-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

CREATE SERVER dbl_aron FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP) (HOST = 192.168.13.14)(PORT = 1521)) (CONNECT_DATA = (SID = UPEU)))');
-- CREATE USER MAPPING FOR "postgres" SERVER dbl_aron OPTIONS (user 'aron' , password 'secret');
CREATE SERVER dbl_aron_app FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP) (HOST = 192.168.13.112)(PORT = 1521)) (CONNECT_DATA = (SID = UPEU)))');
-- CREATE USER MAPPING FOR "postgres" SERVER dbl_aron_app OPTIONS (user 'aron' , password 'secret');
CREATE SERVER dbl_jul FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP) (HOST = 192.168.97.111)(PORT = 1521)) (CONNECT_DATA = (SID = upeu)))');
-- CREATE USER MAPPING FOR "postgres" SERVER dbl_jul OPTIONS (user 'aron' , password 'secret');
CREATE SERVER dbl_noe FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP) (HOST = 192.168.13.14)(PORT = 1521)) (CONNECT_DATA = (SID = UPEU)))');
-- CREATE USER MAPPING FOR "postgres" SERVER dbl_noe OPTIONS (user 'noe' , password 'secret');
