-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_finances_students,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_finances_students_sp_desc_hijo_misionero_mat (P_ID_ALUMNO_CONTRATO bigint,P_ID_CRITERIO_SEMESTRE bigint,P_IMPORTE OUT bigint,P_ID_PARENT OUT bigint,P_ACUMULADO OUT bigint) AS $body$
DECLARE


    l_importe decimal(10,2):=0.00;
    l_importe_cri decimal(10,2):=0.00;
    l_contar integer:=0;
    l_items bigint;
    l_tipo_valor varchar(5);
    l_id_criterio bigint;
    l_id_semestre_programa bigint;
    l_acumula decimal(10,2):=0;
    l_id_criterio_semestre bigint;
    l_id_parent_mi bigint;
    l_acumulado decimal(10,2):=0;

BEGIN
  
    SELECT  COUNT(*) INTO STRICT l_contar
    FROM VW_MAT_CRITERIO_SEMESTRE
    WHERE ID_CRITERIO_SEMESTRE=P_ID_CRITERIO_SEMESTRE;

    IF l_contar=1 THEN
      SELECT 
                importe,
                tipo_valor,
                id_semestre_programa
                INTO STRICT
                l_importe_cri,
                l_tipo_valor,
                l_id_semestre_programa
      FROM VW_MAT_CRITERIO_SEMESTRE
      WHERE ID_CRITERIO_SEMESTRE=P_ID_CRITERIO_SEMESTRE;

      SELECT  COUNT(*) INTO STRICT l_contar
      FROM VW_MAT_CRITERIO_SEMESTRE
      WHERE ID_SEMESTRE_PROGRAMA=l_id_semestre_programa
      AND CODIGO='MAT';

      IF l_contar=1 THEN
          SELECT 
                  id_criterio,
                  id_criterio_semestre
                  INTO STRICT
                  l_id_criterio,
                  l_id_criterio_semestre
        FROM VW_MAT_CRITERIO_SEMESTRE
        WHERE ID_SEMESTRE_PROGRAMA=l_id_semestre_programa
        AND CODIGO='MAT';

        
        select COUNT(*) INTO STRICT l_contar 
        from vw_mat_criterio_semestre a, mat_alumno_contrato_det b
        where a.id_criterio_semestre = b.id_criterio_semestre
        and a.id_criterio=l_id_criterio 
        and b.dc='D'
        and b.id_alumno_contrato=P_ID_ALUMNO_CONTRATO;
        
        if l_contar=1 then
        
          select 
          b.id_alumno_contrato_det into STRICT l_id_parent_mi
          from vw_mat_criterio_semestre a, mat_alumno_contrato_det b
          where a.id_criterio_semestre = b.id_criterio_semestre
          and a.id_criterio=l_id_criterio 
          and b.dc='D'
          and b.id_alumno_contrato=P_ID_ALUMNO_CONTRATO;
          
          select coalesce(max(id_alumno_contrato_det),0) into STRICT l_items
          from mat_alumno_contrato_det
          where id_alumno_contrato=P_ID_ALUMNO_CONTRATO
          and dc='C'
          and id_parent_mis= l_id_parent_mi;

          if l_items>0 then
          
            select acum_mis into STRICT l_acumula
            from mat_alumno_contrato_det
            where id_alumno_contrato=P_ID_ALUMNO_CONTRATO
            and ID_ALUMNO_CONTRATO_DET=l_items;

          else
            select count(*) into STRICT l_contar
            from mat_alumno_contrato_det
            where id_alumno_contrato=P_ID_ALUMNO_CONTRATO
            and dc='C'
            and id_criterio_semestre= l_id_criterio_semestre;

            if l_contar>0 then
              select sum(importe) into STRICT l_acumula
              from mat_alumno_contrato_det
              where id_alumno_contrato=P_ID_ALUMNO_CONTRATO
              and dc='D'
              and id_criterio_semestre= l_id_criterio_semestre;

            end if;
        end if;

        if l_tipo_valor='P' then
          l_importe:= l_acumula * (l_importe_cri/100);
        else
          l_importe:= l_importe_cri;
        end if;
        l_acumulado:= l_acumula - l_importe;
        if l_acumulado<0 then
          l_acumulado:=0;
        end if;

   
        end if;

      END IF;

    END IF;
    P_ID_PARENT:= l_id_parent_mi;
    P_IMPORTE:=l_importe;
    P_ACUMULADO:=l_acumulado;
  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_finances_students_sp_desc_hijo_misionero_mat (P_ID_ALUMNO_CONTRATO bigint,P_ID_CRITERIO_SEMESTRE bigint,P_IMPORTE OUT bigint,P_ID_PARENT OUT bigint,P_ACUMULADO OUT bigint) FROM PUBLIC;
