-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_finances_students,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_finances_students_sp_desc_pronto_pago_ing (P_ID_ALUMNO_CONTRATO bigint,P_ID_CRITERIO_SEMESTRE bigint,P_TIPO_ALUMNO text,P_ERROR OUT bigint,P_MSGERROR out text) AS $body$
DECLARE

    l_items bigint;
    l_contar bigint;
    l_error bigint:=0;
    l_msgerror varchar(200):='';

    l_id_semestre_programa bigint;
    l_id_persona bigint;

    l_id_criterio bigint;
    l_importe decimal(10,2);
    l_dc varchar(5);
    l_dias decimal(10,2);
    l_nombre varchar(150);
    l_tipo_valor varchar(2);
    l_cuotas decimal(10,2);
    l_misionero varchar(2);
    l_id_plan_pago_semestre bigint;
    l_comunidad varchar(1);

BEGIN
  
    SELECT A.ID_SEMESTRE_PROGRAMA,A.ID_PERSONA,coalesce(A.MISIONERO,'N'),A.ID_PLANPAGO_SEMESTRE,coalesce(COMUNIDAD,'N')
    INTO STRICT l_id_semestre_programa,l_id_persona,l_misionero,l_id_plan_pago_semestre,l_comunidad
    FROM DAVID.ACAD_ALUMNO_CONTRATO A
    WHERE A.ID_ALUMNO_CONTRATO = P_ID_ALUMNO_CONTRATO;

    if l_comunidad='N' then
    
      if coalesce(l_id_plan_pago_semestre::text, '') = '' then
        select 
        COUNT(*) INTO STRICT l_contar
        FROM MAT_PLANPAGO_SEMESTRE B,MAT_PLANPAGO C
        WHERE B.ID_PLANPAGO=C.ID_PLANPAGO
        AND B.ID_SEMESTRE_PROGRAMA=l_id_semestre_programa;

        IF l_contar=0 THEN
          l_error:=1;
          l_msgerror:='Falta asignar plan de pago';
--           goto salida_ptopagoing;
        ELSE
          select
          MAX(ID_PLANPAGO_SEMESTRE) INTO STRICT l_id_plan_pago_semestre
          FROM MAT_PLANPAGO_SEMESTRE B,MAT_PLANPAGO C
          WHERE B.ID_PLANPAGO=C.ID_PLANPAGO
          AND B.ID_SEMESTRE_PROGRAMA=l_id_semestre_programa;

          UPDATE DAVID.ACAD_ALUMNO_CONTRATO SET ID_PLANPAGO_SEMESTRE=l_id_plan_pago_semestre WHERE ID_ALUMNO_CONTRATO = P_ID_ALUMNO_CONTRATO;
        END IF;

      end if;

      SELECT A.ID_SEMESTRE_PROGRAMA,A.ID_PERSONA, C.CUOTAS,coalesce(A.MISIONERO,'N')
      INTO STRICT l_id_semestre_programa,l_id_persona,l_cuotas,l_misionero
      FROM DAVID.ACAD_ALUMNO_CONTRATO A, MAT_PLANPAGO_SEMESTRE B,MAT_PLANPAGO C
      WHERE A.ID_PLANPAGO_SEMESTRE=B.ID_PLANPAGO_SEMESTRE
      AND B.ID_PLANPAGO=C.ID_PLANPAGO
      AND A.ID_ALUMNO_CONTRATO = P_ID_ALUMNO_CONTRATO;

      
  
      
      if l_cuotas=1  then
        SELECT 
              ID_CRITERIO,
              IMPORTE,
              DC,
              NOMBRE,
              TIPO_VALOR
              INTO STRICT
              l_id_criterio,
              l_importe,
              l_dc,
              l_nombre,
              l_tipo_valor
          FROM VW_MAT_CRITERIO_SEMESTRE
          WHERE ID_CRITERIO_SEMESTRE=P_ID_CRITERIO_SEMESTRE;

        SELECT COALESCE(MAX(ITEM),0)+1  INTO STRICT l_items FROM MAT_CONCEPTO_ASIGN_ALUM
         WHERE ID_ALUMNO_CONTRATO=P_ID_ALUMNO_CONTRATO;

         insert into MAT_CONCEPTO_ASIGN_ALUM(
          ID_ALUMNO_CONTRATO,
          ID_CRITERIO_SEMESTRE,
          ITEM,
          ID_SEMESTRE_PROGRAMA,
          DESCRIPCION,
          DC,
          TOTAL,
          TIPO_VALOR
          )VALUES (
          P_ID_ALUMNO_CONTRATO,
          P_ID_CRITERIO_SEMESTRE,
          l_items,
          l_id_semestre_programa,
          l_nombre,
          l_dc,
          l_importe,
          l_tipo_valor
          );
      end if;
    end if;
--     <<salida_ptopagoing>>
    P_ERROR:=l_error;
    P_MSGERROR:= l_msgerror;
  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_finances_students_sp_desc_pronto_pago_ing (P_ID_ALUMNO_CONTRATO bigint,P_ID_CRITERIO_SEMESTRE bigint,P_TIPO_ALUMNO text,P_ERROR OUT bigint,P_MSGERROR out text) FROM PUBLIC;
