-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE eliseo.iudp_diario (P_Modo integer, P_ID_ENTIDAD integer, P_COD_AASI integer, P_ID_TIPOASIENTO text, P_FEC_ASIENTO text, P_FEC_DIGITADO text, P_FEC_CONTABILIZADO text, P_NOM_DIGITADOR text, P_NOM_CONTADOR text, P_COMENTARIO text) AS $body$
DECLARE


S_ID_DIARIO     integer;
S_ID_ANHO       integer;
S_ID_MES        integer;
S_ID_EMPRESA        integer;
S_CONT          integer;
S_FEC_ASIENTO   timestamp(0);
S_FEC_DIGITADO  timestamp(0);
S_FEC_CONTABILIZADO timestamp(0);
S_COMENTARIO    varchar(255);

BEGIN
    S_ID_DIARIO := 0;
    S_ID_ANHO := TO_CHAR(to_date(P_FEC_ASIENTO,'yyyy-mm-dd"T"HH24:MI:SS'),'YYYY');
    S_ID_MES := (TO_CHAR(to_date(P_FEC_ASIENTO,'yyyy-mm-dd"T"HH24:MI:SS'),'MM'))::numeric;
    S_COMENTARIO := REPLACE(P_COMENTARIO, '|', ' ');
    S_FEC_ASIENTO := to_date(P_FEC_ASIENTO,'yyyy-mm-dd"T"HH24:MI:SS');
    S_FEC_DIGITADO := to_date(P_FEC_DIGITADO,'yyyy-mm-dd"T"HH24:MI:SS');
    S_FEC_CONTABILIZADO := to_date(P_FEC_CONTABILIZADO,'yyyy-mm-dd"T"HH24:MI:SS');
	
    IF P_Modo = 0 THEN
  
        
        SELECT
                COUNT(ID_DIARIO), max(id_diario)  INTO STRICT S_CONT, S_ID_DIARIO
        FROM CONTA_DIARIO
        WHERE ID_ENTIDAD = P_ID_ENTIDAD
        AND ID_ANHO = S_ID_ANHO
        AND ID_MES = S_ID_MES
        AND ID_TIPOASIENTO = P_ID_TIPOASIENTO
        AND COD_AASI = P_COD_AASI;

        IF S_CONT > 0 THEN
        
            DELETE FROM CONTA_DIARIO_DETALLE
            WHERE ID_ENTIDAD = P_ID_ENTIDAD
            AND ID_DIARIO = S_ID_DIARIO;

            UPDATE CONTA_DIARIO SET
                    FEC_ASIENTO = S_FEC_ASIENTO,
                    FEC_DIGITADO = S_FEC_DIGITADO,
                    FEC_CONTABILIZADO = S_FEC_CONTABILIZADO,
                    NOM_CONTADOR = P_NOM_CONTADOR,
                    NOM_DIGITADOR = P_NOM_DIGITADOR,
                    COMENTARIO = S_COMENTARIO
            WHERE ID_ENTIDAD = P_ID_ENTIDAD
            AND ID_DIARIO = S_ID_DIARIO;

        ELSE
       
            SELECT
                    coalesce(MAX(ID_DIARIO),0)+1 INTO STRICT S_ID_DIARIO
            FROM CONTA_DIARIO
            WHERE ID_ENTIDAD = P_ID_ENTIDAD;

            INSERT INTO CONTA_DIARIO(ID_ENTIDAD, ID_DIARIO, ID_ANHO, ID_MES, ID_TIPOASIENTO, COD_AASI, FEC_ASIENTO, FEC_DIGITADO, FEC_CONTABILIZADO, NOM_DIGITADOR, NOM_CONTADOR, COMENTARIO)
            VALUES (P_ID_ENTIDAD, S_ID_DIARIO, S_ID_ANHO, S_ID_MES, P_ID_TIPOASIENTO, P_COD_AASI, S_FEC_ASIENTO, S_FEC_DIGITADO, S_FEC_CONTABILIZADO, P_NOM_DIGITADOR, P_NOM_CONTADOR, S_COMENTARIO);

        END IF;

       
        -- Seguimiento para obligar al usuario actualizar la paginación
        SELECT
                COUNT(1) INTO STRICT S_CONT
        FROM CONTA_DIARIO_PAGINACION
        WHERE ID_ENTIDAD = P_ID_ENTIDAD
        AND ID_ANHO = S_ID_ANHO;

       	IF S_CONT>0 THEN 
       		
	        UPDATE CONTA_DIARIO_PAGINACION
	        SET FECHA_LOTES_ACTUALIZADOS = clock_timestamp() 
	        WHERE ID_ENTIDAD =P_ID_ENTIDAD
	        AND ID_ANHO =S_ID_ANHO;
       	ELSE
       		SELECT MAX(ID_EMPRESA) INTO STRICT S_ID_EMPRESA FROM CONTA_ENTIDAD ce WHERE ce.ID_ENTIDAD=	P_ID_ENTIDAD;
       	
       		INSERT INTO CONTA_DIARIO_PAGINACION(ID_EMPRESA, ID_ENTIDAD, ID_ANHO, FECHA_LOTES_ACTUALIZADOS)
       		values (S_ID_EMPRESA,P_ID_ENTIDAD, S_ID_ANHO, clock_timestamp());
       	END IF;

       
       
    END IF;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.iudp_diario (P_Modo integer, P_ID_ENTIDAD integer, P_COD_AASI integer, P_ID_TIPOASIENTO text, P_FEC_ASIENTO text, P_FEC_DIGITADO text, P_FEC_CONTABILIZADO text, P_NOM_DIGITADOR text, P_NOM_CONTADOR text, P_COMENTARIO text) FROM PUBLIC;

