-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE eliseo.spc_user_session_finish () AS $body$
DECLARE

   l_time_session      integer := 10;--tiempo maximo de session inactiva
BEGIN
   insert into users_session_log(token,
                                  id_user,
                                  id_entidad,
                                  id_depto,
                                  date_create,
                                  last_update,
                                  status,
                                  id_almacen,
                                  token_oauth)
      SELECT token,
             id_user,
             id_entidad,
             id_depto,
             date_create,
             last_update,
             status,
             id_almacen,
             token_oauth
        from users_session
       where last_update < clock_timestamp() - (l_time_session / 1440)
       and caduca = 'S';

   delete from users_session
         where last_update < clock_timestamp() - (l_time_session / 1440)
         and caduca = 'S';
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.spc_user_session_finish () FROM PUBLIC;

