-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS testing_ai_pk ON testing CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_testing_ai_pk() RETURNS trigger AS $BODY$
DECLARE
   last_Sequence NUMBER;
   last_InsertID NUMBER;
BEGIN
   SELECT TESTING_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   IF (:NEW.ID IS NULL OR :NEW.ID = 0) THEN
      SELECT TESTING_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   ELSE
      SELECT NVL(Last_Number, 0) INTO last_Sequence
        FROM User_Sequences
       WHERE Sequence_Name = 'TESTING_SEQ';
      SELECT :NEW.ID INTO last_InsertID FROM DUAL;
      WHILE (last_InsertID > last_Sequence) LOOP
         SELECT TESTING_SEQ.NEXTVAL INTO last_Sequence FROM DUAL;
      END LOOP;
   END IF;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_testing_ai_pk() FROM PUBLIC;

DROP TRIGGER IF EXISTS testing_ai_pk ON testing;
CREATE TRIGGER testing_ai_pk
	BEFORE INSERT ON testing FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_testing_ai_pk();

