-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_acad_curso_metod_pk ON acad_curso_metodologia CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_acad_curso_metod_pk() RETURNS trigger AS $BODY$
begin
  select sq_acad_curso_metod_id.nextval
  into :new.id_curso_metodologia
  from dual;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_acad_curso_metod_pk() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_acad_curso_metod_pk ON acad_curso_metodologia;
CREATE TRIGGER tr_acad_curso_metod_pk
	BEFORE INSERT ON acad_curso_metodologia FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_acad_curso_metod_pk();

