-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_acad_participante_gf_id ON acad_participante_gf CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_acad_participante_gf_id() RETURNS trigger AS $BODY$
begin
  select sq_ACAD_PARTICIPANTE_GF_id.nextval
  into :new.ID_PARTICIPANTE_GF
  from dual;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_acad_participante_gf_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_acad_participante_gf_id ON acad_participante_gf;
CREATE TRIGGER tr_acad_participante_gf_id
	BEFORE INSERT ON acad_participante_gf FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_acad_participante_gf_id();

