-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_competencia_area_id ON competencia_area CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_competencia_area_id() RETURNS trigger AS $BODY$
BEGIN
  SELECT sq_competencia_area_id.nextval
  INTO :new.id_competencia_area
  FROM dual;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_competencia_area_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_competencia_area_id ON competencia_area;
CREATE TRIGGER tr_competencia_area_id
	BEFORE INSERT ON competencia_area FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_competencia_area_id();

