-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_sn_modulo_canal_persona_id ON sn_modulo_canal_persona CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_sn_modulo_canal_persona_id() RETURNS trigger AS $BODY$
BEGIN
  SELECT SN_MODULO_CANAL_PERSONA_SQ.NEXTVAL
  INTO :NEW.ID_MODULO_CANAL_PERSONA
  FROM dual;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_sn_modulo_canal_persona_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_sn_modulo_canal_persona_id ON sn_modulo_canal_persona;
CREATE TRIGGER tr_sn_modulo_canal_persona_id
	BEFORE INSERT ON sn_modulo_canal_persona FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_sn_modulo_canal_persona_id();

