-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS trig_tr_requisito_id ON tr_requisito CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_trig_tr_requisito_id() RETURNS trigger AS $BODY$
BEGIN
    IF :new.ID_REQUISITO IS NULL THEN
        SELECT DAVID.SQ_TR_REQUISITO_ID.NEXTVAL
        INTO :new.ID_REQUISITO
        FROM dual;
    END IF;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_trig_tr_requisito_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS trig_tr_requisito_id ON tr_requisito;
CREATE TRIGGER trig_tr_requisito_id
	BEFORE INSERT ON tr_requisito FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_trig_tr_requisito_id();

