-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = jairo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_perspectiva_pk ON sge_perspectiva CASCADE;
CREATE OR REPLACE FUNCTION jairo.trigger_fct_tr_perspectiva_pk() RETURNS trigger AS $BODY$
BEGIN
  SELECT nextval('sq_sge_perspectiva_seq')
  INTO STRICT NEW.id_perspectiva
;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION jairo.trigger_fct_tr_perspectiva_pk() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_perspectiva_pk ON sge_perspectiva;
CREATE TRIGGER tr_perspectiva_pk
	BEFORE INSERT ON sge_perspectiva FOR EACH ROW
	EXECUTE PROCEDURE jairo.trigger_fct_tr_perspectiva_pk();

