-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = jairo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_vin_int_rol_part_id ON vin_interv_rol_participante CASCADE;
CREATE OR REPLACE FUNCTION jairo.trigger_fct_tr_vin_int_rol_part_id() RETURNS trigger AS $BODY$
BEGIN
  select nextval('sq_vin_int_rol_part_id')
  into STRICT NEW.ID_INTERV_ROL_PARTICIPANTE
;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION jairo.trigger_fct_tr_vin_int_rol_part_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_vin_int_rol_part_id ON vin_interv_rol_participante;
CREATE TRIGGER tr_vin_int_rol_part_id
	BEFORE INSERT ON vin_interv_rol_participante FOR EACH ROW
	EXECUTE PROCEDURE jairo.trigger_fct_tr_vin_int_rol_part_id();

