-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_init_config,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_init_config_sp_sistema_externo (P_ID_ENTIDAD bigint,P_ID_DEPTO text, P_ERROR OUT bigint,P_MSGERROR out text) AS $body$
DECLARE

        l_contar bigint := 0;
        l_id_entidad_base bigint := 72122;
        l_id_depto_base varchar(15) := '121211';
        l_id_user bigint := 7932;

        base_sistema_externo CURSOR FOR
        SELECT * from eliseo.sistema_externo where id_entidad = l_id_entidad_base and id_depto = l_id_depto_base;



BEGIN
        FOR bsistema_externo in base_sistema_externo LOOP

            select count(1) into STRICT l_contar from eliseo.sistema_externo 
                where id_entidad = P_ID_ENTIDAD
                and id_depto = P_ID_DEPTO
                and id_tipoasiento = bsistema_externo.id_tipoasiento;

            if l_contar = 0 then
                insert into eliseo.sistema_externo 
                values (null, P_ID_ENTIDAD, P_ID_DEPTO, bsistema_externo.id_tipoasiento,
                        bsistema_externo.codigo, bsistema_externo.nombre, bsistema_externo.estado);
                RAISE NOTICE 'Sistemas externo : % creado, cant:%', bsistema_externo.id_tipoasiento, l_contar;
            else
                RAISE NOTICE 'Sistemas externo : % existente, cant:%', bsistema_externo.id_tipoasiento, l_contar;
            end if;



        end loop;
        P_ERROR := 0;
        P_MSGERROR := 'Sistema externo revisado y actualizado';
    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_init_config_sp_sistema_externo (P_ID_ENTIDAD bigint,P_ID_DEPTO text, P_ERROR OUT bigint,P_MSGERROR out text) FROM PUBLIC;
