-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE david.pcd_create_copia_plan_pre ( p_id_plan integer, p_id_usuario_reg integer ) AS $body$
DECLARE


    --lista de cursos del máximo plan
    curso_plan_pre CURSOR FOR
      SELECT (SELECT id_plan_curso from Acad_Plan_Curso where id_plan=p_id_plan and id_curso_detalle=apc.id_curso_detalle) id_plan_curso,
              (select id_plan_curso from Acad_Plan_Curso where id_plan=p_id_plan and id_curso_detalle=apcp.id_curso_detalle) id_plan_curso_req,
              apr.estado
      from Acad_Pre_Requisito apr
      inner join (select id_plan_curso, id_curso_detalle 
                  from Acad_Plan_Curso 
                  where id_plan=(select id_plan from acad_plan 
                                where (Id_Area,Nombre) = (select id_area,max(nombre) 
                                                          from Acad_Plan where id_area=(select id_area from acad_plan where id_plan=p_id_plan) 
                                                          and id_plan<>p_id_plan 
                                                          group by id_area) ) ) apc 
            on apc.id_plan_curso=apr.id_plan_curso
      inner join Acad_Plan_Curso apcp on apcp.id_plan_curso=apr.id_plan_curso_req;

BEGIN


  for reg in curso_plan_pre
  loop
  
    --registra los requisitos activos al alumno en el semestre activo
    insert into Acad_Pre_Requisito(id_plan_curso,
    id_plan_curso_req,
    estado,
    id_usuario_reg,
    fecha_registro)
    values (reg.id_plan_curso,
          reg.id_plan_curso_req,
          reg.estado,
          p_id_usuario_reg,
          clock_timestamp());

  end loop;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE david.pcd_create_copia_plan_pre ( p_id_plan integer, p_id_usuario_reg integer ) FROM PUBLIC;

