-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE david.pcd_act_avance_silabo2024 ( pval integer) AS $body$
DECLARE


p_id_semestre integer;


BEGIN

    SELECT MAX(ID_SEMESTRE) into STRICT p_id_semestre
    FROM DAVID.ACAD_SEMESTRE WHERE ESTADO_ADVISER=1;

    DELETE FROM AATEMP_AVANCE_SILABO2024 WHERE ID_SEMESTRE=p_id_semestre;
    commit;
    
    INSERT INTO AATEMP_AVANCE_SILABO2024
    SELECT ACA.ID_SEMESTRE,Aca.Id_Carga_Curso,Os.Nombre sede,Aca.Nom_Facultad,Aca.Nom_Escuela,Aca.Ciclo,Aca.Grupo,Aca.Nombre_Curso,
    coalesce(cs.sumilla,0) sumilla,coalesce(cc.competencia,0) competencia,coalesce(cra.resultado_aprendizaje,0) resultado_aprendizaje,
    coalesce(cu.unidad,0) unidades,coalesce(CT.CANTIDAD_TEMAS,0)CANTIDAD_TEMAS,coalesce(CT.TIENE_TEMAS,0) TIENE_TEMAS,
    coalesce(ct.temas,'NO') temas,coalesce(cta.tema_anexo,0) tema_anexo,
    coalesce(cev.TIENE_EVALUACION,0) TIENE_EVALUACION, coalesce(cev.evaluaciones,'NO') evaluaciones,coalesce(CEV.PESO,0) PESO,
    coalesce(ce.estrategias,0) estrategias,
    coalesce(cr.recursos,0) recursos,coalesce(cb.bibliografia,0) bibliografia
    from Vw_Acad_Carga_Academica aca inner join eliseo.org_sede os on os.id_sede=aca.id_sede
    left join(SELECT id_carga_curso, 1 sumilla from Acad_Carga_Sumilla
                group by id_carga_curso) cs on cs.id_carga_curso=aca.id_carga_curso
    left join(select id_carga_curso, 1 competencia from Acad_Carga_Competencia
                group by id_carga_curso) cc on cc.id_carga_curso=aca.id_carga_curso
    left join(select id_carga_curso, 1 unidad from Acad_Carga_unidad
                group by id_carga_curso) cu on cu.id_carga_curso=aca.id_carga_curso
    left join(select id_carga_curso, 1 recursos from PLANTILLA_CURSO_RECURSO
                group by id_carga_curso) cr on cr.id_carga_curso=aca.id_carga_curso
    left join(select id_carga_curso, 1 estrategias from plantilla_curso_estrategia
                group by id_carga_curso) ce on ce.id_carga_curso=aca.id_carga_curso
    left join(select id_carga_curso, 1 bibliografia from Acad_Carga_Bibliografia
                group by id_carga_curso) cb on cb.id_carga_curso=aca.id_carga_curso
    left join(select id_carga_curso, 1 resultado_aprendizaje from Acad_Carga_Curso_Res_Ap
                group by id_carga_curso) cra on cra.id_carga_curso=aca.id_carga_curso
    left join (select ct.id_carga_curso, count(1) CANTIDAD_TEMAS,1 TIENE_TEMAS,
                (case when count(1)>=16 then 'COMPLETO' ELSE 'INCOMPLETO' END) TEMAS
                from Acad_Carga_unidad cu inner join acad_carga_tema ct on ct.id_carga_curso=cu.id_carga_curso 
                                          and Ct.Id_Carga_Unidad=Cu.Id_Carga_Unidad
                group by ct.id_carga_curso) ct on ct.id_carga_curso=aca.id_carga_curso
    left join(select ct.id_carga_curso, 1 tema_anexo
                from Acad_Carga_unidad cu inner join acad_carga_tema ct on ct.id_carga_curso=cu.id_carga_curso 
                                          and Ct.Id_Carga_Unidad=Cu.Id_Carga_Unidad
                inner join acad_carga_tema_anexo cta ON cta.id_carga_tema =ct.id_carga_tema
                group by ct.id_carga_curso) cta on cta.id_carga_curso=aca.id_carga_curso
    left join (select ce.id_carga_curso, sum(peso) PESO, 1 TIENE_EVALUACION,
                (case when sum(peso)=100 then 'COMPLETO'
                      when sum(peso)>100 then 'EXCEDIDO'
                      ELSE 'INCOMPLETO' end) evaluaciones
                      from ( select ce.id_carga_curso,Ce.Id_Carga_Evaluacion, peso peso from Acad_Carga_Evaluacion ce 
                            inner join Acad_Carga_Evaluacion_Detalle ced on Ced.Id_Carga_Evaluacion=Ce.Id_Carga_Evaluacion
                            where ce.estado='1'
                            
union
 
                            select ce.id_carga_curso,Ce.Id_Carga_Evaluacion,ce.ponderado peso from Acad_Carga_Evaluacion ce 
                            where ce.estado='1' and (ce.id_carga_competencia IS NOT NULL AND ce.id_carga_competencia::text <> '') ) ce 
                group by ce.id_carga_curso) cev on cev.id_carga_curso=aca.id_carga_curso 
    where Aca.Id_Formato_Silabo=4 and Aca.Id_Semestre=p_id_semestre and Aca.Id_Nivel_Ensenanza=1
    order by Os.Nombre desc,Aca.Nom_Facultad,Aca.Nom_Escuela,Aca.Ciclo,Aca.Grupo,Aca.Nombre_Curso
;
    COMMIT;

END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE david.pcd_act_avance_silabo2024 ( pval integer) FROM PUBLIC;

