-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE david.pcd_reg_candado_ingles_sem (v_id_semestre integer) AS $body$
BEGIN

     --general
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct ID_PERSONA,ID_TIPO_CANDADO,v_id_semestre,min(FECHA_INICIO),min(FECHA_FIN),min(DESCRIPCION),max(ESTADO),min(ID_USUARIO_REG),max(clock_timestamp())
    from acad_candado ac where id_semestre=(SELECT id_semestre_ant from acad_semestre asm where asm.id_semestre=v_id_semestre) and id_tipo_candado Between 13 and 17
    and id_persona not in (select id_persona from acad_candado where id_semestre=v_id_semestre and id_tipo_candado=ac.id_tipo_candado) 
    group by ID_PERSONA,ID_TIPO_CANDADO,v_id_semestre;
    commit;

    --básico I
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct Aca.Id_Persona,12,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado desde notas del Académico',1,8345,clock_timestamp()
    from acad_curso_alumno aca inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Aca.Id_Curso_Detalle
    inner join acad_curso ac on Ac.Id_Curso=acd.id_curso
    where id_tipo_condicion=1
    and ac.nombre in ('Inglés Básico I','Inglés I','Inglés Básico II','Inglés II','Inglés Intermedio I','Inglés III','Inglés Intermedio II','Inglés IV','Inglés Avanzado I','Inglés Avanzado','Inglés V','Inglés Avanzado II','Inglés VI')
    and Aca.Id_Persona not in (SELECT ID_PERSONA from acad_candado where ID_TIPO_CANDADO=12 and ID_SEMESTRE=v_id_semestre);
    commit;

    --básico II
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct Aca.Id_Persona,13,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado desde notas del Académico',1,8345,clock_timestamp()
    from acad_curso_alumno aca inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Aca.Id_Curso_Detalle
    inner join acad_curso ac on Ac.Id_Curso=acd.id_curso
    where id_tipo_condicion=1
    and ac.nombre in ('Inglés Básico II','Inglés II','Inglés Intermedio I','Inglés III','Inglés Intermedio II','Inglés IV','Inglés Avanzado I','Inglés Avanzado','Inglés V','Inglés Avanzado II','Inglés VI')
    and Aca.Id_Persona not in (SELECT ID_PERSONA from acad_candado where ID_TIPO_CANDADO=13 and ID_SEMESTRE=v_id_semestre);
    commit;

    --intermedio I
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct Aca.Id_Persona,16,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado desde notas del Académico',1,8345,clock_timestamp()
    from acad_curso_alumno aca inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Aca.Id_Curso_Detalle
    inner join acad_curso ac on Ac.Id_Curso=acd.id_curso
    where id_tipo_condicion=1
    and ac.nombre in ('Inglés Intermedio I','Inglés III','Inglés Intermedio II','Inglés IV','Inglés Avanzado I','Inglés Avanzado','Inglés V','Inglés Avanzado II','Inglés VI')
    and Aca.Id_Persona not in (SELECT ID_PERSONA from acad_candado where ID_TIPO_CANDADO=16 and ID_SEMESTRE=v_id_semestre);
    commit;

    --intermedio II
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct Aca.Id_Persona,17,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado desde notas del Académico',1,8345,clock_timestamp()
    from acad_curso_alumno aca inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Aca.Id_Curso_Detalle
    inner join acad_curso ac on Ac.Id_Curso=acd.id_curso
    where id_tipo_condicion=1
    and ac.nombre in ('Inglés Intermedio II','Inglés IV','Inglés Avanzado I','Inglés Avanzado','Inglés V','Inglés Avanzado II','Inglés VI')
    and Aca.Id_Persona not in (SELECT ID_PERSONA from acad_candado where ID_TIPO_CANDADO=17 and ID_SEMESTRE=v_id_semestre);
    commit;

    --Avansado I
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct Aca.Id_Persona,14,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado desde notas del Académico',1,8345,clock_timestamp()
    from acad_curso_alumno aca inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Aca.Id_Curso_Detalle
    inner join acad_curso ac on Ac.Id_Curso=acd.id_curso
    where id_tipo_condicion=1
    and ac.nombre in ('Inglés Avanzado I','Inglés Avanzado','Inglés V','Inglés Avanzado II','Inglés VI')
    and Aca.Id_Persona not in (SELECT ID_PERSONA from acad_candado where ID_TIPO_CANDADO=14 and ID_SEMESTRE=v_id_semestre);
    commit;

    --Avansado II
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct Aca.Id_Persona,15,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado desde notas del Académico',1,8345,clock_timestamp()
    from acad_curso_alumno aca inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Aca.Id_Curso_Detalle
    inner join acad_curso ac on Ac.Id_Curso=acd.id_curso
    where id_tipo_condicion=1
    and ac.nombre in ('Inglés Avanzado II','Inglés VI')
    and Aca.Id_Persona not in (SELECT ID_PERSONA from acad_candado where ID_TIPO_CANDADO=15 and ID_SEMESTRE=v_id_semestre);
    commit;

    --básico I
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct ID_PERSONA,12,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado de Candado',1,8345,clock_timestamp()
    from acad_candado ac where id_semestre=v_id_semestre and id_tipo_candado in (13,14,15,16,17)
    and id_persona not in (SELECT id_persona from acad_candado where id_semestre=v_id_semestre and id_tipo_candado=12);

    --básico II
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct ID_PERSONA,13,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado de Candado',1,8345,clock_timestamp()
    from acad_candado ac where id_semestre=v_id_semestre and id_tipo_candado in (14,15,16,17)
    and id_persona not in (SELECT id_persona from acad_candado where id_semestre=v_id_semestre and id_tipo_candado=13);

    --intermedio I
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct ID_PERSONA,16,v_id_semestre,max(clock_timestamp()),max(clock_timestamp()),'Migrado de Candado',1,8345,max(clock_timestamp())
    from acad_candado ac where id_semestre=v_id_semestre and id_tipo_candado in (14,15,17)
    and id_persona not in (SELECT id_persona from acad_candado where id_semestre=v_id_semestre and id_tipo_candado=16) 
    group by ID_PERSONA,16,v_id_semestre,'Migrado de Candado',1,8345;

    --intermedio II
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct ID_PERSONA,17,v_id_semestre,max(clock_timestamp()),max(clock_timestamp()),'Migrado de Candado',1,8345,max(clock_timestamp())
    from acad_candado ac where id_semestre=v_id_semestre and id_tipo_candado in (14,15)
    and id_persona not in (SELECT id_persona from acad_candado where id_semestre=v_id_semestre and id_tipo_candado=17) 
    group by ID_PERSONA,17,v_id_semestre,'Migrado de Candado',1,8345;

    --Avansado I
    insert into ACAD_CANDADO(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct ID_PERSONA,14,v_id_semestre,clock_timestamp(),clock_timestamp(),'Migrado de Candado',1,8345,clock_timestamp()
    from acad_candado ac where id_semestre=v_id_semestre and id_tipo_candado in (15)
    and id_persona not in (SELECT id_persona from acad_candado where id_semestre=v_id_semestre and id_tipo_candado=14);

    commit;

    --Carga Centro de Idiomas
    insert into acad_candado(ID_PERSONA,ID_TIPO_CANDADO,ID_SEMESTRE,FECHA_INICIO,FECHA_FIN,DESCRIPCION,ESTADO,ID_USUARIO_REG,FECHA_REGISTRO)
    SELECT Distinct * from (
    SELECT id_persona,CASE WHEN nombre_curso='Básico I' THEN 12 WHEN nombre_curso='Basic I' THEN 12 WHEN nombre_curso='Básico II' THEN 13 WHEN nombre_curso='Basic II' THEN 13 WHEN nombre_curso='Intermedio I' THEN 16 WHEN nombre_curso='Intermedio II' THEN 17 WHEN nombre_curso='Intermedíate II' THEN 17 WHEN nombre_curso='Avanzado I' THEN 14 WHEN nombre_curso='Avanzado II' THEN 15  ELSE 0 END  ID_TIPO_CANDADO,
    v_id_semestre ID_SEMESTRE,clock_timestamp() FECHA_INICIO, clock_timestamp() FECHA_FIN,'Cursos de carga' DESCRIPCION,ESTADO,8345 ID_USUARIO_REG,clock_timestamp() FECHA_REGISTRO
    from vw_acad_curso_alumno where id_facultad=72 and estado='1'
    and nombre_curso in ('Básico I','Basic I','Básico II','Basic II','Intermedio I','Intermedio II','Intermedíate II','Avanzado I','Avanzado II') ) alias5
    where (ID_PERSONA,ID_TIPO_CANDADO) not in (select ID_PERSONA,ID_TIPO_CANDADO from acad_candado where id_semestre=v_id_semestre);

    commit;

  end;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE david.pcd_reg_candado_ingles_sem (v_id_semestre integer) FROM PUBLIC;

