-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

PROCEDURE SP_INDICATORS_FINANCIAL (P_ENTIDAD INT, P_ANHO INT,P_MES INT,P_DATA OUT TYPES.cursor_type)                                                    
AS
L_MESES VARCHAR2(50);
BEGIN
    
        FOR I IN 1..P_MES LOOP
            IF I = 1 THEN
                L_MESES := 1;
            ELSE
                L_MESES := L_MESES||','||I;
            END IF;
        END LOOP;
    --DISPONIBLE SEGUN BALANCE
    OPEN P_DATA FOR
    --SELECT *
     --FROM (
     SELECT 'DISPONIBLE' GLOSA,
                  ID_MES,
                  SUM (IMP) OVER (ORDER BY ID_MES ROWS UNBOUNDED PRECEDING)
                     AS IMP
             FROM (  SELECT A.ID_MES, SUM (A.COS_VALOR) IMP
                       FROM VW_CONTA_DIARIO A
                      WHERE     A.ID_ENTIDAD = P_ENTIDAD
                            AND A.ID_ANHO = P_ANHO
                            AND A.ID_MES BETWEEN 1 AND P_MES
                            AND SUBSTR (A.ID_CUENTAAASI, 1, 3) = '111'
                   GROUP BY A.ID_MES);
                   --);
          /*PIVOT
             (SUM (IMP) FOR ID_MES IN (L_MESES));*/
END SP_INDICATORS_FINANCIAL;

