-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

PROCEDURE SP_VENTA_BOLSA(P_ID_MOV_VNT VARCHAR2)IS
S_GRAVADA NUMBER(10,2);
S_IGV NUMBER(10,2);
S_OTROS_CARGOS NUMBER(10,2);
 BEGIN
UPDATE  
ELISEO.VENTA_DETALLE
SET precio=(0.40*cantidad) ,precio_base=round((0.40*cantidad)/1.18,2) ,base=round((0.40*cantidad)/1.18,2)  , IGV=round(((0.40*cantidad)/1.18)*0.18,2),otros_cargos=(0.10*cantidad)
where ID_ARTICULO = 55564
and ID_VENTA=P_ID_MOV_VNT;

SELECT SUM(BASE) BASE, SUM(IGV) IGV, SUM(OTROS_CARGOS) OTROS_CARGOS INTO S_GRAVADA,S_IGV, S_OTROS_CARGOS
FROM ELISEO.VENTA_DETALLE
where ID_VENTA=P_ID_MOV_VNT;

UPDATE ELISEO.VENTA
SET gravada=S_GRAVADA,IGV=S_IGV,OTROS_CARGOS=S_OTROS_CARGOS
WHERE ID_VENTA=P_ID_MOV_VNT;
END SP_VENTA_BOLSA;

