-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

PROCEDURE spc_profile_worker_tipo (
    p_id_persona           int,
    p_tipo  int,
    cursor       OUT SYS_REFCURSOR
)
IS
    
    l_ID_ENTIDAD number(38,2);
    l_ID_ANHO number(38,2);
    l_ID_MES number(38,2);
    l_ID_TIPOESTATUS number(38,2);
    l_ID_SISTEMAPENSION number(38,2);
    l_ES_MISIONERO number(38,2);
    l_NOM_CARGO varchar2(50);
    l_FMR number(38,2);
    l_TIPO_STATUS varchar2(100);
    l_SISTEMA_PENSION varchar2(100);
    l_ANHOS_SERVICIO number(38,2);
    

BEGIN
    select 
    p.ID_ENTIDAD, 
    p.ID_ANHO,
    p.ID_MES,
    p.ID_TIPOESTATUS,
    p.ID_SISTEMAPENSION,
    p.ES_MISIONERO,
    p.NOM_CARGO,
    p.FMR
    INTO 
    l_ID_ENTIDAD,
    l_ID_ANHO,
    l_ID_MES,
    l_ID_TIPOESTATUS,
    l_ID_SISTEMAPENSION,
    l_ES_MISIONERO,
    l_NOM_CARGO,
    l_FMR
    from APS_PLANILLA p
          where p.id_persona = p_id_persona
          and to_date (p.id_anho||lpad(p.id_mes,2,'0'),'yyyymm') = (
          select max(to_date(pp.id_anho||lpad(pp.id_mes,2,'0'),'yyyymm')) from APS_PLANILLA pp
          where pp.id_persona = p_id_persona
          )
    ;
    
    SELECT NOMBRE INTO l_TIPO_STATUS FROM TIPO_ESTATUS
    WHERE ID_TIPOESTATUS = l_ID_TIPOESTATUS;
    
    SELECT NOMBRE INTO l_SISTEMA_PENSION FROM APS_SISTEMA_PENSION
    WHERE ID_SISTEMAPENSION = l_ID_SISTEMAPENSION;
    
    SELECT (SYSDATE - MIN(FEC_INICIO))/ 365.242199 INTO l_ANHOS_SERVICIO FROM APS_EMPLEADO
    WHERE ID_PERSONA = p_id_persona;

    OPEN cursor FOR 
    SELECT 
    l_ID_ENTIDAD AS ID_ENTIDAD,
    l_ID_ANHO AS ID_ANHO,
    l_ID_MES AS ID_MES,
    l_NOM_CARGO AS NOM_CARGO,
    l_ES_MISIONERO AS ES_MISIONERO,
    l_FMR AS PUNTAJE,
    l_TIPO_STATUS AS TIPO_STATUS,
    l_SISTEMA_PENSION AS SISTEMA_PENSION,
    l_ANHOS_SERVICIO AS ANHOS_SERVICIO
    FROM DUAL;
  
END;

