-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

PROCEDURE TEMP_SP_VALIDAR_AJUSTE_PAGO_C(P_ID_PAGO_COMPRA NUMBER, P_ID_PERSONA NUMBER, P_ERROR OUT NUMBER, P_MSGERROR OUT VARCHAR2)
   IS
        L_ID_PAGO NUMBER;
        L_ID_COMPRA NUMBER;
        L_ID_MONEDA_PAGO NUMBER;

        L_IMPORTE_ME_COMPRA NUMBER;
        L_TIPOCAMBIO_COMPRA NUMBER;
        L_ID_VOUCHER_COMPRA NUMBER;
        L_ID_PROVEEDOR_COMPRA NUMBER;
        L_CORRELATIVO_COMPRA NUMBER;

        L_IMPORTE_PAGO_TCC NUMBER :=0; -- Importe pagado según el tipo de cambio de la compra.
        L_IMPORTE_PAGO_TCC_DIF NUMBER :=0; -- Diferencia
        L_IMPORTE_PAGO_TCC_DIF_POS NUMBER :=0; -- Diferencia
        L_ID_ENTIDAD_PAGO NUMBER;
        L_ID_DEPTO_PAGO NUMBER;
        L_ID_ANHO_PAGO NUMBER;
        L_ID_MES_PAGO NUMBER;
        L_ID_PERSONA_PAGO NUMBER;
        L_ID_VOUCHER_PAGO NUMBER;
        L_FECHA_REG_PAGO DATE;

        L_DC_AJUSTE VARCHAR2(10):='';
        L_ID_DINAMICA NUMBER:=0;
        L_ID_AJUSTE NUMBER:=0;
        L_ID_TIPOORIGEN_AJUSTE NUMBER:=0;
        L_NUMERO_AJUSTE VARCHAR2(8):='';
        L_FECHA_AJUSTE DATE;

        L_IMPORTE_PAGO NUMBER;
        L_IMPORTE_ME_PAGO NUMBER;


        L_ID_ASIENTO NUMBER;
        L_ID_PARENT NUMBER;
        L_ID_TIPO_PLAN NUMBER;
        L_ID_RESTRICCION VARCHAR2(50);
        L_ID_CUENTAAASI VARCHAR2(10);
        L_DC VARCHAR2(1);
        L_DESTINO VARCHAR2(1);
        L_ID_INDICADOR VARCHAR2(35);
        L_UNICO VARCHAR2(1);
        L_UNICOCTACTE VARCHAR2(1);
        L_PORCENTAJE NUMBER(10,2);
        L_DESCRIPCION VARCHAR2(255);
        L_AGRUPA VARCHAR2(1);

        L_ID_FONDO VARCHAR2(50);

        L_IMPORTE NUMBER(10,2):=0;
        L_IMPORTE_ME NUMBER(10,2):=0;

        L_DEPTO VARCHAR2(10);
        l_DEPTOS VARCHAR2(200) := '';
        L_CUENTA_CTE VARCHAR2(50);
        L_CTATES VARCHAR2(200);
        L_BUSCAR NUMBER;

        L_CTAS varchar2(200);
        L_ACTAS tablastring;
        L_ADEPTOS tablastring;
        L_ACTATES tablastring;

        L_CONT number;

        CURSOR casi IS		
        SELECT a.ID_ASIENTO,a.ID_PARENT,a.ID_TIPOPLAN,a.ID_RESTRICCION,
        a.ID_CUENTAAASI,a.DC,a.DESTINO,a.ID_INDICADOR,a.UNICO,a.UNICO_CTACTE,a.PORCENTAJE,
        a.NOMBRE,a.AGRUPA,A.ID_FONDO
        FROM CONTA_DINAMICA_ASIENTO a
        WHERE a.ID_DINAMICA =L_ID_DINAMICA
        AND COALESCE(a.ID_PARENT,0)=0 
        ORDER BY a.NRO_ASIENTO,a.DC desc;

        l_error number:=0;
        l_msgerror varchar2(200):='';
   BEGIN
        l_error:=0;
        --l_msgerror:=P_ID_PAGO_COMPRA;
        IF l_error = 0 THEN

           SELECT ID_PAGO, ID_COMPRA, COALESCE(IMPORTE, 0), COALESCE(IMPORTE_ME, 0), ID_DINAMICA INTO L_ID_PAGO, L_ID_COMPRA,
           L_IMPORTE_PAGO, L_IMPORTE_ME_PAGO, L_ID_DINAMICA
           FROM CAJA_PAGO_COMPRA WHERE ID_PCOMPRA=P_ID_PAGO_COMPRA;

           SELECT  COALESCE(IMPORTE_ME, 0), COALESCE(TIPOCAMBIO, 0), ID_VOUCHER, ID_PROVEEDOR, CORRELATIVO 
                INTO L_IMPORTE_ME_COMPRA, L_TIPOCAMBIO_COMPRA, L_ID_VOUCHER_COMPRA, L_ID_PROVEEDOR_COMPRA, L_CORRELATIVO_COMPRA
                FROM COMPRA WHERE ID_COMPRA = L_ID_COMPRA;

           SELECT ID_MONEDA, ID_ENTIDAD, ID_DEPTO, ID_ANHO, ID_MES, ID_PERSONA, ID_VOUCHER, FECHA_REG INTO L_ID_MONEDA_PAGO, L_ID_ENTIDAD_PAGO,
           L_ID_DEPTO_PAGO
           , L_ID_ANHO_PAGO, L_ID_MES_PAGO, L_ID_PERSONA_PAGO, L_ID_VOUCHER_PAGO, L_FECHA_REG_PAGO
           FROM CAJA_PAGO WHERE ID_PAGO=L_ID_PAGO;

           IF L_ID_MONEDA_PAGO <> '7' THEN -- Moneda extranjera
               L_IMPORTE_PAGO_TCC := (L_IMPORTE_ME_PAGO * L_TIPOCAMBIO_COMPRA);

               L_IMPORTE_PAGO_TCC_DIF := L_IMPORTE_PAGO-L_IMPORTE_PAGO_TCC;

               IF L_IMPORTE_PAGO_TCC_DIF<>0 THEN
                    -- Agregar Ajuste
                    IF L_IMPORTE_PAGO_TCC_DIF > 0 THEN
                        L_DC_AJUSTE := 'D';
                        L_IMPORTE_PAGO_TCC_DIF_POS:=L_IMPORTE_PAGO_TCC_DIF;
                    ELSE 
                        L_DC_AJUSTE := 'C';
                        L_IMPORTE_PAGO_TCC_DIF_POS := L_IMPORTE_PAGO_TCC_DIF*-1;
                    END IF;

                    -- Eliminar ajustes anteriores y sus asientos
                    DELETE CONTA_ASIENTO WHERE ID_TIPOORIGEN=4 AND ID_ORIGEN IN ( 
                                SELECT ID_AJUSTE FROM COMPRA_AJUSTE WHERE ID_DINAMICA=L_ID_DINAMICA AND ID_COMPRA=L_ID_COMPRA);
                    DELETE COMPRA_AJUSTE WHERE ID_DINAMICA=L_ID_DINAMICA AND ID_COMPRA=L_ID_COMPRA;

                    TEMP_SP_CREAR_AJUSTE(
                    L_ID_ENTIDAD_PAGO, L_ID_DEPTO_PAGO, L_ID_ANHO_PAGO, L_ID_MES_PAGO, P_ID_PERSONA, L_ID_COMPRA,
                    L_ID_DINAMICA,
                    L_ID_VOUCHER_PAGO, L_FECHA_REG_PAGO, L_IMPORTE_PAGO_TCC_DIF_POS, 
                    --IMPORTE_ME,
                    0, L_DC_AJUSTE, L_ID_AJUSTE, l_error );


                    IF l_error = 0 AND L_ID_DINAMICA IS NOT NULL THEN
                        OPEN casi;
                        FETCH casi INTO L_ID_ASIENTO, L_ID_PARENT, L_ID_TIPO_PLAN, L_ID_RESTRICCION,
                                    L_ID_CUENTAAASI,L_DC, L_DESTINO, L_ID_INDICADOR,L_UNICO,L_UNICOCTACTE,
                                    L_PORCENTAJE,L_DESCRIPCION,L_AGRUPA, L_ID_FONDO;

                        WHILE casi%FOUND LOOP

                            L_DEPTO:=NULL;
                            L_CUENTA_CTE:=NULL;

                            IF L_UNICO='U' THEN -- Único
                                -- SELECT MAX(ID_DEPTO) INTO L_DEPTO FROM CONTA_DINAMICA_DEPTO WHERE ID_ENTIDAD=P_ID_ENTIDAD;
                                SELECT MAX(ID_DEPTO) INTO L_DEPTO FROM CONTA_DINAMICA_DEPTO WHERE ID_ASIENTO=L_ID_ASIENTO;
                            ELSIF(L_UNICO='M') THEN -- Muchos
                                SELECT INSTR(l_DEPTOS, '|') INTO L_BUSCAR FROM dual;
                                IF L_BUSCAR>0 THEN
                                    SELECT FC_SPLIT(L_CTAS,'|') INTO L_ACTAS  FROM dual;
                                    SELECT FC_SPLIT(L_DEPTOS,'|') INTO L_ADEPTOS  FROM dual; 
                                    SELECT FC_OBTENER_DPTOCTCTE(L_ACTAS,L_ADEPTOS ,L_ID_CUENTAAASI) INTO L_DEPTO FROM dual;
                                ELSE
                                    L_DEPTO:=L_DEPTOS;
                                END IF;
                            ELSIF L_UNICO='S' THEN -- Si es sesión
                                L_DEPTO := L_ID_DEPTO_PAGO;
                            END IF;

                            IF L_UNICOCTACTE='U' THEN
                              SELECT  count(*) INTO L_CONT FROM CONTA_DINAMICA_CTA_CTE WHERE ID_ASIENTO=L_ID_ASIENTO;
                              if L_CONT>0 THEN
                                SELECT ID_CTACTE INTO L_CUENTA_CTE FROM CONTA_DINAMICA_CTA_CTE WHERE ID_ASIENTO=L_ID_ASIENTO;
                              END IF;
                            ELSIF(L_UNICOCTACTE='M') THEN
                               SELECT INSTR(L_CTATES, '|') INTO L_BUSCAR FROM dual;
                               if l_buscar>0 THEN
                                 SELECT FC_SPLIT(L_CTAS,'|') INTO L_ACTAS  FROM dual;
                                 SELECT FC_SPLIT(L_CTATES,'|') INTO L_ACTATES  FROM dual; 
                                 SELECT FC_OBTENER_DPTOCTCTE(L_ACTAS,L_ACTATES ,L_ID_CUENTAAASI) INTO L_CUENTA_CTE FROM dual;
                               ELSE
                                L_CUENTA_CTE:=L_CTATES;
                               END IF;
                            ELSIF(L_UNICOCTACTE='X') THEN
                                SELECT PKG_PURCHASES.FC_RUC(L_ID_PROVEEDOR_COMPRA) into L_CUENTA_CTE from dual;
                            END IF;

                            L_IMPORTE :=  (L_IMPORTE_PAGO_TCC_DIF)*(L_PORCENTAJE);
                            IF L_DC='C' THEN
                                L_IMPORTE:= case when L_IMPORTE > 0 then L_IMPORTE *(-1) ELSE L_IMPORTE END;
                                L_IMPORTE_ME:=0;
                             ELSE 
                                L_IMPORTE := case when L_IMPORTE > 0 then L_IMPORTE ELSE L_IMPORTE *(-1) END;
                                L_IMPORTE_ME := 0;
                            END IF;


                            SELECT ID_TIPOORIGEN, NUMERO, FECHA INTO L_ID_TIPOORIGEN_AJUSTE, L_NUMERO_AJUSTE, L_FECHA_AJUSTE FROM COMPRA_AJUSTE WHERE ID_AJUSTE=L_ID_AJUSTE;
                            IF L_IMPORTE_PAGO_TCC_DIF > 0 AND L_ID_INDICADOR = 'VARIACION_CAMBIARIA_PASIVO' THEN 

                                   INSERT INTO CONTA_ASIENTO (
                                            ID_TIPOORIGEN,
                                            ID_ORIGEN, 
                                            FONDO,
                                            DEPTO,
                                            CUENTA, 
                                            CUENTA_CTE,
                                            RESTRICCION,
                                            IMPORTE,
                                            DESCRIPCION,
                                            MEMO,
                                            VOUCHER, 
                                            PARENT_ID,
                                            REF_ID,
                                            AGRUPA
                                    )VALUES ( 
                                            L_ID_TIPOORIGEN_AJUSTE,
                                            L_ID_AJUSTE,
                                            L_ID_FONDO,
                                            L_DEPTO,
                                            L_ID_CUENTAAASI,
                                            L_CUENTA_CTE,
                                            L_ID_RESTRICCION,
                                            L_IMPORTE,
                                            --'VARIACION CAMBIARIA DEL PASIVO TC',
                                            SUBSTR((L_ID_ENTIDAD_PAGO || '-' || L_CORRELATIVO_COMPRA || ' ' || L_NUMERO_AJUSTE || '-' ||TO_CHAR(L_FECHA_AJUSTE, 'DD/MM/YYYY') || '-' || 'VAR-CAMB-PASIVO-TC'),1,50),
                                            L_ID_AJUSTE,
                                            L_ID_VOUCHER_PAGO,
                                            null,
                                            L_ID_AJUSTE,
                                            L_AGRUPA
                                    );

                            ELSIF L_IMPORTE_PAGO_TCC_DIF < 0 AND L_ID_INDICADOR = 'VARIACION_CAMBIARIA_ACTIVO' THEN
                                    INSERT INTO CONTA_ASIENTO (
                                            ID_TIPOORIGEN,
                                            ID_ORIGEN, 
                                            FONDO,
                                            DEPTO,
                                            CUENTA, 
                                            CUENTA_CTE,
                                            RESTRICCION,
                                            IMPORTE,
                                            DESCRIPCION,
                                            MEMO,
                                            VOUCHER, 
                                            PARENT_ID,
                                            REF_ID,
                                            AGRUPA
                                    )VALUES ( 
                                            L_ID_TIPOORIGEN_AJUSTE,
                                            L_ID_AJUSTE,
                                            L_ID_FONDO,
                                            L_DEPTO,
                                            L_ID_CUENTAAASI,
                                            L_CUENTA_CTE,
                                            L_ID_RESTRICCION,
                                            L_IMPORTE,
                                            -- 'VARIACION CAMBIARIA DEL ACTIVO TC',
                                            SUBSTR((L_ID_ENTIDAD_PAGO || '-' || L_CORRELATIVO_COMPRA || ' ' || L_NUMERO_AJUSTE || '-' ||TO_CHAR(L_FECHA_AJUSTE, 'DD/MM/YYYY') || '-' || 'VAR-CAMB-ACTIVO-TC'),1,50),
                                            L_ID_AJUSTE,
                                            L_ID_VOUCHER_PAGO,
                                            null,
                                            L_ID_AJUSTE,
                                            L_AGRUPA
                                    );
                            END IF;

                            FETCH casi INTO L_ID_ASIENTO, L_ID_PARENT, L_ID_TIPO_PLAN, L_ID_RESTRICCION,
                                    L_ID_CUENTAAASI,L_DC, L_DESTINO, L_ID_INDICADOR,L_UNICO,L_UNICOCTACTE,
                                    L_PORCENTAJE,L_DESCRIPCION,L_AGRUPA, L_ID_FONDO;
                            END LOOP;
                        CLOSE casi; 
                    END IF;
               END IF;
           END IF;
        END IF;

        P_ERROR:=l_error;
        P_MSGERROR:=l_msgerror;
    END TEMP_SP_VALIDAR_AJUSTE_PAGO_C;

