-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = enoc,pkg_assistance,public;




CREATE OR REPLACE PROCEDURE enoc.pkg_assistance_sp_control_asistencia (P_ID_ENTIDAD bigint,P_ID_DEPTO text,P_ID_ANHO bigint,P_ID_MES bigint,P_ID_PERSONA bigint,P_ID_USER_REG bigint,P_ERROR OUT bigint,P_MSGERROR out text) AS $body$
DECLARE

        l_contar bigint;
        l_error bigint:=0;
        l_msgerror varchar(200):='';

BEGIN
        
         --vacaciones
        CALL pkg_benefits_sp_control_vacacion(P_ID_ENTIDAD,P_ID_DEPTO,P_ID_ANHO,P_ID_MES,P_ID_PERSONA,P_ID_USER_REG,l_error,l_msgerror);
        if l_error<>0 then
--           GOTO SALIDA;
        end if;
        --permiso licencia/permiso especial
        CALL pkg_benefits_sp_control_permiso_lic(P_ID_ENTIDAD,P_ID_DEPTO,P_ID_ANHO,P_ID_MES,P_ID_PERSONA,P_ID_USER_REG,l_error,l_msgerror);
        if l_error<>0 then
--           GOTO SALIDA;
        end if;
        --generar faltas automaticas
         CALL pkg_assistance_sp_control_generar_falta(P_ID_ENTIDAD,P_ID_DEPTO,P_ID_ANHO,P_ID_MES,P_ID_PERSONA,P_ID_USER_REG,l_error,l_msgerror);
          if l_error<>0 then
--             GOTO SALIDA;
          end if;
        --asistencia
        CALL pkg_assistance_sp_control_laboral(P_ID_ENTIDAD,P_ID_DEPTO,P_ID_ANHO,P_ID_MES,P_ID_PERSONA,P_ID_USER_REG,l_error,l_msgerror);
        if l_error<>0 then
--           GOTO SALIDA;
        end if;
        --generar sobretiempo
        CALL pkg_assistance_sp_control_sobretiempo(P_ID_ENTIDAD,P_ID_DEPTO,P_ID_ANHO,P_ID_MES,P_ID_PERSONA,P_ID_USER_REG,l_error,l_msgerror);
        if l_error<>0 then
--           GOTO SALIDA;
        end if;

        --generar tardanza
        CALL pkg_assistance_sp_control_generar_tardanza(P_ID_ENTIDAD,P_ID_DEPTO,P_ID_ANHO,P_ID_MES,P_ID_PERSONA,P_ID_USER_REG,l_error,l_msgerror);
        if l_error<>0 then
--           GOTO SALIDA;
        end if;
--         <<SALIDA>>

        P_ERROR:=l_error;
        P_MSGERROR:= l_msgerror;

      END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE enoc.pkg_assistance_sp_control_asistencia (P_ID_ENTIDAD bigint,P_ID_DEPTO text,P_ID_ANHO bigint,P_ID_MES bigint,P_ID_PERSONA bigint,P_ID_USER_REG bigint,P_ERROR OUT bigint,P_MSGERROR out text) FROM PUBLIC;
