-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = moises,public;
\set ON_ERROR_STOP ON

procedure eliminar_duplicados_simples(v_persona_1 integer,v_persona_2 integer) AS
begin
  update eliseo.compra set Id_Proveedor=v_persona_1 where Id_Proveedor=v_persona_2;commit;
  update eliseo.caja_pago_compra set Id_Proveedor=v_persona_1 where Id_Proveedor=v_persona_2;commit;
  update ELISEO.Compra_Suspencion set Id_Proveedor=v_persona_1 where Id_Proveedor=v_persona_2;commit;
  update ELISEO.venta set Id_cliente=v_persona_1 where Id_cliente=v_persona_2;commit;
  update ELISEO.venta set id_cliente_legal=v_persona_1 where id_cliente_legal=v_persona_2;commit;
  update ELISEO.venta_saldo set Id_cliente=v_persona_1 where Id_cliente=v_persona_2;commit;
  update ELISEO.Caja_Deposito set Id_cliente=v_persona_1 where Id_cliente=v_persona_2;commit;
  update moises.persona_documento set Id_Persona=v_persona_1 where Id_Persona=v_persona_2;commit;
  update moises.persona_direccion set Id_Persona=v_persona_1 where Id_Persona=v_persona_2;commit;
  update moises.persona_telefono set Id_Persona=v_persona_1 where Id_Persona=v_persona_2;commit;
  update moises.persona_natural_idioma set Id_Persona=v_persona_1 where Id_Persona=v_persona_2;commit;
  update moises.persona_virtual set Id_Persona=v_persona_1 where Id_Persona=v_persona_2;commit;
  update jose.school_persona_religion set id_persona=v_persona_1 where id_persona=v_persona_2;commit;
    update jose.school_persona_vivienda set id_persona=v_persona_1 where id_persona=v_persona_2;commit;
    update jose.school_persona_parentesco set id_persona=v_persona_1 where id_persona=v_persona_2;commit;
    update jose.school_persona_laboral set id_persona=v_persona_1 where id_persona=v_persona_2;commit;
    update jose.school_persona_familia set id_persona=v_persona_1 where id_persona=v_persona_2;commit;
    update jose.school_dato_adicional set id_hijo_hija=v_persona_1 where id_hijo_hija=v_persona_2;commit;
    update jose.school_dato_adicional set id_pmo=v_persona_1 where id_pmo=v_persona_2;commit;
    update jose.school_matricula set id_resp_financiero=v_persona_1 where id_resp_financiero=v_persona_2;commit;
    update jose.school_reserva set id_resp_financiero=v_persona_1 where id_resp_financiero=v_persona_2;commit;
    update jose.school_persona_admision set id_persona=v_persona_1 where id_persona=v_persona_2;commit;
    update jose.school_persona_admision set id_resp_financiero=v_persona_1 where id_resp_financiero=v_persona_2;commit;
  delete moises.persona_natural where  Id_Persona=v_persona_2;commit;
  commit;
end;

