-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = moises,public;
\set ON_ERROR_STOP ON

PROCEDURE        IUDP_PERSON_NATUR_PARENT_MULT(
P_Modo int,PN_NUM_DOCUMENTO varchar2, P_NUM_DOCUMENTO varchar2,
P_ID_TIPODOCUMENTO int, P_ID_TIPOPARENTESCO int,
P_NOMBRE varchar2, P_PATERNO varchar2, P_MATERNO varchar2, 
P_ID_ESTADOCIVIL int,
P_COD_PAIS int, P_SEXO VARCHAR2, P_FEC_NACIMIENTO varchar2,
P_EMAIL varchar2 DEFAULT NULL,
P_FIJO varchar2 DEFAULT NULL,
P_CELULAR varchar2 DEFAULT NULL,
P_RESIDENCIA varchar2 DEFAULT NULL,
P_NUM_CUSPP varchar2 DEFAULT NULL
)
AS

S_PN_NUM_DOCUMENTO VARCHAR2(100);
S_PN_ID_PERSONA int DEFAULT 0;  
S_PR_ID_PERSONA int; 
BEGIN
  IF P_Modo = 0 THEN
  S_PN_NUM_DOCUMENTO := NULLIF(TRIM(PN_NUM_DOCUMENTO),'');
  SELECT nvl (
				(SELECT  
					      NVL(moises.Persona.ID_PERSONA, 0)
					    FROM moises.PERSONA
					    LEFT JOIN moises.Persona_Natural ON
					      Persona.ID_PERSONA = Persona_Natural.ID_PERSONA
					    LEFT JOIN moises.Persona_Documento ON
					      Persona.ID_PERSONA = Persona_Documento.ID_PERSONA
					    WHERE moises.Persona_Documento.NUM_DOCUMENTO = S_PN_NUM_DOCUMENTO)
				,0) INTO S_PN_ID_PERSONA FROM dual;
  	S_PR_ID_PERSONA := 0;
    IF S_PN_ID_PERSONA IS NOT NULL AND S_PN_ID_PERSONA != 0 THEN
        iudp_Persona_Natural (0, P_NUM_DOCUMENTO, P_ID_TIPODOCUMENTO, P_NOMBRE, P_PATERNO, P_MATERNO, P_ID_ESTADOCIVIL, NULL, P_COD_PAIS, P_COD_PAIS, NULL, P_SEXO, P_FEC_NACIMIENTO, NULL, S_PR_ID_PERSONA);
        iudp_Persona_Virtual (0, S_PR_ID_PERSONA, 0, 1, P_EMAIL, NULL);
        iudp_Persona_Telefono (0, S_PR_ID_PERSONA, 0, 1, P_FIJO, 0, 0, NULL);
        iudp_Persona_Telefono (0, S_PR_ID_PERSONA, 0, 5, P_CELULAR, 0, 0, NULL);
        iudp_Persona_Telefono (0, S_PR_ID_PERSONA, 0, 9, P_RESIDENCIA, 0, 0, NULL);
		iudp_Persona_Documento (0, S_PR_ID_PERSONA, 98, P_NUM_CUSPP);
        iudp_Persona_Natural_Parent (0,S_PN_ID_PERSONA, S_PR_ID_PERSONA, P_ID_TIPOPARENTESCO, NULL);
    END IF;
  END IF;
END;

