-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_persona_comun (id_persona, nombre_tipo_documento, tipo_doc, num_documento, paterno, materno, nombre, apellido_nombre, nombre_apellido, celular, telefono, correo, correo_upeu, fec_nacimiento, sexo, id_sexo, discapacidad, codigo_sexo, codigo_religion, pais, id_tipopais, religion, estado_civil, id_tipodireccion, direccion, id_ubigeo, foto) AS select p.id_persona,td.Nombre nombre_tipo_documento,td.Siglas tipo_doc,pn.Num_Documento,
p.paterno,p.materno,p.nombre , p.paterno||' '||p.materno||' '||p.nombre apellido_nombre,
p.nombre||' '||p.paterno||' '||p.materno nombre_apellido,pn.celular,pn.TELEFONO,pn.correo,pn.Correo_Inst correo_upeu,
pn.Fec_Nacimiento,Ts.Nombre sexo, pn.sexo id_sexo, nvl(tdc.Nombre,'Ninguna') discapacidad,
Ts.Codigo codigo_sexo,tr.Codigo codigo_religion,
Tp.Nombre pais, pn.Id_Tipopais,nvl(tr.Nombre,'Otro') religion,Tec.Nombre estado_civil,
pd.Id_Tipodireccion,pd.Direccion,pd.Id_Ubigeo,pn.foto
FROM moises.persona p inner join moises.persona_natural pn on pn.id_persona=p.id_persona
left join moises.tipo_sexo ts on ts.sexo=pn.sexo
left join moises.tipo_documento td on td.Id_Tipodocumento=pn.Id_Tipodocumento
left join moises.tipo_pais tp on Tp.Id_Tipopais=pn.Id_Tipopais
left join moises.tipo_religion tr on tr.Id_Tiporeligion=pn.Id_TipoReligion
left join MOISES.Tipo_Estado_Civil tec on Tec.Id_Tipoestadocivil=pn.Id_Tipoestadocivil
left join MOISES.Tipo_Discapacidad tdc on tdc.Id_Tipo_Discapacidad=pn.Id_Tipo_Discapacidad
left join (select id_persona,pd.Id_Tipodireccion,pd.Direccion,pd.Id_Ubigeo from MOISES.Persona_Direccion pd
            where pd.Id_Direccion=(select max(Id_Direccion) from MOISES.Persona_Direccion b where b.id_persona=pd.id_persona)
           ) pd on pd.id_persona=p.id_persona;

