-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_persona_egresado (anio, semestre, id_sede, sede, id_facultad, nom_facultad, escuela_profesional, id_escuela, nombre_certificado, id_programa_estudio, nombre_escuela, id_persona, nombre_tipo_documento, tipo_doc, num_documento, paterno, materno, nombre, apellido_nombre, nombre_apellido, codigo, celular, correo, correo_upeu, fec_nacimiento, sexo, id_sexo, pais, id_tipopais, religion, estado_civil) AS select pne.Anio,asm.semestre,vpp.id_sede,Vpp.Sede,vpp.id_facultad,Vpp.Nom_Facultad,ape.Escuela_Profesional,
ape.id_escuela,ape.Nombre_Certificado,ape.Id_Programa_Estudio,ape.Nombre_Escuela,
p.id_persona,Td.Nombre nombre_tipo_documento,Td.Siglas tipo_doc,pn.Num_Documento,
p.paterno,p.materno,p.nombre , p.paterno||' '||p.materno||' '||p.nombre apellido_nombre,
p.nombre||' '||p.paterno||' '||p.materno nombre_apellido,pna.codigo,pn.celular,pn.correo,pn.Correo_Inst correo_upeu,
pn.Fec_Nacimiento,ts.Nombre sexo, pn.sexo id_sexo, tp.Nombre pais, pn.Id_Tipopais,nvl(Tr.Nombre,'Otro') religion,tec.Nombre estado_civil
FROM moises.persona p inner join moises.persona_natural pn on pn.id_persona=p.id_persona
inner join moises.persona_natural_alumno pna on pna.id_persona=pn.id_persona
inner join moises.persona_natural_EGRESADO pne on pne.id_persona=pn.id_persona
inner join Vw_Plan_Programa vpp on Vpp.Id_Plan_Programa=pne.Id_Plan_Programa
inner join Vw_Acad_Programa_Estudio ape on ape.Id_Programa_Estudio=Vpp.Id_Programa_Estudio
inner join acad_semestre asm on asm.id_semestre=pne.id_semestre
left join moises.tipo_sexo ts on ts.sexo=pn.sexo
left join moises.tipo_documento td on Td.Id_Tipodocumento=pn.Id_Tipodocumento
left join moises.tipo_pais tp on tp.Id_Tipopais=pn.Id_Tipopais
left join moises.tipo_religion tr on Tr.Id_Tiporeligion=pn.Id_TipoReligion
left join MOISES.Tipo_Estado_Civil tec on tec.Id_Tipoestadocivil=pn.Id_Tipoestadocivil;

