-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = enoc,pkg_desempeno,public;




CREATE OR REPLACE PROCEDURE enoc.pkg_desempeno_sp_generar_participante_grupo (P_ID_DESEMPENO bigint,P_ID_ENTIDAD bigint, P_ID_DEPTO text, P_ID_TIPO_TIEMPO_TRABAJO text,P_ID_CONDICION_LABORAL text,P_ID_USER_REG bigint,P_ERROR OUT bigint, P_MSGERROR out text ) AS $body$
DECLARE

        l_contar bigint;
        l_error bigint:=0;
        l_msgerror varchar(200):='';
        l_id_participante bigint;
        l_fecha_inicio timestamp(0);

        l_query varchar(4000):='';
        l_id_depto varchar(2000):='';
        l_id_tipo_tiempo_trabajo varchar(2000):='';
        l_id_condicion_laboral varchar(2000):='';

BEGIN
      
        delete from enoc.TT_LISTAR_PARAM_PART;

        l_id_depto:=''''||REPLACE(P_ID_DEPTO, '*', ''',''')||'''';
        l_id_tipo_tiempo_trabajo:=REPLACE(P_ID_TIPO_TIEMPO_TRABAJO, '*', ',');
        l_id_condicion_laboral:=''''||REPLACE(P_ID_CONDICION_LABORAL, '*', ''',''')||'''';

    
        l_query:='insert into  enoc.TT_LISTAR_PARAM_PART(ID_CAMPO_NUM,ID_CAMPO_VAR,TIPO) ';
        l_query:=l_query||'select null,id_depto,''D'' from eliseo.conta_entidad_depto where id_depto in('||l_id_depto||') and id_entidad=:p1 ';
        l_query:=l_query||'union select ID_TIPO_TIEMPO_TRABAJO,null,''T'' from moises.TIPO_TIEMPO_TRABAJO where ID_TIPO_TIEMPO_TRABAJO in('||l_id_tipo_tiempo_trabajo||') ';
        l_query:=l_query||'union select null,ID_CONDICION_LABORAL,''C'' from moises.CONDICION_LABORAL where ID_CONDICION_LABORAL in('||l_id_condicion_laboral||') ';

        EXECUTE l_query USING P_ID_ENTIDAD;

        
        
        select FECHA_INICIO into STRICT l_fecha_inicio from enoc.DES_DESEMPENO where ID_DESEMPENO=P_ID_DESEMPENO;
        select coalesce(max(id_participante),0)  into STRICT l_id_participante from enoc.des_participante;

        insert into ENOC.DES_PARTICIPANTE(
          ID_PARTICIPANTE,
          ID_DESEMPENO,
          ID_TRABAJADOR,
          ID_SEDEAREA,
          ID_PERFIL_PUESTO,
          ID_CONDICION_LABORAL,
          ID_TIPO_TIEMPO_TRABAJO,
          ID_ESCALA,
          PUNTAJE,
          CERRADO,
          ID_USER_REG,
          FECHA_REG
        )
        SELECT (row_number() OVER ( ORDER BY x.ID_TRABAJADOR ASC )) + l_id_participante as ID_PARTICIPANTE,
        P_ID_DESEMPENO as ID_DESEMPENO,
        x.ID_TRABAJADOR,
        x.ID_SEDEAREA,
        x.ID_PERFIL_PUESTO,
        x.ID_CONDICION_LABORAL,
        x.ID_TIPO_TIEMPO_TRABAJO,
        null ID_ESCALA,
        0 as PUNTAJE,
        0 as CERRADO,
        P_ID_USER_REG,
        clock_timestamp()
        from (
          SELECT 
          a.ID_TRABAJADOR,
          a.ID_SEDEAREA,
          a.ID_PERFIL_PUESTO,
          a.ID_CONDICION_LABORAL,
          a.ID_TIPO_TIEMPO_TRABAJO
          from moises.trabajador a,enoc.vw_ent_dep_area_ccosto b
          where a.ID_SEDEAREA=b.ID_SEDEAREA
          and a.id_situacion_trabajador='1'
          and a.id_entidad=P_ID_ENTIDAD
          and a.ID_CONDICION_LABORAL in (select ID_CAMPO_VAR from enoc.TT_LISTAR_PARAM_PART where tipo='C' )
          and a.ID_TIPO_TIEMPO_TRABAJO in (select ID_CAMPO_NUM from enoc.TT_LISTAR_PARAM_PART where tipo='T' )
          and b.ID_DEPTO_PADRE in (select ID_CAMPO_VAR from enoc.TT_LISTAR_PARAM_PART where tipo='D' )
          and MOD( FLOOR( MONTHS_BETWEEN( date_trunc('day', l_fecha_inicio ), date_trunc('day', a.fecha_inicio ) ) ), 12 )>=1  --hasta un mes que esta trabajando
          and a.ID_TRABAJADOR not in (
            select ID_TRABAJADOR from enoc.DES_PARTICIPANTE
            where ID_DESEMPENO=P_ID_DESEMPENO
          )
          /*UNION
          select 
          a.ID_TRABAJADOR,
          a.ID_SEDEAREA,
          a.ID_PERFIL_PUESTO,
          a.ID_CONDICION_LABORAL,
          a.ID_TIPO_TIEMPO_TRABAJO
          from moises.trabajador a,enoc.vw_ent_dep_area_ccosto b 
          where a.ID_SEDEAREA=b.ID_SEDEAREA
          and a.id_situacion_trabajador='0' 
          and a.fecha_fin_efectivo is not null
          and a.id_entidad=P_ID_ENTIDAD
          and a.ID_CONDICION_LABORAL in(select ID_CAMPO_VAR from enoc.TT_LISTAR_PARAM_PART where tipo='C' )
          and a.ID_TIPO_TIEMPO_TRABAJO in(select ID_CAMPO_NUM from enoc.TT_LISTAR_PARAM_PART where tipo='T' )
          and b.ID_DEPTO_PADRE in(select ID_CAMPO_VAR from enoc.TT_LISTAR_PARAM_PART where tipo='D' )
          and a.ID_TRABAJADOR not in(
            select ID_TRABAJADOR from enoc.DES_PARTICIPANTE
            where ID_DESEMPENO=P_ID_DESEMPENO
          )
          and MOD ( FLOOR ( MONTHS_BETWEEN ( TRUNC( l_fecha_inicio ), TRUNC ( a.fecha_fin_efectivo ) ) ), 12 )<=1  --hasta un mes de antigüidad
          */
 
                   
        )x;

--         <<salida>>
        P_ERROR:=l_error;
        P_MSGERROR:=l_msgerror;

      END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE enoc.pkg_desempeno_sp_generar_participante_grupo (P_ID_DESEMPENO bigint,P_ID_ENTIDAD bigint, P_ID_DEPTO text, P_ID_TIPO_TIEMPO_TRABAJO text,P_ID_CONDICION_LABORAL text,P_ID_USER_REG bigint,P_ERROR OUT bigint, P_MSGERROR out text ) FROM PUBLIC;
