-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

function ft_calcular_bim_carg_cur(p_id_mes number, p_id_carga_curso_doc integer) 
return number IS

p_bimestre number;

begin

    select (case when p_id_mes >p_bimestre and p_id_mes<=s_bimestre then 2 when p_id_mes>=mes_inicio and p_id_mes<=p_bimestre then 1 else 0 end) into p_bimestre
    from (select to_char(Amd.Fecha_Inicio,'mm') mes_inicio, (to_char(Amd.Fecha_Inicio,'mm')-1) + (to_char(Amd.Fecha_Fin,'mm')-(to_char(Amd.Fecha_Inicio,'mm')-1))/2 p_bimestre,
          to_char(Amd.Fecha_Fin,'mm') s_bimestre
          from Acad_Carga_Curso_Docente accd inner join Acad_Modulo_Detalle amd on Amd.Id_Modulo_Detalle=Accd.Id_Modulo_Detalle
          where Id_Carga_Curso_Docente=p_id_carga_curso_doc);
          
          return p_bimestre;
      
      
end;

