-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

function ft_fin_plan_anio(p_id_persona in integer,p_id_plan_programa in integer, p_anio in integer) 
return varchar2
is
  p_ciclo number;
  res number;
  p_res varchar2(10);
begin  

    select (p_anio*2) into p_ciclo from dual;
  
    select nvl((SELECT count(APCA.ID_PLAN_CURSO)
    FROM ACAD_PLAN_PROGRAMA APP
    INNER JOIN ACAD_PLAN_CURSO APCA ON APCA.ID_PLAN=APP.ID_PLAN AND APP.ID_PLAN_PROGRAMA=p_id_plan_programa
    AND APCA.ID_PLAN_CURSO_ELECTIVO IS NULL AND APCA.CICLO <= p_ciclo 
    WHERE NOT EXISTS (SELECT 1
                FROM ACAD_CURSO_ALUMNO ACA 
                INNER JOIN ACAD_PLAN_CURSO APC ON APC.ID_PLAN_CURSO=ACA.ID_PLAN_CURSO
                WHERE ACA.ID_PERSONA=p_id_persona AND ACA.ID_PLAN_PROGRAMA=p_id_plan_programa 
                AND APC.CICLO <= p_ciclo
                AND ACA.ID_TIPO_CONDICION IN (1,13,17) AND ACA.ESTADO='1'
                AND DECODE(APC.ID_PLAN_CURSO_ELECTIVO,NULL,APC.ID_PLAN_CURSO,APC.ID_PLAN_CURSO_ELECTIVO)=APCA.ID_PLAN_CURSO)),0) into res
    from dual;
    
    if(res=0) then p_res:='S';
    else p_res:='N';
    end if;
    
    
  return p_res;
  
end;

