-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

function ft_new_codigo_acad(v_id_persona number) RETURN VARCHAR2 AS
  p_codigo VARCHAR2(20);
BEGIN
  SELECT SINTILDE(CONCAT(CONCAT(TO_CHAR(sysdate,'YYYY'),SUBSTR(UPPER(conv_char@dbl_noe(REPLACE(CONVERT(SUBSTR(UPPER(PATERNO),1,2),'US7ASCII','WE8ISO8859P1'),'?','X'))),1,2)),TO_CHAR(sysdate,'YYYYMMDDHH24MI')||LPAD(1,2,'0'))) INTO p_codigo
  FROM MOISES.PERSONA
  WHERE ID_PERSONA=v_id_persona;
  RETURN p_codigo;
END;

