-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

FUNCTION             FT_PROGRAMA_ALUMNO_ID(P_ID_PERSONA IN INTEGER) 
RETURN NUMBER
IS
  P_ID_ESCUELA NUMBER;
BEGIN
    
    SELECT Distinct Vpp.Id_Programa_Estudio INTO P_ID_ESCUELA
    FROM DAVID.VW_ALUMNO_PLAN_PROGRAMA VPP 
    WHERE  ID_PERSONA=P_ID_PERSONA
    AND ID_PLAN_PROGRAMA = (SELECT  ID_PLAN_PROGRAMA
                            FROM (SELECT ID_PLAN_PROGRAMA,ID_PERSONA FROM DAVID.VW_ALUMNO_PLAN_PROGRAMA WHERE ESTADO=1 ORDER BY LPAD(decode(ID_NIVEL_ENSENANZA,1,9,2,9,3,9,4,9,1),2,'0')||NOMBRE_PLAN DESC)
                            WHERE ID_PERSONA=VPP.ID_PERSONA AND ROWNUM=1);
                            
                            
    RETURN P_ID_ESCUELA;
END;

