-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

function ft_rsultado_consultas(v_id_persona integer, v_id_plan_programa integer, v_tipo varchar2)
RETURN varchar2 IS
  p_res	  varchar2(2000);		 

BEGIN

  if(v_tipo='CASA') then
  select sum(A.Credito) into p_res 
  from vw_acad_curso_alumno a
  where id_persona=v_id_persona and Id_Plan_Programa=v_id_plan_programa and Id_Tipo_Condicion in (1)
  and id_semestre=(select max(id_semestre) from vw_acad_curso_alumno where id_persona=a.id_persona and Id_Plan_Programa=a.Id_Plan_Programa and Id_Tipo_Condicion in (1,2));
  
  elsif(v_tipo='TCAO') then
  select sum(A.Credito) into p_res
  from vw_acad_curso_alumno a
  inner join Vw_Acad_Curso_Plan acp on Acp.Id_Plan_Curso=A.Id_Plan_Curso and Id_Tipo_Condicion in (1)
  where id_persona=v_id_persona and Id_Plan_Programa=v_id_plan_programa and Acp.Id_Plan_Curso_Electivo is null;
  
  elsif(v_tipo='TCAE') then
  select sum(apce.Credito) into p_res
  from vw_acad_curso_alumno a
  inner join Acad_Plan_Curso acp on Acp.Id_Plan_Curso=A.Id_Plan_Curso and Id_Tipo_Condicion in (1)
  inner join Vw_Acad_Curso_Plan apce on Apce.Id_Plan_Curso=Acp.Id_Plan_Curso_Electivo
  where id_persona=v_id_persona and Id_Plan_Programa=v_id_plan_programa;
  
  elsif(v_tipo='USC') then
  select max(semestre)  into p_res
  from vw_acad_curso_alumno where id_persona=v_id_persona and Id_Plan_Programa=v_id_plan_programa and Id_Tipo_Condicion in (1,2);
  
  elsif(v_tipo='CSM') then
  select count(*) into p_res
  from (select Distinct Aac.Semestre
        from vw_acad_alumno_contrato aac
        inner join Acad_Alumno_Contrato_Curso acc on Acc.Id_Alumno_Contrato=Aac.Id_Alumno_Contrato
        inner join Acad_Curso_Alumno aca on Aca.Id_Curso_Alumno=Acc.Id_Curso_Alumno and Aca.Id_Tipo_Condicion in (1,2)
        where aac.id_persona=v_id_persona and aac.Id_Plan_Programa=v_id_plan_programa and Aac.Id_Modo_Contrato=1);
  end if;
  
  return p_res;
end;

