-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

FUNCTION               ft_verificacion(v_codigo in Varchar2, v_tipo in Varchar2) RETURN VARCHAR2 IS

   p_res  VARCHAR2(200);

begin



  if(v_tipo='1') then



    select 'S' into p_res

    from moises.verificacion where codigo_verificacion=v_codigo AND ROWNUM=1;



  end if;



  if(v_tipo='2') then



    select 'S'||estado into p_res

    from moises.verificacion where valor=v_codigo AND ROWNUM=1;



  end if;



  return p_res;
  
end;

