-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_orders (id_pedido, id_entidad, id_depto, id_anho, id_mes, id_persona, id_tipopedido, id_gasto, id_tipotransaccion, id_actividad, id_areaorigen, id_areadestino, id_areagasto, id_pbancaria, id_tipoactividadeconomica, numero, acuerdo, fecha, fecha_pedido, fecha_entrega, fecha_pago, motivo, estado, comentario, id_almacen_origen, id_almacen_destino, id_dexec, id_task, email, tipo_pedido, nombre_deptoorigen, id_depto_origen, nombre_areaorigen, nombre_deptodestino, id_depto_destino, nombre_areadestino, paso, porcentaje, id_formulario, codigo_formulario, nombre_formulario, id_paso_anterior, id_paso_actual, id_paso_next, id_mapa_iniciativa, id_iniciativa_detalle, serie_numero_venta, codigo_areaorigen, codigo_areadestino, celular) AS SELECT A.ID_PEDIDO,
          A.ID_ENTIDAD,
          A.ID_DEPTO,
          A.ID_ANHO,
          A.ID_MES,
          A.ID_PERSONA,
          A.ID_TIPOPEDIDO,
          A.ID_GASTO,
          A.ID_TIPOTRANSACCION,
          A.ID_ACTIVIDAD,
          A.ID_AREAORIGEN,
          A.ID_AREADESTINO,
          ID_AREAGASTO,
          A.ID_PBANCARIA,
          A.ID_TIPOACTIVIDADECONOMICA,
          A.NUMERO,
          A.ACUERDO,
          A.FECHA,
          A.FECHA_PEDIDO,
          A.FECHA_ENTREGA,
          A.FECHA_PAGO,
          A.MOTIVO,
          A.ESTADO,
          A.COMENTARIO,
          A.ID_ALMACEN_ORIGEN,
          A.ID_ALMACEN_DESTINO,
          A.ID_DEXEC,
          A.ID_TASK,
          B.EMAIL,
          C.NOMBRE AS TIPO_PEDIDO,
          FC_DEPARTAMENTO(D.ID_DEPTO) AS NOMBRE_DEPTOORIGEN,
          D.ID_DEPTO AS ID_DEPTO_ORIGEN,
          PKG_ORDERS.FC_NOMBRE_AREA(A.ID_AREAORIGEN) AS NOMBRE_AREAORIGEN,
          FC_DEPARTAMENTO(E.ID_DEPTO) AS NOMBRE_DEPTODESTINO,
          E.ID_DEPTO AS ID_DEPTO_DESTINO,
          PKG_ORDERS.FC_NOMBRE_AREA(A.ID_AREADESTINO) AS NOMBRE_AREADESTINO,
          PKG_PURCHASES_ORDERS.FC_PASO(A.ID_DEXEC) AS PASO,
          PKG_PURCHASES_ORDERS.FC_PORCENTAJE_PROCESO(A.ID_PEDIDO)
             AS PORCENTAJE,
          A.ID_FORMULARIO,
          F.CODIGO AS CODIGO_FORMULARIO,
          F.NOMBRE AS NOMBRE_FORMULARIO,
          (SELECT MAX(LPF.ID_PASO)
             FROM LAMB_PROCESS_FLUJO LPF
            WHERE     LPF.ID_TASK = A.ID_TASK
                  AND LPF.ID_PASO_NEXT IN (SELECT LPEP.ID_PASO_ACTUAL
                                             FROM LAMB_PROCESS_EXEC_PASO LPEP
                                            WHERE LPEP.ID_DEXEC = A.ID_DEXEC) )
             AS ID_PASO_ANTERIOR,
          (SELECT MAX(X.ID_PASO_ACTUAL)
             FROM LAMB_PROCESS_EXEC_PASO X
            WHERE X.ID_DEXEC = A.ID_DEXEC)
             ID_PASO_ACTUAL,
          (SELECT MAX(X.ID_PASO_NEXT)
             FROM LAMB_PROCESS_EXEC_PASO X
            WHERE X.ID_DEXEC = A.ID_DEXEC)
             ID_PASO_NEXT,
          A.ID_MAPA_INICIATIVA,
          A.ID_INICIATIVA_DETALLE,
          --X.SERIE||'-'||X.NUMERO AS 
          '' AS SERIE_NUMERO_VENTA,
          D.CODIGO AS CODIGO_AREAORIGEN,
          E.CODIGO AS CODIGO_AREADESTINO,
          A.CELULAR
     FROM PEDIDO_REGISTRO A
          JOIN USERS B ON B.ID = A.ID_PERSONA
          JOIN TIPO_PEDIDO C ON C.ID_TIPOPEDIDO = A.ID_TIPOPEDIDO
          LEFT JOIN ORG_SEDE_AREA D ON D.ID_SEDEAREA = A.ID_AREAORIGEN
          LEFT JOIN ORG_SEDE_AREA E ON E.ID_SEDEAREA = A.ID_AREADESTINO
          LEFT JOIN PEDIDO_FORM F ON F.ID_FORMULARIO = A.ID_FORMULARIO

    WHERE (A.NUMERO IS NOT NULL AND A.NUMERO::text <> '') AND A.ID_TIPOPEDIDO BETWEEN 3 AND 6;

COMMENT ON VIEW vw_orders  IS E'VISTA DE PEDIDOS';

