-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_program_plan (id_plan_programa, id_plan, total_creditos, id_facultad, nom_facultad, id_escuela, nom_escuela, escuela_profesional, nombre_plan, id_semestre_plan) AS SELECT
pp.id_plan_programa,pp.id_plan,pp.total_creditos,
ap.id_facultad,ap.nom_facultad,ap.id_escuela,ap.nom_escuela, ap.escuela_profesional,ap.nombre_plan, ap.id_semestre as id_semestre_plan
FROM DAVID.acad_plan_programa pp, DAVID.VW_ACAD_PLAN ap
WHERE pp.id_plan=ap.id_plan;

