-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_caja_school,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_caja_school_sp_crear_deposito_detalle (P_ID_DEPOSITO bigint,P_VENTAS text,P_IMP_VENTAS text,P_ARTICULOS text,P_ID_MONEDA bigint,P_TIPO_CAMBIO bigint,P_ID_DINAMICA bigint,P_ERROR out bigint, P_MSGERROR out text) AS $body$
DECLARE

    l_id_ddetalle bigint;
    l_id_voucher bigint;
    l_contar bigint;
    l_error bigint:=0;
    l_msgerror varchar(200):='';
    l_total decimal(10,2);
    l_importe decimal(10,2);
    l_importe_me decimal(10,2);
    s_ventas tablastring;
    s_importes tablastring;
    s_articulos tablastring;
    l_id_venta bigint;
    l_imp  decimal(10,2);
    l_id_articulo bigint;
    l_importe2 decimal(10,2);

BEGIN

      RAISE NOTICE '------------';
      RAISE NOTICE '%', P_VENTAS;

      select FC_SPLIT(P_VENTAS,'|') into STRICT s_ventas;
      select FC_SPLIT(P_IMP_VENTAS,'|') into STRICT s_importes;
      select FC_SPLIT(P_ARTICULOS,'|') into STRICT s_articulos;
      
      FOR i IN s_ventas.FIRST .. s_ventas.LAST
      LOOP
          select cast(s_ventas(i) as bigint) into STRICT l_id_venta;

          select cast(s_importes(i) as bigint) into STRICT l_imp;

          if coalesce(s_articulos::text, '') = '' then
          l_id_articulo := null;
          else
          select cast(s_articulos(i) as bigint) into STRICT l_id_articulo;
          end if;
          l_importe:=0;

          -- select total into l_total from VENTA where ID_VENTA=l_id_venta;
          
          select sum(total) into STRICT l_total  from (
                SELECT total 
                from VENTA 
                where id_venta = l_id_venta
                and estado = '1'
                
union all
 
                SELECT total
                from VENTA 
                where id_parent = l_id_venta
                and id_comprobante = '08' --Al parecer NO se usa, pero tener en cuenta el id_comprobane por tiponpais
                and estado = '1'
                ) alias1 
;



          select coalesce(sum(IMPORTE),0) into STRICT l_importe from CAJA_DEPOSITO_DETALLE 
          where ID_VENTA=l_id_venta and id_deposito = P_ID_DEPOSITO;

          l_importe2 := l_importe;
          l_importe:=l_importe + l_imp;

          select coalesce(max(ID_DDETALLE),0)+1 into STRICT l_id_ddetalle from CAJA_DEPOSITO_DETALLE;

          /*if l_importe > l_total then
              l_error:=1; --no existe voucher
              l_msgerror:='Depósito Detalle: Importe pago mayor a total venta:'||l_importe2||'----->'||l_imp||' '||l_importe||' '||l_total;
          end if;
          */
         l_importe_me:=0;
         if P_ID_MONEDA=9 then
           l_importe_me:=l_imp;
           l_imp:=l_imp*P_TIPO_CAMBIO;
         end if;

         /* REVISAR
         --Valida si la venta y deposito tiene a misma cuenta contable
         select count(*) into l_contar from VENTA_DETALLE A,CONTA_DINAMICA B, CONTA_DINAMICA_ASIENTO C
         WHERE A.ID_DINAMICA=B.ID_DINAMICA
         AND B.ID_DINAMICA=C.ID_DINAMICA
         AND A.ID_VENTA=ID_VENTA
         and C.ID_INDICADOR='IMPORTE'
         AND C.ID_CUENTAAASI IN(
            select ID_CUENTAAASI from CONTA_DINAMICA_ASIENTO where ID_DINAMICA=P_ID_DINAMICA
         );
         
         if l_contar=0 then
              l_error:=2; --no existe voucher
              l_msgerror:='Depósito Detalle: Cuenta contable del depósito es distinto a la cuenta contable de venta';
         end if;
         */
         
         if l_error=0 then
          insert into CAJA_DEPOSITO_DETALLE(
            ID_DDETALLE,
            ID_DEPOSITO,
            ID_VENTA,
            ID_ARTICULO,
            IMPORTE,
            IMPORTE_ME
          )values (
            l_id_ddetalle,
            P_ID_DEPOSITO,
            l_id_venta,
            l_id_articulo,
            l_imp,
            l_importe_me
          );
        end if;
    END LOOP;
--     <<salida_rapida>>
    P_ERROR:=l_error;
    P_MSGERROR:=l_msgerror;
  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_caja_school_sp_crear_deposito_detalle (P_ID_DEPOSITO bigint,P_VENTAS text,P_IMP_VENTAS text,P_ARTICULOS text,P_ID_MONEDA bigint,P_TIPO_CAMBIO bigint,P_ID_DINAMICA bigint,P_ERROR out bigint, P_MSGERROR out text) FROM PUBLIC;
