-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_sales,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_sales_sp_kardex_venta (P_ID_VENTA bigint) AS $body$
DECLARE

        L_ID_ANHO bigint;
        L_ID_VDETALLE bigint;
        L_ID_TIPOORIGEN bigint :=1;
        L_ID_ALMACEN bigint;
        L_ID_ARTICULO bigint;
        L_CANTIDAD bigint;
        L_COSTO bigint;
        L_IMPORTE bigint;
        L_ID_MODULO bigint :=13; --VENTAS
        L_ID_COMPROBANTE varchar(2);
        L_TIPO varchar(1) := 'S';

        articulos CURSOR FOR	
        SELECT ID_VDETALLE,ID_ALMACEN,ID_ARTICULO,CANTIDAD,PRECIO_ALM,round((CANTIDAD*PRECIO_ALM)::numeric,2)
        FROM VENTA_DETALLE
        WHERE ID_VENTA = P_ID_VENTA
        ORDER BY ID_ARTICULO;
        	

BEGIN   
        SELECT ID_ANHO,ID_COMPROBANTE INTO STRICT L_ID_ANHO, L_ID_COMPROBANTE
        FROM VENTA
        WHERE ID_VENTA = P_ID_VENTA;

        IF L_ID_COMPROBANTE = '07' THEN
            L_TIPO := 'I';
        ELSE
            L_TIPO := 'S';
        END IF;

        OPEN articulos;
          FETCH articulos INTO L_ID_VDETALLE,L_ID_ALMACEN,L_ID_ARTICULO,L_CANTIDAD,L_COSTO,L_IMPORTE;
            WHILE articulos%FOUND LOOP
                CALL pkg_inventories_sp_add_kardex(L_ID_ANHO,L_ID_ALMACEN,L_ID_ARTICULO,L_ID_TIPOORIGEN,L_ID_VDETALLE,L_CANTIDAD,L_COSTO,L_IMPORTE,L_TIPO);
                FETCH articulos INTO L_ID_VDETALLE,L_ID_ALMACEN,L_ID_ARTICULO,L_CANTIDAD,L_COSTO,L_IMPORTE;
            END LOOP;
        CLOSE articulos;

    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_sales_sp_kardex_venta (P_ID_VENTA bigint) FROM PUBLIC;
