-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = enoc,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_plla_param_valor_det_id ON plla_parametros_valor_det CASCADE;
CREATE OR REPLACE FUNCTION enoc.trigger_fct_tr_plla_param_valor_det_id() RETURNS trigger AS $BODY$
BEGIN
	  SELECT nextval('enoc.sq_plla_param_valor_det_id')
	  into STRICT NEW.ID_PARAMETRO_VALOR_D
	;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION enoc.trigger_fct_tr_plla_param_valor_det_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_plla_param_valor_det_id ON plla_parametros_valor_det;
CREATE TRIGGER tr_plla_param_valor_det_id
	BEFORE INSERT ON plla_parametros_valor_det FOR EACH ROW
	EXECUTE PROCEDURE enoc.trigger_fct_tr_plla_param_valor_det_id();

