-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS migrations_id_trg ON migrations CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_migrations_id_trg() RETURNS trigger AS $BODY$
begin
            if :new.id is null then
                select migrations_id_seq.nextval into :new.id from dual;
            end if;
            end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_migrations_id_trg() FROM PUBLIC;

DROP TRIGGER IF EXISTS migrations_id_trg ON migrations;
CREATE TRIGGER migrations_id_trg
	BEFORE INSERT ON migrations FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_migrations_id_trg();

