-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_colp_deposito_asist ON colp_deposito_asist CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_colp_deposito_asist() RETURNS trigger AS $BODY$
BEGIN
  SELECT SQ_COLP_DEPOSITO_ASIST_ID.nextval
  INTO :new.ID_DEPOSITO_ASIST
  FROM dual;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_colp_deposito_asist() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_colp_deposito_asist ON colp_deposito_asist;
CREATE TRIGGER tr_colp_deposito_asist
	BEFORE INSERT ON colp_deposito_asist FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_colp_deposito_asist();

