-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_entideptoctacte_id ON conta_entidad_depto_cta_cte CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_entideptoctacte_id() RETURNS trigger AS $BODY$
BEGIN
	SELECT ELISEO.SQ_ENTIDEPTOCTACTE_ID.nextval
  	into :new.ID_ENTIDEPTOCTACTE
  	from dual;
  
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_entideptoctacte_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_entideptoctacte_id ON conta_entidad_depto_cta_cte;
CREATE TRIGGER tr_entideptoctacte_id
	BEFORE INSERT ON conta_entidad_depto_cta_cte 
 FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_entideptoctacte_id();

