-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_fin_contrato_bk_pk ON fin_contrato_bk CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_fin_contrato_bk_pk() RETURNS trigger AS $BODY$
BEGIN
  SELECT FIN_CONTRATO_BK_SEQ.nextval
  INTO :new.ID_CONTRATO_BK
  FROM dual;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_fin_contrato_bk_pk() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_fin_contrato_bk_pk ON fin_contrato_bk;
CREATE TRIGGER tr_fin_contrato_bk_pk
	BEFORE INSERT ON fin_contrato_bk FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_fin_contrato_bk_pk();

