-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_nro_conciliacion ON caja_conciliacion CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_nro_conciliacion() RETURNS trigger AS $BODY$
DECLARE 
L_NRO_DOC NUMBER;
BEGIN
	SELECT MAX(TO_NUMBER(NUMERO)) INTO L_NRO_DOC FROM ELISEO.CAJA_CONCILIACION 
	WHERE ID_ENTIDAD = :new.ID_ENTIDAD AND ID_DEPTO = :new.ID_DEPTO; 
	SELECT COALESCE(L_NRO_DOC,0)+1
  	INTO :new.NUMERO
  	FROM dual;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_nro_conciliacion() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_nro_conciliacion ON caja_conciliacion;
CREATE TRIGGER tr_nro_conciliacion
	BEFORE INSERT ON caja_conciliacion 
 FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_nro_conciliacion();

