-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_process_componente_id ON process_componente CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_process_componente_id() RETURNS trigger AS $BODY$
DECLARE 
CONTADOR INT;
BEGIN
SELECT NVL(MAX(ID_COMPONENTE),0)+1 INTO CONTADOR 
FROM PROCESS_COMPONENTE;

:NEW.ID_COMPONENTE:=CONTADOR;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_process_componente_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_process_componente_id ON process_componente;
CREATE TRIGGER tr_process_componente_id
	BEFORE INSERT ON process_componente 
 FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_process_componente_id();

