-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_tipo_archivo ON tipo_archivo CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_tipo_archivo() RETURNS trigger AS $BODY$
BEGIN
 IF :new.ID_TIPOARCHIVO is null THEN
	  SELECT SQ_TIPO_ARCHIVO_ID.nextval
	  INTO :new.ID_TIPOARCHIVO
	  FROM dual;
 END IF;
  
 IF :new.CODIGO is null THEN
	  SELECT LPAD(SQ_TIPO_ARCHIVO_CODIGO.nextval,6,0)
	  INTO :new.CODIGO
	  FROM dual;
 END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_tipo_archivo() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_tipo_archivo ON tipo_archivo;
CREATE TRIGGER tr_tipo_archivo
	BEFORE INSERT ON tipo_archivo FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_tipo_archivo();

