-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,utils,public;




CREATE OR REPLACE FUNCTION eliseo.utils_convert_to_clob (P_EXPR TS , P_PRECISION bigint DEFAULT NULL, P_SCALE bigint DEFAULT 0, P_STYLE bigint DEFAULT NULL) RETURNS text AS $body$
DECLARE

   v_format varchar(50);

BEGIN
   RETURN utils_convert_to_clob_(P_EXPR,P_PRECISION,P_SCALE,P_STYLE);
END;


-- commented out for now as it returns null
--FUNCTION utils_convert_to_char(P_EXPR IN BLOB, P_PRECISION IN numeric DEFAULT 0   , P_SCALE IN numeric DEFAULT 0   , P_STYLE IN numeric DEFAULT 0) RETURN CHAR
--IS
--BEGIN
--     RETURN utils_substr_(utils_convert_to_varchar2(P_EXPR, P_PRECISION, P_SCALE, P_STYLE), P_PRECISION);
--END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.utils_convert_to_clob (P_EXPR TS , P_PRECISION bigint DEFAULT NULL, P_SCALE bigint DEFAULT 0, P_STYLE bigint DEFAULT NULL) FROM PUBLIC;
