-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_sales_facturacion_desis,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_sales_facturacion_desis_sp_venta_electronica_desis (P_ID_VENTA bigint) AS $body$
DECLARE

        L_ID_ENTIDAD bigint;
        L_ID_DEPTO varchar(11);
        L_RUC varchar(11);
        L_ID_COMPROBANTE varchar(3);
        L_SERIE varchar(4);
        L_NUMERO varchar(8);
        L_XML xml;
        L_EMISOR_ID bigint:=1; --EMPRESA CON RUC UPeU
        L_HASH varchar(50);
        L_ORIGENID bigint := 0;
        L_TIPOEMISORID varchar(20);
        L_TIPODTE bigint;
       	L_COUNT bigint;


BEGIN  


        select coalesce(max(origenid),0) into STRICT L_ORIGENID from eliseo.VENTA_ELECTRONICA_DESIS ved
        where origenid = P_ID_VENTA;

        IF L_ORIGENID = 0 THEN
        --IF 7 = 7 THEN 
            SELECT 
                    A.ID_ENTIDAD,A.ID_DEPTO, B.COD_ELECTRONICO ,A.SERIE,A.NUMERO INTO STRICT L_ID_ENTIDAD,L_ID_DEPTO,L_ID_COMPROBANTE,L_SERIE,L_NUMERO
            FROM VENTA A
	  		INNER JOIN ELISEO.TIPO_COMPROBANTE B ON A.ID_COMPROBANTE = B.ID_COMPROBANTE
            WHERE A.ID_VENTA = P_ID_VENTA;

            SELECT B.ID_RUC, EMISORID, TIPOEMISORID INTO STRICT L_RUC, L_EMISOR_ID, L_TIPOEMISORID
            FROM CONTA_ENTIDAD A, CONTA_EMPRESA B
            WHERE A.ID_EMPRESA = B.ID_EMPRESA
            AND A.ID_ENTIDAD = L_ID_ENTIDAD;

            IF L_ID_COMPROBANTE IN ('39','41','33','34') THEN
                SELECT pkg_sales_facturacion_desis_fc_venta(P_ID_VENTA) INTO STRICT L_XML;
            END IF;
            IF L_ID_COMPROBANTE = '61' THEN
                SELECT pkg_sales_facturacion_desis_fc_nota_credito(P_ID_VENTA) INTO STRICT L_XML;
            END IF;
            --IF L_ID_COMPROBANTE = '08' THEN 
                --SELECT PKG_SALES_FACTURACION_DESIS.FC_NOTA_DEBITO(P_ID_VENTA) INTO L_XML FROM DUAL;
            --END IF;
            --FACTURACION ELECTRONICA LAMB
            IF L_TIPOEMISORID = 'DESIS' THEN

            	SELECT COUNT(1) INTO STRICT L_COUNT FROM ELISEO.VENTA_ELECTRONICA_DESIS
            	WHERE ORIGENID = P_ID_VENTA AND TIPODTE=L_ID_COMPROBANTE AND FOLIO=L_NUMERO;
            	IF L_COUNT>0 THEN
            		UPDATE ELISEO.VENTA_ELECTRONICA_DESIS SET 
            		EMISORID=L_EMISOR_ID,COMPROBANTE=L_XML
            		WHERE ORIGENID = P_ID_VENTA AND TIPODTE=L_ID_COMPROBANTE AND FOLIO=L_NUMERO;
            	ELSE
		             INSERT INTO VENTA_ELECTRONICA_DESIS(EMISORID,ORIGENID,FECHA,TIPODTE,FOLIO,COMPROBANTE, PROCESADO, ENVIADO,ESTADO)
		             VALUES (L_EMISOR_ID,P_ID_VENTA,clock_timestamp(),L_ID_COMPROBANTE,L_NUMERO,L_XML, 0, 0,1);
	            END IF;

            END IF;

        END IF;


    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_sales_facturacion_desis_sp_venta_electronica_desis (P_ID_VENTA bigint) FROM PUBLIC;
