-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_natural_person (id_persona, nombre, paterno, materno, codigo, unapellido, id_tipotratamiento, id_tipoestadocivil, id_tiposangre, id_situacion_educativo, id_tipopais, id_ubigeo, id_tiporeligion, id_tipoautoridadiglesia, id_tipodocumento, num_documento, sexo, fec_nacimiento, fec_defuncion, vive, fec_caducidad, telefono, celular, correo, correo_inst, iglesia, fecha_bautizo, tiene_cargo, cargo_iglesia, nombre_autoridad, tlf_autoridad, id_nacionalidad, id_departamento, documento_url, id_provincia, id_distrito, foto, firma, es_docente, cv_url, p_personal, p_familiar, p_academico, p_laboral, apellidonombre, nombreapellido, apellidos, id_tipo_discapacidad, v_seleccion, id_tipoactividadeconomica, fecha_salida) AS SELECT
P.ID_PERSONA,
P.NOMBRE,
P.PATERNO,
P.MATERNO,
P.CODIGO,
P.UNAPELLIDO,
PN.ID_TIPOTRATAMIENTO,
PN.ID_TIPOESTADOCIVIL,
PN.ID_TIPOSANGRE,
PN.ID_SITUACION_EDUCATIVO,
PN.ID_TIPOPAIS,
PN.ID_UBIGEO,
PN.ID_TIPORELIGION,
PN.ID_TIPOAUTORIDADIGLESIA,
PN.ID_TIPODOCUMENTO,
PN.NUM_DOCUMENTO,
PN.SEXO,
PN.FEC_NACIMIENTO,
PN.FEC_DEFUNCION,
PN.VIVE,
PN.FEC_CADUCIDAD,
PN.TELEFONO,
PN.CELULAR,
PN.CORREO,
PN.CORREO_INST,
PN.IGLESIA,
PN.FECHA_BAUTIZO,
PN.TIENE_CARGO,
PN.CARGO_IGLESIA,
PN.NOMBRE_AUTORIDAD,
PN.TLF_AUTORIDAD,
PN.ID_NACIONALIDAD,
PN.ID_DEPARTAMENTO,
PN.DOCUMENTO_URL,
PN.ID_PROVINCIA,
PN.ID_DISTRITO,
PN.FOTO,
PN.FIRMA,
PN.ES_DOCENTE,
PN.CV_URL,
PN.p_personal,
PN.p_familiar,
PN.p_academico,
PN.p_laboral,
P.PATERNO ||' '|| P.MATERNO ||' '||P.NOMBRE AS APELLIDONOMBRE,
P.NOMBRE ||' '|| P.PATERNO ||' '||P.MATERNO AS NOMBREAPELLIDO,
P.PATERNO ||' '|| P.MATERNO AS APELLIDOS,
PN.ID_TIPO_DISCAPACIDAD,
PN.V_SELECCION,
PN.ID_TIPOACTIVIDADECONOMICA,
PN.FECHA_SALIDA
FROM MOISES.PERSONA P
INNER JOIN MOISES.PERSONA_NATURAL PN ON
  PN.ID_PERSONA = P.ID_PERSONA;

