-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_area_por_plan (p_id_plan integer) RETURNS bigint AS $body$
DECLARE


  p_id_area bigint;



BEGIN


 SELECT  id_area INTO STRICT p_id_area
FROM acad_plan WHERE id_plan =p_id_plan;
  return p_id_area;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_area_por_plan (p_id_plan integer) FROM PUBLIC;

