-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_credito_sem_alum_modo (v_id_persona integer, v_id_plan_programa integer, v_id_semestre integer, V_ID_CURSO_MODO integer, V_ESTADO text) RETURNS bigint AS $body$
DECLARE

  p_creditos	  bigint;		


BEGIN
	
	select sum(credito) into STRICT p_creditoS
  from vw_acad_curso_alumno 
  where id_persona=v_id_persona 
  and id_plan_programa=v_id_plan_programa 
  and id_semestre=v_id_semestre and id_tipo_condicion<>3 
  AND ID_CURSO_MODO=V_ID_CURSO_MODO
  and estado<>'4';

RETURN p_creditos;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_credito_sem_alum_modo (v_id_persona integer, v_id_plan_programa integer, v_id_semestre integer, V_ID_CURSO_MODO integer, V_ESTADO text) FROM PUBLIC;

