-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_fecha_cambio_escuela (p_id_persona integer,p_id_plan_programa integer) RETURNS timestamp(0) AS $body$
DECLARE


p_fecha timestamp(0);


BEGIN

  select fecha_registro into STRICT p_fecha
  from (
        SELECT fecha_registro from Acad_Alumno_Contrato where id_persona=p_id_persona and id_plan_programa<>p_id_plan_programa
        order by Fecha_Registro) alias0 LIMIT 1;

  return p_fecha;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_fecha_cambio_escuela (p_id_persona integer,p_id_plan_programa integer) FROM PUBLIC;

