-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_intervalo_notas (p_nota bigint) RETURNS varchar AS $body$
DECLARE

  v_res varchar(20);

BEGIN
  
    select (case when nota<10 then '<10' 
                  when nota Between 10 and 12 then '10_12' 
                  when nota Between 13 and 14 then '13_14' 
                  when nota Between 15 and 16 then '15_16' 
                  when nota >16 then '>16' end ) into STRICT v_res
    from (SELECT p_nota nota ) alias1;

    return v_res;
  end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_intervalo_notas (p_nota bigint) FROM PUBLIC;

