-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_id_persona_alumno ( v_codigo text) RETURNS integer AS $body$
DECLARE

	p_id	  integer;
		

BEGIN

	select max(id_persona) into STRICT p_id
  from moises.persona_natural_alumno
  where codigo =v_codigo;

return p_id;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_id_persona_alumno ( v_codigo text) FROM PUBLIC;

