-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_num_horas_cruce_curso_det ( p_id_carga_curso_docente integer,p_id_semestre integer, p_id_programa_estudio integer, p_ciclo integer, p_grupo text) RETURNS varchar AS $body$
DECLARE

   horario_t varchar(4000);
   horario_b varchar(4000);
   horario_f varchar(4000);
   horas numeric(30);
   curso_cruce varchar(4000);
   cursocruce varchar(4000);
   cursos_cruce varchar(4000);
   letra varchar(1);

   curso CURSOR FOR     
    SELECT aca.Nombre_Curso||' - '||Th.Nombre curso,
    coalesce(Accd.Horario,'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000') horario_t 
    from vw_acad_carga_academica aca inner join acad_carga_curso_docente accd on Accd.Id_Carga_Curso=Aca.Id_Carga_Curso
    inner join Tipo_Horario th on Th.Id_Tipo_Horario=Accd.Id_Tipo_Horario
    where aca.id_semestre=p_id_semestre and Aca.Id_Programa_Estudio=p_id_programa_estudio 
    and Accd.Id_Carga_Curso_docente<>p_id_carga_curso_docente
    and aca.ciclo=p_ciclo and (coalesce(aca.grupo::text, '') = '' or coalesce(aca.grupo,'999')=coalesce(p_grupo,'999'));
BEGIN

    select wm_concat(coalesce(Accd.Horario,'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000')) into STRICT horario_f
          from vw_acad_carga_academica aca inner join acad_carga_curso_docente accd on Accd.Id_Carga_Curso=Aca.Id_Carga_Curso and aca.origen='O' and Accd.Id_Carga_Curso_docente=p_id_carga_curso_docente;

	 horas := 0;
   curso_cruce :='';

	 FOR curCab in curso LOOP
	 	   for i in 1..134 loop

			   if ( substr(curCab.horario_t,i,1) = '1') and ( substr(horario_f,i,1) = '1') then
            if (curso_cruce=curCab.curso) then
              cursocruce :='';
            else
              curso_cruce :=curCab.curso;
              cursocruce :=','||curCab.curso;
            end if;
            cursos_cruce := cursos_cruce||cursocruce;
			   	  horas := horas + 1;
			   end if;

		   end loop;

	 end loop;

	 RETURN( cursos_cruce );
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_num_horas_cruce_curso_det ( p_id_carga_curso_docente integer,p_id_semestre integer, p_id_programa_estudio integer, p_ciclo integer, p_grupo text) FROM PUBLIC;

