-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_profesor_principal (v_id_carga_curso integer) RETURNS varchar AS $body$
DECLARE


	p_nombre	  varchar(2000);

	

BEGIN

	select p.paterno||' '||p.materno||' '||p.nombre into STRICT p_nombre
	    FROM ACAD_CARGA_CURSO_DOCENTE ccd INNER JOIN
	    MOISES.Persona p ON p.ID_PERSONA =ccd.ID_PERSONA  
    WHERE ccd.ID_CARGA_CURSO = v_id_carga_curso AND ccd.ID_TIPO_DOCENTE =1  LIMIT 1;


return p_nombre;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_profesor_principal (v_id_carga_curso integer) FROM PUBLIC;

