-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_ponderado_general (p_id_persona integer,p_id_semestre integer,p_id_programa_estudio integer) RETURNS bigint AS $body$
DECLARE

  p_promedio bigint;

BEGIN

  select round((sum(coalesce(aca.Promedio,0)*acd.Credito)/CASE WHEN sum(acd.Credito)=0 THEN 1  ELSE sum(acd.Credito) END )::numeric,2) into STRICT p_promedio
  from Acad_Curso_Alumno aca inner join Vw_Plan_Programa vpp on Vpp.Id_Plan_Programa=Aca.Id_Plan_Programa
  inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Aca.Id_Curso_Detalle
  where aca.id_persona=p_id_persona
  and Vpp.Id_Programa_Estudio=p_id_programa_estudio
  and aca.estado='1' and id_tipo_condicion in ('1','2');

  return p_promedio;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_ponderado_general (p_id_persona integer,p_id_semestre integer,p_id_programa_estudio integer) FROM PUBLIC;

