-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_promedio_ant (v_id_persona integer,v_id_escuela integer) RETURNS integer AS $body$
DECLARE


	p_promedio	  integer;
  p_ciclo	  integer;
		

BEGIN


  select coalesce(max(Aac.Ciclo),1) into STRICT p_ciclo
  from Vw_Acad_Alumno_Contrato aac inner join Vw_Acad_Programa_Estudio ape on Ape.Id_Programa_Estudio=aac.id_persona 
  where id_persona=v_id_persona and ape.id_escuela=v_id_escuela and Aac.Id_Modo_Contrato=1 and aac.estado='1';

  if (p_ciclo=1) then
    p_promedio:=20;
  else

    select coalesce((select promedio
                from (select vca.semestre,round(sum(aca.promedio*Acd.Credito)/sum(Acd.Credito)) promedio
                      from acad_curso_alumno aca inner join vw_acad_carga_academica vca on Vca.Id_Carga_Curso=Aca.Id_Carga_Curso and aca.id_persona=v_id_persona
                                                  and substr(vca.semestre,-2) in ('-1','-2') and aca.estado='1'
                      inner join Acad_Plan_Curso apc on Apc.Id_Plan_Curso=Vca.Id_Plan_Curso
                      inner join Vw_Acad_Plan vap on Vap.Id_Plan=apc.id_plan and vap.id_escuela=v_id_escuela
                      inner join acad_curso_detalle acd on Acd.Id_Curso_Detalle=Apc.Id_Curso_Detalle 
                      group by vca.semestre
                      order by vca.semestre desc
                      ) alias5  LIMIT 1),0) into STRICT p_promedio;

  end if;

return p_promedio;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_promedio_ant (v_id_persona integer,v_id_escuela integer) FROM PUBLIC;

