-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.ft_tiempo_completo ( v_id_persona integer, v_id_semestre integer, v_tipo text) RETURNS varchar AS $body$
DECLARE

	p_val	  bigint;		
	p_res	  varchar(2);		

BEGIN

  p_res:='N';

  if (v_tipo in ('M','E','CTC') ) then
    p_res:='S';

  else
  
    select sum(hlab) into STRICT p_val
    from (SELECT accd.id_persona,Accd.Hl*Accd.Factor hlab
          from vw_acad_carga_academica acc inner join eliseo.org_sede os on os.id_sede=acc.id_sede and acc.origen='O' and acc.id_facultad between 7 and 12
          inner join acad_carga_curso_docente accd on Accd.Id_Carga_Curso=Acc.Id_Carga_Curso
          left join acad_persona_contrato apc
              on apc.id_persona=accd.id_persona and apc.id_semestre=acc.id_semestre
          where Acc.Id_Semestre=199
          and accd.id_persona=20311
          and acc.id_escuela not in (674)
          and acc.id_facultad not in (673) 
          
union all

          SELECT pc.id_persona,Apc.Horas_Laborales
          from acad_persona_contrato pc inner join VW_PERSONA_NATURAL_CARGA pnc on pnc.id_persona=pc.id_persona
          inner join acad_persona_comision apc on apc.id_persona_contrato=pc.id_persona_contrato
          inner join acad_semestre asm on asm.id_semestre=pc.id_semestre
          inner join acad_comision_det acd on Acd.Id_Comision_Det=Apc.Id_Comision_Det
          where Pc.Id_Semestre=199
          and pc.id_persona=20311) alias3;

    if (p_val>=40) then
      p_res:='S';
    else
      p_res:='N';
    end if;

  end if;

return p_res;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.ft_tiempo_completo ( v_id_persona integer, v_id_semestre integer, v_tipo text) FROM PUBLIC;

