-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION david.horario_dia_curdoc ( p_id_carga_curso integer, p_dia integer) RETURNS varchar AS $body$
DECLARE


val varchar(100);
hrrio varchar(100);
hrrio_tot varchar(100);
corte bigint;
r1 varchar(100);
resp varchar(100);
hi varchar(100);
hf varchar(100);

v_id_carga_curso_docente bigint;
v_horario varchar(200);
v_id_horario bigint;

v_hora_inicio varchar(200);
v_hora_fin varchar(200);



BEGIN


  select accd.id_carga_curso_docente,accd.horario,asp.id_horario into STRICT v_id_carga_curso_docente,v_horario,v_id_horario
    from acad_carga_curso_docente accd inner join acad_modulo_detalle amd on amd.id_modulo_detalle=accd.id_modulo_detalle
    inner join acad_semestre_programa asp on asp.id_semestre_programa=amd.id_semestre_programa
    where accd.id_carga_curso_docente=p_id_carga_curso;


    hrrio_tot :='';
    corte :=1;

    FOR i IN 1..25 LOOP
        val := SUBSTR(v_horario,corte ,corte+7);
        hrrio := substr(val,p_dia,1);
        corte:=corte+7;
        hrrio_tot := hrrio_tot||hrrio;
        hrrio :='';
    END LOOP;

    resp :='';

    FOR r IN 1..25 LOOP

        r1 :=SUBSTR(hrrio_tot,r ,1);
        if (r1=1) then
            resp := resp||','||(case when r<10 then '0'||r else ''||r end);
        end if;

    END LOOP;

    if (resp='') then resp:='0';end if;

    hi :=(SUBSTR(resp,2,2))::numeric;
    hf :=(SUBSTR(resp,-2))::numeric;

    select hora_inicio into STRICT v_hora_inicio
    from (SELECT row_number() OVER () AS num,a.hora_inicio
            from (select id_tipo_turno,
                    (case when id_tipo_turno=1 and (substr(ahd.hora_inicio,0,2))::numeric >2 then to_char(to_date(ahd.hora_inicio,'hh:mi'),'hh:mi')
                            else (case when (substr(ahd.hora_inicio,0,2))::numeric >=12 then to_char(to_date(ahd.hora_inicio,'hh:mi'),'hh:mi')
                                        else to_char(to_date((substr(ahd.hora_inicio,0,2))::numeric +12||substr(ahd.hora_inicio,-3),'hh24:mi'),'hh24:mi')
                                        end)
                            end) hora_inicio
                from acad_horario ah inner join acad_horario_detalle ahd on ahd.id_horario=ah.id_horario
                where ah.id_horario=v_id_horario
                order by ahd.id_tipo_turno,periodo) a ) alias16
    where num=hi;

    select hora_fin into STRICT v_hora_fin
    from (SELECT row_number() OVER () AS num,a.hora_fin
            from (select id_tipo_turno,
                    (case when id_tipo_turno=1 and (substr(ahd.hora_fin,0,2))::numeric >2 then to_char(to_date(ahd.hora_fin,'hh:mi'),'hh:mi')
                            else (case when (substr(ahd.hora_fin,0,2))::numeric >=12 then to_char(to_date(ahd.hora_fin,'hh:mi'),'hh:mi')
                                        else to_char(to_date((substr(ahd.hora_fin,0,2))::numeric +12||substr(ahd.hora_fin,-3),'hh24:mi'),'hh24:mi')
                                        end)
                            end) hora_fin
                from acad_horario ah inner join acad_horario_detalle ahd on ahd.id_horario=ah.id_horario
                where ah.id_horario=v_id_horario
                order by ahd.id_tipo_turno,periodo) a ) alias16
    where num=hf;



  return v_hora_inicio||'**'||v_hora_fin;

  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION david.horario_dia_curdoc ( p_id_carga_curso integer, p_dia integer) FROM PUBLIC;

