-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_accounting,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_accounting_sp_delete_conta_asiento ( p_id_asiento bigint ) AS $body$
BEGIN
        DELETE FROM conta_asiento
        WHERE
            id_asiento = p_id_asiento;

    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_accounting_sp_delete_conta_asiento ( p_id_asiento bigint ) FROM PUBLIC;
