-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

FUNCTION        FC_ENTIDADES_ASIGNADAS(P_ID in INT) RETURN varchar2 IS
   p_name		  		   varchar2(1000);
   p_dato                  varchar2(255);
   cont                     int;
   cursor datos is
       SELECT 
        A.ID_ENTIDAD||' - '||B.NOMBRE AS NOMBRE
        FROM CONTA_ENTIDAD_USUARIO A, CONTA_ENTIDAD B
        WHERE A.ID_ENTIDAD = B.ID_ENTIDAD
        AND A.ID_PERSONA = P_ID;
BEGIN
	 p_name:='';
	 cont:=0;
	 OPEN datos;
                FETCH datos INTO p_dato;

                WHILE datos%FOUND LOOP
                cont:=cont+1;
                if cont = 1 then
                    p_name :=p_dato;
                else
                    p_name :=p_name||', '||p_dato;
                end if;
                
                FETCH datos INTO p_dato;

                END LOOP;
    CLOSE datos;  
    RETURN(p_name); 
END;

