-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

FUNCTION        FC_OBTENER_PHONO(P_ID_PERSONA NUMBER) RETURN VARCHAR2 IS
    L_PHONO VARCHAR2(50);
		l_contar int:=0;
		l_id_telefono number;
    BEGIN 
		select COUNT(*) INTO l_contar 
		from MOISES.PERSONA_TELEFONO 
		WHERE ID_PERSONA=P_ID_PERSONA 
		and ID_TIPOTELEFONO=5;

		IF l_contar>0 THEN
			IF l_contar = 1 THEN
						SELECT
						NVL(NUM_TELEFONO,'') INTO L_PHONO
						FROM MOISES.PERSONA_TELEFONO
						WHERE ID_PERSONA = P_ID_PERSONA
						AND ID_TIPOTELEFONO = 5;
			ELSE
				select max(id_telefono) into l_id_telefono 
				from MOISES.PERSONA_TELEFONO 
				WHERE ID_PERSONA=P_ID_PERSONA and ID_TIPOTELEFONO=5;

				SELECT
						NVL(NUM_TELEFONO,'') INTO L_PHONO
						FROM MOISES.PERSONA_TELEFONO
						WHERE ID_PERSONA = P_ID_PERSONA
						AND ID_TIPOTELEFONO = 5 AND id_telefono = l_id_telefono;
			END IF;
		END IF;
	RETURN(L_PHONO);
END;

