-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

FUNCTION FC_PSTO_CALC_MODFORLAB(P_VALOR NUMBER)
   RETURN NUMBER IS
   l_incremento NUMBER(10,2):=1;
  l_valor NUMBER(10,2):=0;
BEGIN
   l_valor:=round(P_VALOR,0);
   WHILE l_incremento<10 loop

      EXIT WHEN SUBSTR(to_char(round(l_valor,0)),-1) in('0','5'); 
      
      l_valor:=l_valor + 1;
      l_incremento:=l_incremento + 1;
     
    END LOOP;

   RETURN l_valor;
END;

