-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

FUNCTION FC_SPLIT_1 (
    p_list VARCHAR2,
    f_par  VARCHAR2  
) RETURN tablastring AS  l_datos tablastring;

   -- l_datos tablastring;
    t_datos tablastring := tablastring();
    --f_list      VARCHAR2(32767) := 'AA|BBB|CCCC|DDDDD|EE';
   -- f_par       VARCHAR2(32767) := '|';
   f_list VARCHAR2 (32767) := p_list;
    f_sice  NUMBER := nvl(length(regexp_replace(f_list, '[^'  || f_par  || ']')),0);
    o_pos   NUMBER := 0;
    o_vtn   VARCHAR2(32767) := '';
BEGIN
    t_datos.extend(f_sice + 1);
    FOR i IN 0..f_sice LOOP
        o_pos := instr(f_list, f_par);
        o_vtn := substr(f_list, 1, o_pos - 1);
        IF o_pos = 0 THEN
            o_vtn := f_list;
        END IF;
        f_list := substr(f_list, o_pos + 1, length(f_list));
       
        t_datos(i + 1) := '' || o_vtn;
    END LOOP;

    RETURN ( t_datos );
END;

