-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = caleb,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_adm_mensajes_id ON adm_mensajes CASCADE;
CREATE OR REPLACE FUNCTION caleb.trigger_fct_tr_adm_mensajes_id() RETURNS trigger AS $BODY$
begin
			  select CALEB.sq_adm_mensajes_id.nextval
			  into :new.ID_MENSAJE
			  from dual;
			end;
		
		
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION caleb.trigger_fct_tr_adm_mensajes_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_adm_mensajes_id ON adm_mensajes;
CREATE TRIGGER tr_adm_mensajes_id
	BEFORE INSERT ON adm_mensajes FOR EACH ROW
	EXECUTE PROCEDURE caleb.trigger_fct_tr_adm_mensajes_id();

