-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

PROCEDURE        spc_mobile_tra_data_detail_tot (
    p_id_entidad           int,
    p_id_anho           int,
    p_id_ctacte       int,
    cursor       OUT SYS_REFCURSOR
)
IS

    l_ingresos number(38,2);

BEGIN
    DELETE FROM TT_TABLE_AUX;



    OPEN cursor FOR 
    select
                    sum(di.COS_VALOR) AS TOTAL
                from VW_CONTA_DIARIO di
                where di.ID_ENTIDAD = p_id_entidad
                and di.ID_ANHO = p_id_anho
                and di.ID_CUENTAAASI  in (4111022,4111023,4111070,4111071,4111073,4113023,4121029,4113093)
                and di.ID_CTACTE = p_id_ctacte
                and di.ID_DEPTO = 396119
                and di.ID_TIPOASIENTO != 'EA'
        ;

  
END;

