-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

PROCEDURE        spc_profile_worker (
    p_id_persona           int,
    cursor       OUT SYS_REFCURSOR
)
IS
    
    l_ID_ENTIDAD number(38,2);
    l_ID_ANHO number(38,2);
    l_ID_MES number(38,2);
    l_ID_TIPOESTATUS number(38,2);
    l_ID_SISTEMAPENSION number(38,2);
    l_ES_MISIONERO number(38,2);
    l_NOM_CARGO varchar2(50);
    l_FMR number(38,2);
    l_TIPO_STATUS varchar2(100);
    l_SISTEMA_PENSION varchar2(100);
    l_ANHOS_SERVICIO number(38,2);
    l_telefono varchar2(100);
    l_email varchar2(100);
    l_fec_misionero varchar2(100);
    l_sueldo_depositado number(38,2);
    l_doc_number varchar2(50);
    

BEGIN
    select 
    p.ID_ENTIDAD, 
    p.ID_ANHO,
    p.ID_MES,
    p.ID_TIPOESTATUS,
    p.ID_SISTEMAPENSION,
    p.ES_MISIONERO,
    p.NOM_CARGO,
    p.FMR
    INTO 
    l_ID_ENTIDAD,
    l_ID_ANHO,
    l_ID_MES,
    l_ID_TIPOESTATUS,
    l_ID_SISTEMAPENSION,
    l_ES_MISIONERO,
    l_NOM_CARGO,
    l_FMR
    from APS_PLANILLA p
          where p.id_persona = p_id_persona
          and to_date (p.id_anho||lpad(p.id_mes,2,'0'),'yyyymm') = (
          select max(to_date(pp.id_anho||lpad(pp.id_mes,2,'0'),'yyyymm')) from APS_PLANILLA pp
          where pp.id_persona = p_id_persona
          )
    ;
    
    SELECT max(NOMBRE) INTO l_TIPO_STATUS FROM TIPO_ESTATUS
    WHERE ID_TIPOESTATUS = l_ID_TIPOESTATUS;
    
    SELECT NOMBRE INTO l_SISTEMA_PENSION FROM APS_SISTEMA_PENSION
    WHERE ID_SISTEMAPENSION = l_ID_SISTEMAPENSION;
    
    SELECT (SYSDATE - MIN(FEC_INICIO))/ 365.242199 INTO l_ANHOS_SERVICIO FROM APS_EMPLEADO
    WHERE ID_PERSONA = p_id_persona;

    select max(num_telefono) into l_telefono from persona_telefono
          where id_persona = p_id_persona;
          
    SELECT to_char(max(fec_misionero),'dd/mm/yyyy') into l_fec_misionero FROM APS_EMPLEADO
    WHERE ID_PERSONA = p_id_persona
    ;
    
    
    select max(NUM_DOCUMENTO) into l_doc_number from VW_PERSONA_NATURAL
    where ID_PERSONA = p_id_persona
    ;
    
    select max(DIRECCION) into l_email from persona_virtual
          where id_persona = p_id_persona
          and ID_TIPOVIRTUAL = 1;
          
    spc_account_statement_by_id(l_ID_ENTIDAD,l_ID_ANHO,l_ID_MES,p_id_persona,l_doc_number,l_sueldo_depositado);
   
    DBMS_OUTPUT.PUT_LINE('en profile worker');          
    DBMS_OUTPUT.PUT_LINE(l_sueldo_depositado);
    
    OPEN cursor FOR 
    SELECT 
    l_ID_ENTIDAD AS ID_ENTIDAD,
    l_ID_ANHO AS ID_ANHO,
    l_ID_MES AS ID_MES,
    l_telefono as telefono,
    l_email as email,
    l_NOM_CARGO AS NOM_CARGO,
    l_ES_MISIONERO AS ES_MISIONERO,
    l_fec_misionero as fec_misionero,
    l_FMR AS PUNTAJE,
    l_TIPO_STATUS AS TIPO_STATUS,
    l_SISTEMA_PENSION AS SISTEMA_PENSION,
    ROUND(l_ANHOS_SERVICIO) AS ANHOS_SERVICIO,
    l_sueldo_depositado AS SUELDO_DEPOSITADO
    FROM DUAL;
  
END;

