-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

PROCEDURE        spc_sta_salary_desc_cta_total (
    p_id_entidad           int,
    p_id_anho           int,
    p_id_mes           int,
    p_id_ctacte       varchar2,
    p_id_cuentaaasi       varchar2,
    cursor       OUT SYS_REFCURSOR
)
IS

    l_ingresos number(38,2);

l_id_persona NUMBER;

BEGIN
	
	SELECT max(ID_PERSONA) INTO l_id_persona FROM MOISES.PERSONA_DOCUMENTO WHERE NUM_DOCUMENTO =p_id_ctacte;


    OPEN cursor FOR 
    select nvl(sum(COS_VALOR),0) as total from (
   		 select COS_VALOR from VW_CONTA_DIARIO
                where id_entidad = p_id_entidad
                and ID_CUENTAAASI = p_id_cuentaaasi
                and ID_CTACTE = p_id_ctacte
                and ID_MES = p_id_mes
                and ID_ANHO = p_id_anho
                and not ID_TIPOASIENTO = 'RH'
                -- Le estamos agregardo el descuento a la boleta de Ayudas y Viajes(1557, 1558)
                  UNION all
                SELECT 
                COS_VALOR
                FROM VW_APS_PLANILLA A INNER JOIN APS_CONCEPTO_PLANILLA B
                 ON A.ID_CONCEPTOAPS = B.ID_CONCEPTOAPS 
				WHERE A.ID_ENTIDAD = p_id_entidad
				AND A.ID_ANHO = p_id_anho
				AND A.ID_MES = p_id_mes
				AND A.ID_PERSONA = l_id_persona
				AND A.ID_CONCEPTOAPS IN (1557, 1558)
                ) x;
      
  
END;

