-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_inventario_alm_vcanal_id ON inventario_almacen_vcanal CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_inventario_alm_vcanal_id() RETURNS trigger AS $BODY$
BEGIN
  SELECT SQ_INVENTARIO_ALM_VCANAL_ID.nextval
  INTO :new.ID_VENTA_CANAL
  FROM DUAL;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_inventario_alm_vcanal_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_inventario_alm_vcanal_id ON inventario_almacen_vcanal;
CREATE TRIGGER tr_inventario_alm_vcanal_id
	BEFORE INSERT ON inventario_almacen_vcanal FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_inventario_alm_vcanal_id();

