-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_aps_uit ON aps_uit CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_aps_uit() RETURNS trigger AS $BODY$
DECLARE
CONTADOR integer;
BEGIN
	CONTADOR:=0;
	SELECT coalesce(MAX((ID_UIT)::numeric ),0)+1  INTO STRICT CONTADOR    
	FROM APS_UIT;
	NEW.ID_UIT:=CONTADOR;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_aps_uit() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_aps_uit ON aps_uit;
CREATE TRIGGER tr_aps_uit
	BEFORE INSERT ON aps_uit FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_aps_uit();

