-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = jairo,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_sv_ini_process_exec_data (id_iniciativa_detalle, id_paso_actual) AS SELECT
    smid.ID_INICIATIVA_DETALLE,
    lpe.ID_PASO_ACTUAL
FROM
    JAIRO.SGE_MAPA_INICIATIVA_DETALLE smid
JOIN
    ELISEO.LAMB_PROCESS_EXEC_PASO lpep ON smid.ID_DEXEC = lpep.ID_DEXEC
JOIN
    ELISEO.LAMB_PROCESS_EXECUTE lpe ON lpep.ID_EXECUTE = lpe.ID_EXECUTE;

