-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = enoc,pkg_contract,public;




CREATE OR REPLACE PROCEDURE enoc.pkg_contract_sp_gen_contrato_trabajador (P_ID_CONTRATO bigint,P_ID_USER bigint,P_OPC text,P_ERROR OUT bigint,P_MSGERROR out text) AS $body$
DECLARE

        l_contar bigint;
        l_error bigint:=0;
        l_msgerror varchar(200):='';
        l_id_persona bigint;
        l_id_entidad bigint;
        l_id_trabajador bigint;
        l_id bigint;
        l_id_tipo_comision_pens bigint;
        l_id_regimen_pensionaria varchar(5);
        l_fec_inicioafp timestamp(0);
        l_fec_inicioonp timestamp(0);
        l_id_remuneracion bigint;
        l_fecha_ini timestamp(0);
        l_tipo_pago varchar(5);
        l_id_remuneracion_det  bigint;
        l_contrato_mensual bigint;
        l_modo_pago varchar(1);
        l_id_solic_req_candidato bigint;
        l_id_depto varchar(10);
        l_id_anho_proc bigint;
        l_id_mes_proc bigint;
        l_fecha_inic timestamp(0);
        l_fecha_finc timestamp(0);
        l_id_siuacion_trabajador varchar(5);
        l_id_tipo_control_personal bigint;
        l_id_tipo_horario bigint;
        l_id_situacion_especial varchar(5);
        l_ret_asis varchar(200);

        l_id_tipo_control_personal_act bigint;
        l_id_tipo_horario_act bigint;
        l_id_situacion_especial_act varchar(5);
        l_codigo varchar(10);
        l_id_tipo_horario_pf bigint;

BEGIN
      
       select id_persona,id_entidad,FECHA_INI, TIPO_PAGO,COALESCE(contrato_mensual,0),COALESCE(modo_pago,'N'), ID_SOLIC_REQ_CANDIDATO, id_depto
       into STRICT l_id_persona, l_id_entidad,l_fecha_ini,l_tipo_pago,l_contrato_mensual, l_modo_pago,l_id_solic_req_candidato,l_id_depto
       from plla_contrato 
       where id_contrato=P_ID_CONTRATO;

       
       select count(*) into STRICT l_contar from moises.PERSONA_NATURAL_TRABAJADOR where id_persona= l_id_persona;

       if l_contar=0 then
         insert into moises.PERSONA_NATURAL_TRABAJADOR(id_persona) values (l_id_persona);
       end if;

       select count(*) into STRICT l_contar from moises.TRABAJADOR where id_persona= l_id_persona and id_entidad=l_id_entidad;

       if l_contar=0 then
         select coalesce(max(id_trabajador),0)+1 into STRICT l_id_trabajador from moises.TRABAJADOR;
         insert into moises.TRABAJADOR(id_trabajador,id_persona,id_entidad) values (l_id_trabajador,l_id_persona,l_id_entidad);
       else
        select id_trabajador into STRICT l_id_trabajador from moises.TRABAJADOR where id_persona= l_id_persona and id_entidad=l_id_entidad;

       end if;

       if P_OPC='C' or P_OPC='X' then
       
        select coalesce(ID_SITUACION_TRABAJADOR,'0') into STRICT  l_id_siuacion_trabajador from moises.trabajador where id_trabajador=l_id_trabajador;

        if l_id_siuacion_trabajador='1' then
        MERGE INTO MOISES.TRABAJADOR S 
          USING(
           SELECT
              A.ID_CONTRATO,
              A.ID_ENTIDAD,
              A.ID_DEPTO,
              A.ID_PERSONA,
              A.ID_SEDEAREA,
              A.MENOREDAD,
              A.MENOREDAD_URL,
              B.ID_PUESTO,
              B.ID_TIPO_HORARIO,
              A.ID_PERFIL_PUESTO
            FROM PLLA_CONTRATO A , PLLA_PERFIL_PUESTO B
            WHERE A.ID_PERFIL_PUESTO=B.ID_PERFIL_PUESTO
            AND A.ID_CONTRATO=P_ID_CONTRATO
          )T ON (T.ID_PERSONA=S.ID_PERSONA AND T.ID_ENTIDAD=S.ID_ENTIDAD)
          WHEN  MATCHED THEN UPDATE SET  
          S.MENOREDAD=T.MENOREDAD,
          S.MENOREDAD_URL = T.MENOREDAD_URL;
          --S.ID_SEDEAREA=T.ID_SEDEAREA,
          --S.ID_PUESTO=T.ID_PUESTO,
          --S.ID_TIPO_HORARIO=T.ID_TIPO_HORARIO,
          --S.ID_PERFIL_PUESTO=T.ID_PERFIL_PUESTO,
          --S.ID_SITUACION_TRABAJADOR='P';--PROCESO DE CONTRATACION
        else
          MERGE INTO MOISES.TRABAJADOR S 
          USING(
           SELECT
              A.ID_CONTRATO,
              A.ID_ENTIDAD,
              A.ID_DEPTO,
              A.ID_PERSONA,
              A.ID_SEDEAREA,
              A.MENOREDAD,
              A.MENOREDAD_URL,
              B.ID_PUESTO,
              B.ID_TIPO_HORARIO,
              A.ID_PERFIL_PUESTO,
              A.ID_CONDICION_LABORAL
            FROM PLLA_CONTRATO A , PLLA_PERFIL_PUESTO B
            WHERE A.ID_PERFIL_PUESTO=B.ID_PERFIL_PUESTO
            AND A.ID_CONTRATO=P_ID_CONTRATO
          )T ON (T.ID_PERSONA=S.ID_PERSONA AND T.ID_ENTIDAD=S.ID_ENTIDAD)
          WHEN  MATCHED THEN UPDATE SET  
          S.MENOREDAD=T.MENOREDAD,
          S.MENOREDAD_URL = T.MENOREDAD_URL, 
          S.ID_SEDEAREA=T.ID_SEDEAREA,
          S.ID_PUESTO=T.ID_PUESTO,
          --S.ID_TIPO_HORARIO=T.ID_TIPO_HORARIO,
          S.ID_PERFIL_PUESTO=T.ID_PERFIL_PUESTO,
          S.ID_CONDICION_LABORAL=T.ID_CONDICION_LABORAL,
          S.ID_SITUACION_TRABAJADOR='P';--PROCESO DE CONTRATACION
        end if;

        /*
        MERGE INTO MOISES.TRABAJADOR S 
        USING(
         SELECT
            A.ID_CONTRATO,
            A.ID_ENTIDAD,
            A.ID_DEPTO,
            A.ID_PERSONA,
            A.ID_SEDEAREA,
            A.MENOREDAD,
            A.MENOREDAD_URL,
            B.ID_PUESTO,
            B.ID_TIPO_HORARIO,
            A.ID_PERFIL_PUESTO,
            A.ID_CONDICION_LABORAL
          FROM PLLA_CONTRATO A , PLLA_PERFIL_PUESTO B
          WHERE A.ID_PERFIL_PUESTO=B.ID_PERFIL_PUESTO
          AND A.ID_CONTRATO=P_ID_CONTRATO
        )T ON(T.ID_PERSONA=S.ID_PERSONA AND T.ID_ENTIDAD=S.ID_ENTIDAD)
        WHEN  MATCHED THEN UPDATE SET  
        S.MENOREDAD=T.MENOREDAD,
        S.MENOREDAD_URL = T.MENOREDAD_URL, 
        S.ID_SEDEAREA=T.ID_SEDEAREA,
        S.ID_PUESTO=T.ID_PUESTO,
        --S.ID_TIPO_HORARIO=T.ID_TIPO_HORARIO,
        S.ID_PERFIL_PUESTO=T.ID_PERFIL_PUESTO,
        S.ID_CONDICION_LABORAL=T.ID_CONDICION_LABORAL,
        S.ID_SITUACION_TRABAJADOR=case when l_id_siuacion_trabajador ='1' then '1' else  'P' end;--PROCESO DE CONTRATACION
        */
        
        if P_OPC='X' then
--           goto salida_gen_trabajador;
        end if;

        if l_tipo_pago = 'H' then
            
            
              --l_tipo_pago,l_contrato_mensual, l_modo_pago
              
              if l_modo_pago = 'M' and l_contrato_mensual = 0 then
              
                delete from enoc.PLLA_CONTRATO_DET where id_contrato=P_ID_CONTRATO;

                insert into enoc.PLLA_CONTRATO_DET(
                  ID_ITEM,
                  ID_CONTRATO,
                  TIPO,
                  ID_ANHO,
                  ID_MES,
                  ID_SEDEAREA,
                  ID_PROGRAMA_ESTUDIO,
                  ID_TIPO_HORA_PAGO,
                  ID_ESCALA_SALA_DOCENTE_DET,
                  ID_SEMESTRE,
                  DIAS,
                  COSTOHORA,
                  HORAS,
                  IMPORTE,
                  VIGENCIA,
                  ID_USER_REG,
                  FECHA_REG,
                  ID_SOLIC_REQ_CANDIDATO_DET,
                  ID_TIPO_CANTIDAD
                )
                SELECT
                  ID_ITEM,
                  ID_CONTRATO,
                  'C',
                  ID_ANHO,
                  ID_MES,
                  ID_SEDEAREA,
                  ID_PROGRAMA_ESTUDIO,
                  ID_TIPO_HORA_PAGO,
                  ID_ESCALA_SALA_DOCENTE_DET,
                  ID_SEMESTRE,
                  DIAS,
                  COSTOHORA,
                  HORAS,
                  IMPORTE,
                  1,
                  P_ID_USER,
                  clock_timestamp(),
                  ID_SOLIC_REQ_CANDIDATO_DET,
                  ID_TIPO_CANTIDAD
                from enoc.PLLA_CONTRATO_MES
                where id_contrato=P_ID_CONTRATO
                order by ID_ITEM;

              end if;

              if l_modo_pago = 'M' and l_contrato_mensual = 1 then
              
                delete from enoc.PLLA_CONTRATO_DET where id_contrato=P_ID_CONTRATO;

                
                select coalesce(min(id_anho),0) into STRICT l_id_anho_proc
                from enoc.PLLA_CONTRATO_MES
                where id_contrato=P_ID_CONTRATO
                and ID_SOLIC_REQ_CANDIDATO_DET not in (
                  SELECT a.ID_SOLIC_REQ_CANDIDATO_DET from enoc.PLLA_CONTRATO_DET a, enoc.PLLA_CONTRATO c
                  where a.id_contrato=c.id_contrato
                  and c.ID_SOLIC_REQ_CANDIDATO = l_id_solic_req_candidato
                  and c.ID_ESTADO_CONT_DEPTO in (
                     SELECT a.ID_ESTADO_CONT_DEPTO 
                     FROM PLLA_ESTADO_CONT_DEPTO a, PLLA_ESTADO_CONT b 
                     WHERE a.ID_ESTADO_CONT=b.ID_ESTADO_CONT 
                     AND  a.ID_ENTIDAD=l_id_entidad 
                     AND a.ID_DEPTO=l_id_depto 
                     AND a.TIPO='C' 
                     AND b.ID_ESTADO_CONT not in ('00') 
                  ) 
                );

                select coalesce(min(id_mes),0) into STRICT l_id_mes_proc
                from enoc.PLLA_CONTRATO_MES
                where id_contrato=P_ID_CONTRATO
                and id_anho=l_id_anho_proc
                and ID_SOLIC_REQ_CANDIDATO_DET not in (
                  SELECT a.ID_SOLIC_REQ_CANDIDATO_DET from enoc.PLLA_CONTRATO_DET a, enoc.PLLA_CONTRATO c
                  where a.id_contrato=c.id_contrato
                  and c.ID_SOLIC_REQ_CANDIDATO = l_id_solic_req_candidato
                  and c.ID_ESTADO_CONT_DEPTO in (
                     SELECT a.ID_ESTADO_CONT_DEPTO 
                     FROM PLLA_ESTADO_CONT_DEPTO a, PLLA_ESTADO_CONT b 
                     WHERE a.ID_ESTADO_CONT=b.ID_ESTADO_CONT 
                     AND  a.ID_ENTIDAD=l_id_entidad 
                     AND a.ID_DEPTO=l_id_depto 
                     AND a.TIPO='C' 
                     AND b.ID_ESTADO_CONT not in ('00') 
                  ) 
                );

                
                insert into enoc.PLLA_CONTRATO_DET(
                  ID_ITEM,
                  ID_CONTRATO,
                  TIPO,
                  ID_ANHO,
                  ID_MES,
                  ID_SEDEAREA,
                  ID_PROGRAMA_ESTUDIO,
                  ID_TIPO_HORA_PAGO,
                  ID_ESCALA_SALA_DOCENTE_DET,
                  ID_SEMESTRE,
                  DIAS,
                  COSTOHORA,
                  HORAS,
                  IMPORTE,
                  VIGENCIA,
                  ID_USER_REG,
                  FECHA_REG,
                  ID_SOLIC_REQ_CANDIDATO_DET,
                  ID_TIPO_CANTIDAD
                )
                SELECT
                  ID_ITEM,
                  ID_CONTRATO,
                  'C',
                  ID_ANHO,
                  ID_MES,
                  ID_SEDEAREA,
                  ID_PROGRAMA_ESTUDIO,
                  ID_TIPO_HORA_PAGO,
                  ID_ESCALA_SALA_DOCENTE_DET,
                  ID_SEMESTRE,
                  DIAS,
                  COSTOHORA,
                  HORAS,
                  IMPORTE,
                  1,
                  P_ID_USER,
                  clock_timestamp(),
                  ID_SOLIC_REQ_CANDIDATO_DET,
                  ID_TIPO_CANTIDAD
                from enoc.PLLA_CONTRATO_MES
                where id_contrato=P_ID_CONTRATO
                and id_anho=l_id_anho_proc
                and id_mes = l_id_mes_proc
                order by ID_ITEM;

                
                
                IF l_id_anho_proc>0 AND l_id_mes_proc>0 THEN
                    select 
                     min(FEC_DESDE) as FEC_DESDE,
                     max(FEC_HASTA) as FEC_HASTA
                     into STRICT 
                     l_fecha_inic,
                     l_fecha_finc
                    from enoc.PLLA_CONTRATO_MES
                    where id_contrato=P_ID_CONTRATO
                    and id_anho=l_id_anho_proc
                    and id_mes = l_id_mes_proc;

                    
                    update enoc.plla_contrato set
                    fecha_ini=l_fecha_inic,
                    fecha_fin=l_fecha_finc
                    where id_contrato = P_ID_CONTRATO;
                END IF;

                
              end if;

              if l_modo_pago = 'C' and l_contrato_mensual = 1 then
              
                  
                  
                 delete from enoc.PLLA_CONTRATO_DET where id_contrato=P_ID_CONTRATO;

                
                select coalesce(min(id_anho),0) into STRICT l_id_anho_proc
                from enoc.PLLA_CONTRATO_MES
                where id_contrato=P_ID_CONTRATO
                AND VIGENCIA=1;

                
                select coalesce(min(id_mes),0) into STRICT l_id_mes_proc
                from enoc.PLLA_CONTRATO_MES
                where id_contrato=P_ID_CONTRATO
                and id_anho=l_id_anho_proc
                AND VIGENCIA=1;

                              
                
                insert into enoc.PLLA_CONTRATO_DET(
                  ID_ITEM,
                  ID_CONTRATO,
                  TIPO,
                  ID_ANHO,
                  ID_MES,
                  ID_SEDEAREA,
                  ID_PROGRAMA_ESTUDIO,
                  ID_TIPO_HORA_PAGO,
                  ID_ESCALA_SALA_DOCENTE_DET,
                  ID_SEMESTRE,
                  DIAS,
                  COSTOHORA,
                  HORAS,
                  IMPORTE,
                  VIGENCIA,
                  ID_USER_REG,
                  FECHA_REG,
                  ID_SOLIC_REQ_CANDIDATO_DET,
                  ID_TIPO_CANTIDAD
                )
                SELECT
                  ID_ITEM,
                  ID_CONTRATO,
                  'C',
                  ID_ANHO,
                  ID_MES,
                  ID_SEDEAREA,
                  ID_PROGRAMA_ESTUDIO,
                  ID_TIPO_HORA_PAGO,
                  ID_ESCALA_SALA_DOCENTE_DET,
                  ID_SEMESTRE,
                  DIAS,
                  COSTOHORA,
                  HORAS,
                  IMPORTE,
                  1,
                  P_ID_USER,
                  clock_timestamp(),
                  ID_SOLIC_REQ_CANDIDATO_DET,
                  ID_TIPO_CANTIDAD
                from enoc.PLLA_CONTRATO_MES
                where id_contrato=P_ID_CONTRATO
                and id_anho=l_id_anho_proc
                and id_mes = l_id_mes_proc
                order by ID_ITEM;


                IF l_id_anho_proc>0 AND l_id_mes_proc>0 THEN
                    select 
                     min(FEC_DESDE) as FEC_DESDE,
                     max(FEC_HASTA) as FEC_HASTA
                     into STRICT 
                     l_fecha_inic,
                     l_fecha_finc
                    from enoc.PLLA_CONTRATO_MES
                    where id_contrato=P_ID_CONTRATO
                    and id_anho=l_id_anho_proc
                    and id_mes = l_id_mes_proc;

                    
                    update enoc.plla_contrato set
                    fecha_ini=l_fecha_inic,
                    fecha_fin=l_fecha_finc
                    where id_contrato = P_ID_CONTRATO;
                END IF;
              END IF;

              select count(*) into STRICT l_contar from enoc.PLLA_CONTRATO_DET where id_contrato=P_ID_CONTRATO;

              IF l_contar=0 THEN
                  l_error:=1;
                  l_msgerror:='No se ha generado detalle contrato';
--                   goto salida_gen_trabajador;
              END IF;

         end if;

        
       else
       
       update PLLA_CONTRATO set ID_TIPO_TIEMPO_REGIMEN = case when id_condicion_laboral='M' then 4 else ID_TIPO_TIEMPO_TRABAJO end  where id_contrato=P_ID_CONTRATO;

        MERGE INTO MOISES.TRABAJADOR S 
       USING(
         SELECT
            A.ID_CONTRATO,
            A.ID_ENTIDAD,
            A.ID_DEPTO,
            A.ID_PERSONA,
            A.ID_SEDEAREA,
            A.ID_PERFIL_PUESTO,
            A.ID_TIPO_TIEMPO_TRABAJO,
            A.ID_CONDICION_LABORAL,
            A.FECHA_INI,
            A.FECHA_FIN,
            A.MENOREDAD,
            A.MENOREDAD_URL,
            A.ID_TIPO_OCUPACION,
            A.ID_SITUACION_TRABAJADOR,
            B.ID_PUESTO,
            B.ID_TIPO_CONTROL_PERSONAL,
            A.ID_TIPO_HORARIO,--B.ID_TIPO_HORARIO,
            A.FECHA_INICIO_MISIONERO,
            A.MISIONERO_URL,
            A.ID_TIPO_STATUS,
            A.ID_PERIODO_REMU,
            A.ID_TIPO_CONTRATO,
            A.ID_GRUPO_PLANILLA,
            A.ID_TIPO_TIEMPO_REGIMEN
          FROM PLLA_CONTRATO A , PLLA_PERFIL_PUESTO B
          WHERE A.ID_PERFIL_PUESTO=B.ID_PERFIL_PUESTO
          AND A.ID_CONTRATO=P_ID_CONTRATO
        )T ON (T.ID_PERSONA=S.ID_PERSONA AND T.ID_ENTIDAD=S.ID_ENTIDAD)
        WHEN  MATCHED THEN UPDATE SET  
        S.MENOREDAD=T.MENOREDAD,
        S.MENOREDAD_URL = T.MENOREDAD_URL, 
        S.ID_SITUACION_TRABAJADOR=T.ID_SITUACION_TRABAJADOR,
        --S.ID_TIPO_CONTROL_PERSONAL=T.ID_TIPO_CONTROL_PERSONAL,
        S.ID_CONDICION_LABORAL=T.ID_CONDICION_LABORAL,
        S.FECHA_INICIO_MISIONERO=T.FECHA_INICIO_MISIONERO,
        S.MISIONERO_URL=T.MISIONERO_URL,
        S.ID_TIPO_STATUS=T.ID_TIPO_STATUS,
        S.FECHA_INGRESO=CASE WHEN S.FECHA_INGRESO = NULL THEN T.FECHA_INI ELSE S.FECHA_INGRESO END,
        S.FECHA_INICIO=T.FECHA_INI,
        S.FECHA_FIN_PREVISTO=T.FECHA_FIN,
        S.FECHA_FIN_EFECTIVO = NULL,
        S.ID_PERIODO_REMU=T.ID_PERIODO_REMU,
        S.ID_TIPO_CONTRATO=T.ID_TIPO_CONTRATO,
        S.ID_SEDEAREA=T.ID_SEDEAREA,
        S.ID_PUESTO=T.ID_PUESTO,
        S.ID_TIPO_TIEMPO_TRABAJO=T.ID_TIPO_TIEMPO_TRABAJO,
        S.ID_GRUPO_PLANILLA=T.ID_GRUPO_PLANILLA,
        --S.ID_TIPO_HORARIO=T.ID_TIPO_HORARIO,
        S.ID_TIPO_OCUPACION=T.ID_TIPO_OCUPACION,
        S.ID_PERFIL_PUESTO=T.ID_PERFIL_PUESTO,
        S.ID_CONTRATO=T.ID_CONTRATO,
        S.ID_TIPO_TIEMPO_REGIMEN=T.ID_TIPO_TIEMPO_REGIMEN;

        
          --S.ID_SEDEAREA=T.ID_SEDEAREA,
          --S.ID_PUESTO=T.ID_PUESTO,
          --S.ID_TIPO_HORARIO=T.ID_TIPO_HORARIO,
          --S.ID_PERFIL_PUESTO=T.ID_PERFIL_PUESTO,
          --S.ID_SITUACION_TRABAJADOR='P';--PROCESO DE CONTRATACION
        
        
       end if;

      
       if P_OPC<>'C' then
       
          UPDATE PLLA_REMUNERACION SET VIGENCIA=0 WHERE id_trabajador = l_id_trabajador AND VIGENCIA=1;

          select coalesce(max(ID_REMUNERACION),0) + 1  into STRICT l_id_remuneracion  from  PLLA_REMUNERACION;

          INSERT INTO PLLA_REMUNERACION(
            ID_REMUNERACION,
            ID_TRABAJADOR,
            ID_CONTRATO,
            REFERENCIA,
            REFERENCIA_URL,
            FEC_EFECTIVO,
            TIPO_PAGO,
            FMR,
            SUELDO,
            BONIFICACION,
            OBSERVACION,
            ID_ESTADO_REMUNE,
            VIGENCIA,
            ID_USER_REG,
            FECHA_REG,
            ID_USER_MOD,
            FECHA_MOD,
            ID_ESCALA_SALARIAL
          )
          SELECT
            l_id_remuneracion,
            l_id_trabajador,
            ID_CONTRATO,
            null,
            null,
            clock_timestamp(),
            TIPO_PAGO,
            PJE_FMR,
            SUELDO,
            0,
            'Contrato',
            '04',--aprobacion gth
            1,
            P_ID_USER,
            clock_timestamp(),
            null,
            null,
            ID_ESCALA_SALARIAL
            FROM plla_contrato 
            where id_contrato=P_ID_CONTRATO;

            ---CONTRATO DETALLE---
            if l_tipo_pago = 'H' then
            
            
              IF l_modo_pago = 'M' and l_contrato_mensual = 1 THEN
                  UPDATE enoc.PLLA_CONTRATO_MES
                    SET VIGENCIA=0
                  where id_contrato=P_ID_CONTRATO
                  and id_item in (
                    SELECT id_item from enoc.PLLA_CONTRATO_DET
                    WHERE id_contrato=P_ID_CONTRATO
                  );

              END IF;

              IF l_modo_pago = 'C' and l_contrato_mensual = 1 THEN
              
                  UPDATE enoc.PLLA_CONTRATO_MES
                    SET VIGENCIA=0
                  where id_contrato=P_ID_CONTRATO
                  and id_item in (
                    SELECT id_item from enoc.PLLA_CONTRATO_DET
                    WHERE id_contrato=P_ID_CONTRATO
                  );

              END IF;

              select coalesce(max(ID_REMUNERACION_DET),0)  into STRICT l_id_remuneracion_det  from  PLLA_REMUNERACION_DET;

              insert into PLLA_REMUNERACION_DET(
                ID_REMUNERACION_DET,
                ID_REMUNERACION,
                ID_ITEM,
                ID_CONTRATO,
                ID_ANHO,
                ID_MES,
                ID_SEDEAREA,
                ID_PROGRAMA_ESTUDIO,
                ID_TIPO_HORA_PAGO,
                ID_ESCALA_SALA_DOCENTE_DET,
                ID_SEMESTRE,
                DIAS,
                COSTOHORA,
                HORAS,
                IMPORTE,
                VARIACION,
                CONCEPTO,
                VIGENCIA,
                ID_USER_REG,
                FECHA_REG,
                ID_TIPO_CANTIDAD
              )
              SELECT (row_number() OVER ( ORDER BY ID_ITEM ASC )) + l_id_remuneracion_det AS id_rem_det,
              l_id_remuneracion,
              ID_ITEM,
              ID_CONTRATO,
              ID_ANHO,
              ID_MES,
              ID_SEDEAREA,
              ID_PROGRAMA_ESTUDIO,
              ID_TIPO_HORA_PAGO,
              ID_ESCALA_SALA_DOCENTE_DET,
              ID_SEMESTRE,
              DIAS,
              COSTOHORA,
              HORAS,
              IMPORTE,
              VARIACION,
              CONCEPTO,
              1,
              P_ID_USER,
              clock_timestamp(),
              ID_TIPO_CANTIDAD
              from  PLLA_CONTRATO_DET
              where id_contrato=P_ID_CONTRATO;

            end if;

            ----
            select coalesce(max(ID_REMUNERACION_ESTADO),0) + 1  into STRICT l_id  from  PLLA_REMUNERACION_ESTADO;
            insert into ENOC.PLLA_REMUNERACION_ESTADO(
              ID_REMUNERACION_ESTADO,
              ID_REMUNERACION,
              ID_ESTADO_REMUNE,
              COMENTARIO,
              ID_USER_REG,
              FECHA_REG
            )values (
              l_id,
              l_id_remuneracion,
              '04',
              null,
              P_ID_USER,
              clock_timestamp()
            );

            
            --area trabajador
            select coalesce(max(ID_TRABAJADOR_AREA),0) +1 into STRICT l_id  from MOISES.TRABAJADOR_AREA;
            insert into MOISES.TRABAJADOR_AREA(
              ID_TRABAJADOR_AREA,
              ID_TRABAJADOR,
              ID_SEDEAREA,
              DESDE,
              HASTA,
              ID_USER_REG,
              FECHA_REG,
              ID_USER_MOD,
              FECHA_MOD
              )
              SELECT
              l_id,
              id_trabajador,
              id_sedearea,
              l_fecha_ini,
              null,
              P_ID_USER,
              clock_timestamp(),
              null,
              null
              from MOISES.TRABAJADOR
              where id_trabajador=l_id_trabajador;

            --puesto trabajador
            select coalesce(max(ID_TRABAJADOR_PUESTO),0) + 1 into STRICT l_id  from MOISES.TRABAJADOR_PUESTO;
            insert into MOISES.TRABAJADOR_PUESTO(
              ID_TRABAJADOR_PUESTO,
              ID_TRABAJADOR,
              ID_PERFIL_PUESTO,
              ID_PUESTO,
              DESDE,
              HASTA,
              ID_USER_REG,
              FECHA_REG,
              ID_USER_MOD,
              FECHA_MOD
              )
              SELECT
              l_id,
              id_trabajador,
              ID_PERFIL_PUESTO,
              id_puesto,
              l_fecha_ini,
              null,
              P_ID_USER,
              clock_timestamp(),
              null,
              null
              from MOISES.TRABAJADOR
              where id_trabajador=l_id_trabajador;

            
            if P_OPC = 'A' then
               select count(*) into STRICT l_contar
               from ELISEO.aps_planilla a 
                where a.id_entidad=l_id_entidad and a.id_anho=(to_char(clock_timestamp(),'YYYY'))::numeric  and a.id_mes in (
                  SELECT max(b.id_mes) from ELISEO.aps_planilla b 
                  where a.id_entidad=b.id_entidad 
                  and a.id_anho=b.id_anho 
                  and a.id_persona=b.id_persona
                ) and a.id_persona = l_id_persona;

               if l_contar=1 then 
                 select 
                 CASE
                    WHEN a.id_sistemapension IN (1,11)
                    THEN '21'
                    WHEN a.id_sistemapension IN (3,31)
                    THEN '22'
                    WHEN a.id_sistemapension IN (4,41)
                    THEN '23'
                    WHEN a.id_sistemapension IN (6,61)
                    THEN '24'
                    WHEN a.id_sistemapension IN (7,71)
                    THEN '25'
                    WHEN a.id_sistemapension IN (5)
                    THEN '02'
                    ELSE
                    NULL
                  END AS id_sistemapension,
                  CASE
                    WHEN a.id_sistemapension IN (1,3,4,6,71)
                    THEN 1
                    WHEN a.id_sistemapension IN (7,11,31,41,61)
                    THEN 2
                    ELSE
                    NULL
                  END AS tipo_comision
                  into STRICT l_id_regimen_pensionaria,l_id_tipo_comision_pens
                 from ELISEO.aps_planilla a 
                  where a.id_entidad=l_id_entidad and a.id_anho=(to_char(clock_timestamp(),'YYYY'))::numeric  and a.id_mes in (
                    SELECT max(b.id_mes) from ELISEO.aps_planilla b 
                    where a.id_entidad=b.id_entidad 
                    and a.id_anho=b.id_anho 
                    and a.id_persona=b.id_persona
                  ) and a.id_persona = l_id_persona;
               end if;
               
               SELECT count(*) into STRICT l_contar
               FROM ELISEO.APS_TRABAJADOR WHERE ID_PERSONA = l_id_persona;

               if l_contar = 1 then
                 SELECT FEC_INICIOAFP,FEC_INICIOONP into STRICT l_fec_inicioafp,l_fec_inicioonp
                 FROM ELISEO.APS_TRABAJADOR WHERE ID_PERSONA = l_id_persona;
               end if;
               
              update moises.PERSONA_NATURAL_TRABAJADOR set
                   id_tipo_comision_pens=l_id_tipo_comision_pens,
                   id_regimen_pensionaria=l_id_regimen_pensionaria,
                   fec_inicioafp=l_fec_inicioafp,
                   fec_inicioonp=l_fec_inicioonp
              where id_persona=l_id_persona;

            end if;

             --TIPO HORARIO
             --CONTROL PERSONAL
             --MODALIDAD
             SELECT
              B.ID_TIPO_CONTROL_PERSONAL,
              A.ID_TIPO_HORARIO,
              A.ID_SITUACION_ESPECIAL,
              B.ID_TIPO_HORARIO
              INTO STRICT
              l_id_tipo_control_personal,
              l_id_tipo_horario,
              l_id_situacion_especial,
              l_id_tipo_horario_pf
            FROM PLLA_CONTRATO A , PLLA_PERFIL_PUESTO B
            WHERE A.ID_PERFIL_PUESTO=B.ID_PERFIL_PUESTO
            AND A.ID_CONTRATO=P_ID_CONTRATO;

            if coalesce(l_id_tipo_horario::text, '') = '' then
              update PLLA_CONTRATO set
              ID_TIPO_HORARIO=l_id_tipo_horario_pf
              where ID_CONTRATO=P_ID_CONTRATO;

              l_id_tipo_horario:=l_id_tipo_horario_pf;
            end if;

          
            select
              coalesce(ID_TIPO_CONTROL_PERSONAL,0),
              coalesce(ID_TIPO_HORARIO,0),
              coalesce(ID_SITUACION_ESPECIAL,'-')
              into STRICT 
              l_id_tipo_control_personal_act,
              l_id_tipo_horario_act,
              l_id_situacion_especial_act
            from moises.trabajador where id_trabajador=l_id_trabajador;

            SELECT c.codigo into STRICT l_codigo FROM ENOC.PLLA_TIPO_HORARIO A ,ENOC.PLLA_TIPO_CONFIG_HORARIO c 
            WHERE c.ID_TIPO_CONFIG_HORARIO=a.ID_TIPO_CONFIG_HORARIO
            AND A.id_tipo_horario=l_id_tipo_horario;

            if l_codigo = 'HM' then
              l_id_tipo_control_personal:= 3; --	Sujeto a fiscalizacion
            end if;

            select count(1) into STRICT l_contar from PLLA_CONTROL_PERSONAL_TRAB where id_trabajador=l_id_trabajador;

            if l_id_tipo_control_personal<>l_id_tipo_control_personal_act or l_contar=0 then
              if (l_id_tipo_control_personal IS NOT NULL AND l_id_tipo_control_personal::text <> '') then
                CALL pkg_assistance_sp_cambio_datos(
                 l_id_trabajador,
                 l_id_tipo_control_personal::text,
                 l_fecha_ini,
                 null,
                 'Proceso de contrato',
                 P_ID_USER,
                 'TP',
                 l_ret_asis,
                 l_error,
                 l_msgerror
                 );
               end if;
             end if;

             select count(1) into STRICT l_contar from PLLA_TIPO_HORARIO_TRAB where id_trabajador=l_id_trabajador;

             if l_id_tipo_horario<>l_id_tipo_horario_act or l_contar=0 then
               if (l_id_tipo_horario IS NOT NULL AND l_id_tipo_horario::text <> '') then
                CALL pkg_assistance_sp_cambio_datos(
                 l_id_trabajador,
                 l_id_tipo_horario::text,
                 l_fecha_ini,
                 null,
                 'Proceso de contrato',
                 P_ID_USER,
                 'TH',
                 l_ret_asis,
                 l_error,
                 l_msgerror
                 );
               end if;
             end if;

             select count(1) into STRICT l_contar from moises.TRABAJADOR_SIT_ESP where id_trabajador=l_id_trabajador;

             if l_id_situacion_especial<>l_id_situacion_especial_act or l_contar=0 then
               if (l_id_situacion_especial IS NOT NULL AND l_id_situacion_especial::text <> '') then
                CALL pkg_assistance_sp_cambio_datos(
                 l_id_trabajador,
                 l_id_situacion_especial,
                 l_fecha_ini,
                 null,
                 'Proceso de contrato',
                 P_ID_USER,
                 'TM',
                 l_ret_asis,
                 l_error,
                 l_msgerror
                 );
               end if;
              end if;

       end if;

       if l_contar=0 then
          l_contar:=0;
       end if;

       
--         <<salida_gen_trabajador>>
        P_ERROR:=l_error;
        P_MSGERROR:=l_msgerror;
      END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE enoc.pkg_contract_sp_gen_contrato_trabajador (P_ID_CONTRATO bigint,P_ID_USER bigint,P_OPC text,P_ERROR OUT bigint,P_MSGERROR out text) FROM PUBLIC;
