-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_conta_doc_usuario_salida_id ON conta_documento_usuario_salida CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_conta_doc_usuario_salida_id() RETURNS trigger AS $BODY$
BEGIN

  SELECT nextval('eliseo.sq_conta_doc_usuario_salida_id') 

  INTO STRICT   NEW.ID_USUARIOSALIDA

;

RETURN NEW;
END;
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_conta_doc_usuario_salida_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_conta_doc_usuario_salida_id ON conta_documento_usuario_salida;
CREATE TRIGGER tr_conta_doc_usuario_salida_id
	BEFORE INSERT ON conta_documento_usuario_salida FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_conta_doc_usuario_salida_id();

