-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_caja_chequera_voucher_id ON caja_chequera_voucher CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_tr_caja_chequera_voucher_id() RETURNS trigger AS $BODY$
DECLARE
CONTADOR integer;
BEGIN
SELECT coalesce(MAX(ID_CVOUCHER),0)+1  INTO STRICT CONTADOR
FROM CAJA_CHEQUERA_VOUCHER;

NEW.ID_CVOUCHER:=CONTADOR;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_tr_caja_chequera_voucher_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_caja_chequera_voucher_id ON caja_chequera_voucher;
CREATE TRIGGER tr_caja_chequera_voucher_id
	BEFORE INSERT ON caja_chequera_voucher 
 FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_tr_caja_chequera_voucher_id();

