-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS trig_pro_proforma_id ON pro_proforma CASCADE;
CREATE OR REPLACE FUNCTION eliseo.trigger_fct_trig_pro_proforma_id() RETURNS trigger AS $BODY$
BEGIN
    IF coalesce(NEW.ID_PROFORMA::text, '') = '' THEN
        SELECT nextval('eliseo.sq_pro_proforma')
        INTO STRICT NEW.ID_PROFORMA
;
    END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION eliseo.trigger_fct_trig_pro_proforma_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS trig_pro_proforma_id ON pro_proforma;
CREATE TRIGGER trig_pro_proforma_id
	BEFORE INSERT ON pro_proforma FOR EACH ROW
	EXECUTE PROCEDURE eliseo.trigger_fct_trig_pro_proforma_id();

