-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_purchases_orders,public;




CREATE OR REPLACE FUNCTION eliseo.pkg_purchases_orders_fc_paso (P_ID_DEXEC bigint) RETURNS varchar AS $body$
DECLARE

        L_ID_EXECUTE bigint;
        PASO varchar(100);

BEGIN
        SELECT DISTINCT ID_EXECUTE INTO STRICT L_ID_EXECUTE FROM LAMB_PROCESS_EXEC_PASO WHERE ID_DEXEC = P_ID_DEXEC;
        SELECT
                B.NOMBRE INTO STRICT PASO
        FROM LAMB_PROCESS_EXEC_PASO A JOIN LAMB_PROCESS_PASO B ON A.ID_PASO_ACTUAL = B.ID_PASO AND A.ESTADO <> 3 
        WHERE A.ID_EXECUTE = L_ID_EXECUTE
        AND A.ID_DEXEC = P_ID_DEXEC;

            
        RETURN(PASO);
    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.pkg_purchases_orders_fc_paso (P_ID_DEXEC bigint) FROM PUBLIC;
