-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_finances_students,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_finances_students_sp_actualizar_total_venta (P_ID_VENTA bigint) AS $body$
DECLARE

        l_igv decimal(10,2);
        l_gravada decimal(10,2);
        l_inafecta decimal(10,2);
        l_exonerada decimal(10,2);
        l_gratuita decimal(10,2);
        l_descuento decimal(10,2);
        l_total decimal(10,2);
        l_gravada_me decimal(10,2);
        l_inafecta_me decimal(10,2);
        l_exonerada_me decimal(10,2);
        l_gratuita_me decimal(10,2);
        l_descuento_me decimal(10,2);
        l_igv_me decimal(10,2);
        l_total_me decimal(10,2);
        l_totaldescuento decimal(10,2):=0;
        l_otros_cargos decimal(10,2) := 0;
        l_otros_cargos_me decimal(10,2) := 0;

BEGIN
            SELECT
                    coalesce(sum(case when t.gravado in ('G') then d.BASE else 0 end),0) as gravada, 
                    coalesce(sum(case when t.gravado in ('I') then d.BASE else 0 end),0) as inafecta,
                    coalesce(sum(case when t.gravado in ('E') then d.BASE else 0 end),0) as exonerado,
                    coalesce(sum(case when d.ID_TIPOIGV in ('21') then d.BASE else 0 end),0) as gratuita,
                    ABS(coalesce(sum(d.DESCUENTO),0)),
                    coalesce(sum(d.IGV),0), 
                    coalesce(sum(d.IMPORTE),0),
                    coalesce(sum(case when t.gravado in ('G') then d.BASE_ME else 0 end),0) as gravadame, 
                    coalesce(sum(case when t.gravado in ('I') then d.BASE_ME else 0 end),0) as inafectame,
                    coalesce(sum(case when t.gravado in ('E') then d.BASE_ME else 0 end),0) as exoneradome,
                    coalesce(sum(case when d.ID_TIPOIGV in ('21') then d.BASE_ME else 0 end),0) as gratuitame,
                    coalesce(sum(d.DESCUENTO_ME),0),
                    coalesce(sum(d.IGV_ME),0), 
                    coalesce(sum(d.IMPORTE_ME),0),
                    coalesce(sum(d.OTROS_CARGOS),0),
                    coalesce(sum(d.OTROS_CARGOS_ME),0)
                    into STRICT
                    l_gravada, 
                    l_inafecta, 
                    l_exonerada, 
                    l_gratuita, 
                    l_descuento,
                    l_igv,
                    l_total,
                    l_gravada_me, 
                    l_inafecta_me, 
                    l_exonerada_me, 
                    l_gratuita_me, 
                    l_descuento_me,
                    l_igv_me,
                    l_total_me,
                    l_otros_cargos,
                    l_otros_cargos_me
            from  VW_VENTA_DETALLE d,tipo_igv t
            where d.ID_TIPOIGV=t.ID_TIPOIGV
            and d.id_venta=P_ID_VENTA;

            UPDATE VENTA SET
                            GRAVADA=l_gravada, 
                            INAFECTA=l_inafecta, 
                            EXONERADA=l_exonerada, 
                            GRATUITA=l_gratuita, 
                            DESCUENTO=l_descuento, 
                            IGV=l_igv, 
                            TOTAL=l_total, 
                            GRAVADA_ME=l_gravada_me, 
                            INAFECTA_ME=l_inafecta_me ,
                            EXONERADA_ME=l_exonerada_me, 
                            GRATUITA_ME=l_gratuita_me, 
                            DESCUENTO_ME= l_gratuita_me,
                            IGV_ME=l_igv_me, 
                            TOTAL_ME=l_total_me,
                            OTROS_CARGOS = l_otros_cargos,
                            OTROS_CARGOS_ME = l_otros_cargos_me
            WHERE ID_VENTA=P_ID_VENTA;

    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_finances_students_sp_actualizar_total_venta (P_ID_VENTA bigint) FROM PUBLIC;
