-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_finances_students,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_finances_students_sp_desc_cred_prac_fijo (P_ID_ALUMNO_CONTRATO bigint,P_ID_CRITERIO_SEMESTRE bigint,P_TIPO_ALUMNO text,P_ERROR OUT bigint,P_MSGERROR out text) AS $body$
DECLARE

    l_items bigint;
    l_contar bigint;
    l_contar1 bigint;
    l_error bigint:=0;
    l_msgerror varchar(200):='';
    l_id_semestre_programa bigint;
    l_id_persona bigint;

    l_id_criterio	bigint;
    l_importe	decimal(10,2);
    l_tipo_proceso	varchar(2);
    l_tipo_valor	varchar(2);
    l_id_semestre bigint;
    l_nombre varchar(150);
    l_id_plan_programa bigint;
    l_id_plan bigint;
    l_dc varchar(1);
    l_creditos decimal(10,2);
    l_id_criterio_proc bigint;
    l_id_criterio_semestre bigint;

BEGIN
  
    SELECT ID_SEMESTRE_PROGRAMA,ID_PERSONA,ID_PLAN_PROGRAMA
    INTO STRICT l_id_semestre_programa,l_id_persona,l_id_plan_programa
    FROM DAVID.ACAD_ALUMNO_CONTRATO
    WHERE ID_ALUMNO_CONTRATO = P_ID_ALUMNO_CONTRATO;

    SELECT 
      TIPO_PROCESO,
      TIPO_VALOR,
      DC,
      NOMBRE,
      id_criterio_proc
      INTO STRICT
      l_tipo_proceso,
      l_tipo_valor,
      l_dc,
      l_nombre,
      l_id_criterio_proc
    FROM VW_MAT_CRITERIO_SEMESTRE
    WHERE ID_CRITERIO_SEMESTRE=P_ID_CRITERIO_SEMESTRE;

    SELECT 
    count(*)
    INTO STRICT
    l_contar
    FROM VW_MAT_CRITERIO_SEMESTRE
    WHERE ID_SEMESTRE_PROGRAMA=l_id_semestre_programa
    AND ID_CRITERIO=l_id_criterio_proc;

    if l_contar<>1 then
--       goto salida_desc_crpr_fijo;
    end if;

    SELECT 
    ID_CRITERIO_SEMESTRE
    INTO STRICT
    l_id_criterio_semestre
    FROM VW_MAT_CRITERIO_SEMESTRE
    WHERE ID_SEMESTRE_PROGRAMA=l_id_semestre_programa
    AND ID_CRITERIO=l_id_criterio_proc;

    
    SELECT 
      IMPORTE
      INTO STRICT
      l_importe
    FROM VW_MAT_CRITERIO_SEMESTRE
    WHERE ID_CRITERIO_SEMESTRE=l_id_criterio_semestre;

    
    SELECT sum(CP)  INTO STRICT l_creditos
    FROM VW_MAT_CURSOS_PLAN_ALUMNO
    WHERE ID_ALUMNO_CONTRATO=P_ID_ALUMNO_CONTRATO
    AND DESCUENTO_CREDITO='S';

    
    
    
    SELECT COALESCE(MAX(ITEM),0)+1  INTO STRICT l_items FROM MAT_CONCEPTO_ASIGN_ALUM
    WHERE ID_ALUMNO_CONTRATO=P_ID_ALUMNO_CONTRATO;

    
    
    insert into MAT_CONCEPTO_ASIGN_ALUM(
      ID_ALUMNO_CONTRATO,
      ID_CRITERIO_SEMESTRE,
      ITEM,
      ID_SEMESTRE_PROGRAMA,
      DESCRIPCION,
      DC,
      CANTIDAD,
      UNITARIO,
      TOTAL,
      TIPO_VALOR,
      ID_PLAN,
      CREDITOS,
      UNITARIO_CRED
    )
    VALUES ( 
    P_ID_ALUMNO_CONTRATO,
    P_ID_CRITERIO_SEMESTRE,
    l_items, 
    l_id_semestre_programa,
    l_nombre,
    l_dc,
    l_creditos,
    l_importe,
    l_creditos*l_importe,
    l_tipo_valor,
    null,
    l_creditos,
    l_importe
    );

--     <<salida_desc_crpr_fijo>>
    P_ERROR:=l_error;
    P_MSGERROR:= l_msgerror;
  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_finances_students_sp_desc_cred_prac_fijo (P_ID_ALUMNO_CONTRATO bigint,P_ID_CRITERIO_SEMESTRE bigint,P_TIPO_ALUMNO text,P_ERROR OUT bigint,P_MSGERROR out text) FROM PUBLIC;
