-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = enoc,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_estado_cont_depto (id_estado_cont, nombre, nombrecorto, orden, vigencia, id_estado_cont_depto, id_entidad, id_depto, tipo, orden_depto) AS SELECT
A.ID_ESTADO_CONT,
A.NOMBRE,
A.NOMBRECORTO,
A.ORDEN,
A.VIGENCIA,
B.ID_ESTADO_CONT_DEPTO,
B.ID_ENTIDAD,
B.ID_DEPTO,
B.TIPO,
B.ORDEN AS ORDEN_DEPTO
FROM ENOC.PLLA_ESTADO_CONT A,ENOC.PLLA_ESTADO_CONT_DEPTO B
WHERE A.ID_ESTADO_CONT=B.ID_ESTADO_CONT;

