-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = enoc,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_planilla_trab (id_config_planilla, id_tipo_planilla, id_grupo_planilla, id_entidad, id_depto, id_planilla, id_anho, id_mes, id_tipo_periodo_bs, id_estado_planilla, param_fmr, id_planilla_trab, id_trabajador, id_contrato, id_sedearea, id_perfil_puesto, id_situacion_trabajador, id_condicion_laboral, id_tipo_tiempo_trabajo, id_tipo_control_personal, num_dias, num_dias_vacacion, num_dias_faltas, num_dias_trab, num_horas_trab, id_proceso_boleta, archivo, correo, celular, clave, total_ingreso, total_apor_empl, total_apor_trab, total_descuento, total_neto, total_desc_assinet, total_pagar) AS SELECT
  A.ID_CONFIG_PLANILLA,
  A.ID_TIPO_PLANILLA,
  A.ID_GRUPO_PLANILLA,
  A.ID_ENTIDAD,
  A.ID_DEPTO,
  B.ID_PLANILLA,
  B.ID_ANHO,
  B.ID_MES,
  B.ID_TIPO_PERIODO_BS,
  B.ID_ESTADO_PLANILLA,
  B.PARAM_FMR,
  C.ID_PLANILLA_TRAB,
 C.ID_TRABAJADOR,
 C.ID_CONTRATO,
 C.ID_SEDEAREA,
 C.ID_PERFIL_PUESTO,
 C.ID_SITUACION_TRABAJADOR,
 C.ID_CONDICION_LABORAL,
 C.ID_TIPO_TIEMPO_TRABAJO,
 C.ID_TIPO_CONTROL_PERSONAL,
 C.NUM_DIAS,
 C.NUM_DIAS_VACACION,
 C.NUM_DIAS_FALTAS,
 C.NUM_DIAS_TRAB,
 C.NUM_HORAS_TRAB,
 C.ID_PROCESO_BOLETA,
 C.ARCHIVO,
 C.CORREO,
 C.CELULAR,
 C.CLAVE,
 C.TOTAL_INGRESO,
 C.TOTAL_APOR_EMPL,
 C.TOTAL_APOR_TRAB,
 C.TOTAL_DESCUENTO,
 C.TOTAL_NETO,
 C.TOTAL_DESC_ASSINET,
 C.TOTAL_PAGAR
FROM ENOC.PLLA_CONFIG_PLANILLA A, ENOC.PLLA_PLANILLA B,ENOC.PLLA_PLANILLA_TRAB C
WHERE A.ID_CONFIG_PLANILLA=B.ID_CONFIG_PLANILLA
AND B.ID_PLANILLA=C.ID_PLANILLA;

