-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = jairo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION jairo.fc_iniciativa_feedback_count (P_ID_MAPA_INICIATIVA integer) RETURNS bigint AS $body$
DECLARE

    RET bigint;

BEGIN

    SELECT COUNT(SIC.ID_INICIATIVA_COMENTARIO)
    INTO STRICT RET
    FROM JAIRO.SGE_INICIATIVA_COMENTARIO SIC
    WHERE SIC.ID_MAPA_INICIATIVA = P_ID_MAPA_INICIATIVA
      AND SIC.ID_PERSONA_DESTINO IN (SELECT SMID.ID_PERSONA
                                     FROM JAIRO.SGE_MAPA_INICIATIVA_DETALLE SMID
                                     WHERE SMID.ID_MAPA_INICIATIVA = P_ID_MAPA_INICIATIVA
                                       AND SMID.TIPO = '1'  LIMIT 1)
      AND (coalesce(SIC.ES_LEIDO::text, '') = '' OR SIC.ES_LEIDO = '')
      AND SIC.ID_INICIATIVA_COMENTARIO NOT IN (SELECT SIC2.ID_INICIATIVA_COMENTARIO
                                               FROM JAIRO.SGE_INICIATIVA_COMENTARIO SIC2
                                               WHERE SIC2.ID_MAPA_INICIATIVA = P_ID_MAPA_INICIATIVA
                                                 AND SIC2.ID_PERSONA_ORIGEN IN (SELECT SMID.ID_PERSONA
                                                                                FROM JAIRO.SGE_MAPA_INICIATIVA_DETALLE SMID
                                                                                WHERE SMID.ID_MAPA_INICIATIVA = P_ID_MAPA_INICIATIVA
                                                                                  AND SMID.TIPO = '1'  LIMIT 1) );
    return RET;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION jairo.fc_iniciativa_feedback_count (P_ID_MAPA_INICIATIVA integer) FROM PUBLIC;

