-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = jairo,pkg_planning,public;




CREATE OR REPLACE PROCEDURE jairo.pkg_planning_sp_delete_map (P_ID_MAPA bigint,P_ID_ERROR OUT bigint,P_MSN_ERROR OUT text) AS $body$
DECLARE

        L_CANT bigint;

                    
        
BEGIN
            --SELECT COUNT(1) INTO L_CANT FROM SGE_MAPA_OBJETIVO WHERE ID_MAPA = P_ID_MAPA;
            SELECT COUNT(1) INTO STRICT L_CANT FROM SGE_MAPA_OBJETIVO WHERE ID_DETALLE IN (SELECT ID_DETALLE FROM SGE_MAPA_DETALLE WHERE ID_MAPA = P_ID_MAPA);

            IF L_CANT = 0 THEN
                
                SELECT COUNT(1) INTO STRICT L_CANT FROM SGE_MAPA WHERE  ID_PARENT_MAPA = P_ID_MAPA;

                IF L_CANT = 0 THEN
                    DELETE FROM SGE_MAPA_DETALLE WHERE ID_MAPA = P_ID_MAPA;
                    DELETE FROM SGE_MAPA WHERE ID_MAPA = P_ID_MAPA;
                    P_ID_ERROR:= 0;
                    P_MSN_ERROR := 'OK, Map Eliminado el Mapa Estrategico';
                ELSE
                    P_ID_ERROR:= 1;
                    P_MSN_ERROR := 'ERROR: El Mapa a Eliminar tiene Mapas Hijos, por favor Elimine sus dependientes';
                END IF;
            ELSE
                P_ID_ERROR:= 1;
                P_MSN_ERROR := 'ERROR: El Mapa Estrategico tiene Objetivos Asignado, por favor Elimine sus Objetivos';
            END IF;
    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE jairo.pkg_planning_sp_delete_map (P_ID_MAPA bigint,P_ID_ERROR OUT bigint,P_MSN_ERROR OUT text) FROM PUBLIC;
