-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_sales,public;




CREATE OR REPLACE FUNCTION eliseo.pkg_sales_fc_verificar_serie_numero (P_ID_PERSONA bigint,P_ID_COMPROBANTE text,P_ID_ENTIDAD bigint, P_ID_DEPTO text, P_ID_COMPROBANTE_AFECTO text DEFAULT NULL) RETURNS bigint AS $body$
DECLARE

        l_value_return bigint;
        l_contar bigint;

BEGIN
	        
	        IF coalesce(P_ID_COMPROBANTE_AFECTO::text, '') = '' THEN
        
	            SELECT COUNT(*) INTO STRICT l_contar
	            FROM CONTA_DOCUMENTO_IP A INNER JOIN CONTA_DOCUMENTO_IP_USER B ON A.ID_DOCIP=B.ID_DOCIP
	            INNER JOIN CONTA_DOCUMENTO C ON A.id_documento=C.id_documento
	            AND B.id=P_ID_PERSONA
	            AND C.ID_ENTIDAD=P_ID_ENTIDAD
	            AND C.ID_DEPTO = P_ID_DEPTO
	            AND C.id_comprobante=P_ID_COMPROBANTE
                AND A.ESTADO=1;
            ELSE
            	SELECT COUNT(*) INTO STRICT l_contar
	            FROM CONTA_DOCUMENTO_IP A INNER JOIN CONTA_DOCUMENTO_IP_USER B ON A.ID_DOCIP=B.ID_DOCIP
	            INNER JOIN CONTA_DOCUMENTO C ON A.id_documento=C.id_documento
	            AND B.id=P_ID_PERSONA
	            AND C.ID_ENTIDAD=P_ID_ENTIDAD
	            AND C.ID_DEPTO = P_ID_DEPTO
	            AND C.id_comprobante=P_ID_COMPROBANTE
	            AND C.ID_COMPROBANTE_AFECTO =P_ID_COMPROBANTE_AFECTO
                AND A.ESTADO=1;

           	END IF;
            /*
            
             if l_contar>0 then
                select c.id_documento, c.serie,c.contador into l_id_documento,l_serie,l_numero 
                from CONTA_DOCUMENTO_IP a, CONTA_DOCUMENTO_IP_USER b, CONTA_DOCUMENTO c
                where a.ID_DOCIP=b.ID_DOCIP
                and a.id_documento=c.id_documento
                and b.id=P_ID_PERSONA
                and c.ID_ENTIDAD=P_ID_ENTIDAD
                and c.id_comprobante=P_ID_COMPROBANTE;
              
                update CONTA_DOCUMENTO set contador=contador+1
                where id_documento=l_id_documento;

                select serie,contador into l_serie,l_numero 
                from CONTA_DOCUMENTO 
                where id_documento=l_id_documento;     
            end if;
            
            */
            l_value_return := l_contar;

            /*
            if l_contar = 1 then
                l_value_return := 1;
            elsif l_contar = 1 then
                l_value_return := 1;
            else 
                l_value_return := 0;
            end if;
            */
      
         RETURN l_value_return;
    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.pkg_sales_fc_verificar_serie_numero (P_ID_PERSONA bigint,P_ID_COMPROBANTE text,P_ID_ENTIDAD bigint, P_ID_DEPTO text, P_ID_COMPROBANTE_AFECTO text DEFAULT NULL) FROM PUBLIC;
