-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = genesis,public;
\set ON_ERROR_STOP ON

\i ./sources/triggers/TR_CAMPANIA_CONVOCATORIA_ID_trigger.sql
\i ./sources/triggers/TR_CAMP_CONV_CARTERA_ID_trigger.sql
\i ./sources/triggers/TR_CANAL_DETALLE_ID_trigger.sql
\i ./sources/triggers/TR_CLASI_PROG_trigger.sql
\i ./sources/triggers/TR_CONVOCATORIA_DETALLE_ID_trigger.sql
\i ./sources/triggers/TR_FORMULARIO_PERSONA_ID_trigger.sql
\i ./sources/triggers/TR_FORMULARIO_PREGUNTA_ID_trigger.sql
\i ./sources/triggers/TR_PERSONA_ATENCION_ID_trigger.sql
\i ./sources/triggers/TR_PERSONA_CARTERA_ID_trigger.sql
\i ./sources/triggers/TR_PERSONA_DIRECCION_ID_trigger.sql
\i ./sources/triggers/TR_PERSONA_INTERES_ID_trigger.sql
\i ./sources/triggers/TR_PERSONA_PK_trigger.sql
\i ./sources/triggers/TR_PERSONA_RESPONSABLE_ID_trigger.sql
\i ./sources/triggers/TR_PERSONA_TELEFONO_ID_trigger.sql
\i ./sources/triggers/TR_PERSONA_VIRTUAL_ID_trigger.sql
\i ./sources/triggers/TR_RESP_FINANCIERO_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_CAMPANIA_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_CANAL_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_CARTERA_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_CLASIFICACION_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_CONDICION_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_CONVOCATORIA_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_ETAPA_trigger.sql
\i ./sources/triggers/TR_TIPO_FORMULARIO_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_OFICINA_ID_trigger.sql
\i ./sources/triggers/TR_TIPO_PREGUNTA_ID_trigger.sql
