-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET search_path = jairo,public;
ALTER TABLE dm_anio_persona DROP CONSTRAINT IF EXISTS dm_anio_persona_fk;
ALTER TABLE dm_anio_persona ADD CONSTRAINT dm_anio_persona_fk FOREIGN KEY (anio_id) REFERENCES dm_anio(id_anio) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dm_area DROP CONSTRAINT IF EXISTS dm_area_area_fk;
ALTER TABLE dm_area ADD CONSTRAINT dm_area_area_fk FOREIGN KEY (area_id) REFERENCES dm_area(id_area) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dm_area_anio DROP CONSTRAINT IF EXISTS dm_areaanio_anio_fk;
ALTER TABLE dm_area_anio ADD CONSTRAINT dm_areaanio_anio_fk FOREIGN KEY (anio_id) REFERENCES dm_anio(id_anio) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE dm_area_anio DROP CONSTRAINT IF EXISTS dm_areaanio_sedearea_fk;
ALTER TABLE dm_area_anio ADD CONSTRAINT dm_areaanio_sedearea_fk FOREIGN KEY (sedearea_id) REFERENCES dm_sede_area(id_sedearea) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dm_area_responsable DROP CONSTRAINT IF EXISTS dm_arearesponsable_areaanio_fk;
ALTER TABLE dm_area_responsable ADD CONSTRAINT dm_arearesponsable_areaanio_fk FOREIGN KEY (areaanio_id) REFERENCES dm_area_anio(id_area_anio) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dm_document DROP CONSTRAINT IF EXISTS dm_document_folder_fk;
ALTER TABLE dm_document ADD CONSTRAINT dm_document_folder_fk FOREIGN KEY (folder_id) REFERENCES dm_folder(id_folder) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dm_folder DROP CONSTRAINT IF EXISTS dm_folder_areaanio_fk;
ALTER TABLE dm_folder ADD CONSTRAINT dm_folder_areaanio_fk FOREIGN KEY (areaanio_id) REFERENCES dm_area_anio(id_area_anio) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE dm_folder DROP CONSTRAINT IF EXISTS dm_folder_folder_fk;
ALTER TABLE dm_folder ADD CONSTRAINT dm_folder_folder_fk FOREIGN KEY (id_folder) REFERENCES dm_folder(id_folder) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE dm_folder DROP CONSTRAINT IF EXISTS dm_folder_sedeareains_fk;
ALTER TABLE dm_folder ADD CONSTRAINT dm_folder_sedeareains_fk FOREIGN KEY (sedarins_id) REFERENCES dm_sedearea_instituto(id_sedearea_instituto) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE dm_folder DROP CONSTRAINT IF EXISTS dm_folder_tipo_fk;
ALTER TABLE dm_folder ADD CONSTRAINT dm_folder_tipo_fk FOREIGN KEY (tipo_id) REFERENCES dm_tipo(tipo_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dm_sedearea_instituto DROP CONSTRAINT IF EXISTS dm_sedeareains_inst_fk;
ALTER TABLE dm_sedearea_instituto ADD CONSTRAINT dm_sedeareains_inst_fk FOREIGN KEY (instituto_id) REFERENCES dm_instituciones(id_institucion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE dm_sedearea_instituto DROP CONSTRAINT IF EXISTS dm_sedeareains_sedearea_fk;
ALTER TABLE dm_sedearea_instituto ADD CONSTRAINT dm_sedeareains_sedearea_fk FOREIGN KEY (sedearea_id) REFERENCES dm_sede_area(id_sedearea) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dm_sede_area DROP CONSTRAINT IF EXISTS dm_sedearea_area_fk;
ALTER TABLE dm_sede_area ADD CONSTRAINT dm_sedearea_area_fk FOREIGN KEY (area_id) REFERENCES dm_area(id_area) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_actividad DROP CONSTRAINT IF EXISTS fk_actividad_tipo;
ALTER TABLE sge_actividad ADD CONSTRAINT fk_actividad_tipo FOREIGN KEY (id_tipo_actividad) REFERENCES sge_tipo_actividad(id_tipo_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_actividad DROP CONSTRAINT IF EXISTS fk_acti_proc;
ALTER TABLE sge_actividad ADD CONSTRAINT fk_acti_proc FOREIGN KEY (id_proceso_actividad) REFERENCES sge_proceso_actividad(id_proceso_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_actividad DROP CONSTRAINT IF EXISTS fk_detalle_actividad;
ALTER TABLE sge_actividad ADD CONSTRAINT fk_detalle_actividad FOREIGN KEY (id_iniciativa_detalle) REFERENCES sge_mapa_iniciativa_detalle(id_iniciativa_detalle) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_actividad DROP CONSTRAINT IF EXISTS fk_map_iniciativa_actividad;
ALTER TABLE sge_actividad ADD CONSTRAINT fk_map_iniciativa_actividad FOREIGN KEY (id_mapa_iniciativa) REFERENCES sge_mapa_iniciativa(id_mapa_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_actividad DROP CONSTRAINT IF EXISTS fk_map_iniciativa_estado;
ALTER TABLE sge_actividad ADD CONSTRAINT fk_map_iniciativa_estado FOREIGN KEY (id_estado) REFERENCES sge_estado(id_estado) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_actividad_ppto DROP CONSTRAINT IF EXISTS fk_actividad_ppto;
ALTER TABLE sge_actividad_ppto ADD CONSTRAINT fk_actividad_ppto FOREIGN KEY (id_actividad) REFERENCES sge_actividad(id_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_asiento DROP CONSTRAINT IF EXISTS fk_actividad_asiento;
ALTER TABLE sge_asiento ADD CONSTRAINT fk_actividad_asiento FOREIGN KEY (id_actividad) REFERENCES sge_actividad(id_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_eje DROP CONSTRAINT IF EXISTS fk_plan_eje;
ALTER TABLE sge_eje ADD CONSTRAINT fk_plan_eje FOREIGN KEY (id_plan) REFERENCES sge_plan(id_plan) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_eje_cuenta DROP CONSTRAINT IF EXISTS fk_eje_cuenta;
ALTER TABLE sge_eje_cuenta ADD CONSTRAINT fk_eje_cuenta FOREIGN KEY (id_eje) REFERENCES sge_eje(id_eje) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_eje_cuenta_cte DROP CONSTRAINT IF EXISTS fk_sge_cta_cte;
ALTER TABLE sge_eje_cuenta_cte ADD CONSTRAINT fk_sge_cta_cte FOREIGN KEY (id_cuenta) REFERENCES sge_eje_cuenta(id_cuenta) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_eje_depto DROP CONSTRAINT IF EXISTS fk_eje_depto;
ALTER TABLE sge_eje_depto ADD CONSTRAINT fk_eje_depto FOREIGN KEY (id_eje) REFERENCES sge_eje(id_eje) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_eje_depto_mapa DROP CONSTRAINT IF EXISTS fk_sge_eje_depto;
ALTER TABLE sge_eje_depto_mapa ADD CONSTRAINT fk_sge_eje_depto FOREIGN KEY (id_eje) REFERENCES sge_eje(id_eje) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_eje_depto_mapa DROP CONSTRAINT IF EXISTS fk_sge_mapa_depto;
ALTER TABLE sge_eje_depto_mapa ADD CONSTRAINT fk_sge_mapa_depto FOREIGN KEY (id_mapa) REFERENCES sge_mapa(id_mapa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_elemento DROP CONSTRAINT IF EXISTS fk_elemento_plan;
ALTER TABLE sge_elemento ADD CONSTRAINT fk_elemento_plan FOREIGN KEY (id_plan) REFERENCES sge_plan(id_plan) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_elemento DROP CONSTRAINT IF EXISTS fk_elemento_tipo;
ALTER TABLE sge_elemento ADD CONSTRAINT fk_elemento_tipo FOREIGN KEY (id_tipo) REFERENCES sge_tipo(id_tipo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_entidad_plan_user DROP CONSTRAINT IF EXISTS sys_c0073287;
ALTER TABLE sge_entidad_plan_user ADD CONSTRAINT sys_c0073287 FOREIGN KEY (id_plan) REFERENCES sge_plan(id_plan) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_file DROP CONSTRAINT IF EXISTS fk_actividad_file;
ALTER TABLE sge_file ADD CONSTRAINT fk_actividad_file FOREIGN KEY (id_actividad) REFERENCES sge_actividad(id_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_file DROP CONSTRAINT IF EXISTS fk_iniciativa_detalle2;
ALTER TABLE sge_file ADD CONSTRAINT fk_iniciativa_detalle2 FOREIGN KEY (id_iniciativa_detalle) REFERENCES sge_mapa_iniciativa_detalle(id_iniciativa_detalle) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_file DROP CONSTRAINT IF EXISTS fk_mapa_iniciativa_file;
ALTER TABLE sge_file ADD CONSTRAINT fk_mapa_iniciativa_file FOREIGN KEY (id_mapa_iniciativa) REFERENCES sge_mapa_iniciativa(id_mapa_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_flujo DROP CONSTRAINT IF EXISTS fk_mapa_iniciativa_flujo;
ALTER TABLE sge_flujo ADD CONSTRAINT fk_mapa_iniciativa_flujo FOREIGN KEY (id_mapa_iniciativa) REFERENCES sge_mapa_iniciativa(id_mapa_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_flujo DROP CONSTRAINT IF EXISTS fk_proceso_actividad_flujo;
ALTER TABLE sge_flujo ADD CONSTRAINT fk_proceso_actividad_flujo FOREIGN KEY (id_proceso_iniciativa) REFERENCES sge_proceso_iniciativa(id_proceso_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_frecuencia_detalle DROP CONSTRAINT IF EXISTS fk_frecuencia_detalle;
ALTER TABLE sge_frecuencia_detalle ADD CONSTRAINT fk_frecuencia_detalle FOREIGN KEY (id_frecuencia) REFERENCES sge_frecuencia(id_frecuencia) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_indicador DROP CONSTRAINT IF EXISTS fk_frecuencia_indicador;
ALTER TABLE sge_indicador ADD CONSTRAINT fk_frecuencia_indicador FOREIGN KEY (id_frecuencia) REFERENCES sge_frecuencia(id_frecuencia) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_indicador DROP CONSTRAINT IF EXISTS fk_indicador_medida;
ALTER TABLE sge_indicador ADD CONSTRAINT fk_indicador_medida FOREIGN KEY (id_indicador_medida) REFERENCES sge_indicador_medida(id_indicador_medida) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_indicador DROP CONSTRAINT IF EXISTS fk_indicador_parent;
ALTER TABLE sge_indicador ADD CONSTRAINT fk_indicador_parent FOREIGN KEY (id_parent_indicador) REFERENCES sge_indicador(id_indicador) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_indicador DROP CONSTRAINT IF EXISTS fk_objetivo_indicador;
ALTER TABLE sge_indicador ADD CONSTRAINT fk_objetivo_indicador FOREIGN KEY (id_objetivo) REFERENCES sge_objetivo(id_objetivo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_indicador DROP CONSTRAINT IF EXISTS fk_procedimiento_ind;
ALTER TABLE sge_indicador ADD CONSTRAINT fk_procedimiento_ind FOREIGN KEY (id_procedimiento) REFERENCES sge_procedimiento(id_procedimiento) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_indicador DROP CONSTRAINT IF EXISTS fk_tipo_nivel_indicador;
ALTER TABLE sge_indicador ADD CONSTRAINT fk_tipo_nivel_indicador FOREIGN KEY (id_tipo_nivel) REFERENCES sge_tipo_nivel(id_tipo_nivel) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_iniciativa_criterio DROP CONSTRAINT IF EXISTS fk_iniciativa_criterio;
ALTER TABLE sge_iniciativa_criterio ADD CONSTRAINT fk_iniciativa_criterio FOREIGN KEY (id_iniciativa) REFERENCES sge_iniciativa(id_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_iniciativa_cuenta DROP CONSTRAINT IF EXISTS fk_iniciativa_cuenta;
ALTER TABLE sge_iniciativa_cuenta ADD CONSTRAINT fk_iniciativa_cuenta FOREIGN KEY (id_iniciativa) REFERENCES sge_iniciativa(id_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_iniciativa_cuenta_cte DROP CONSTRAINT IF EXISTS fk_inicia_cuenta_cte;
ALTER TABLE sge_iniciativa_cuenta_cte ADD CONSTRAINT fk_inicia_cuenta_cte FOREIGN KEY (id_iniciativa_cuenta) REFERENCES sge_iniciativa_cuenta(id_iniciativa_cuenta) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa DROP CONSTRAINT IF EXISTS fk_mapa_parent;
ALTER TABLE sge_mapa ADD CONSTRAINT fk_mapa_parent FOREIGN KEY (id_parent_mapa) REFERENCES sge_mapa(id_mapa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa DROP CONSTRAINT IF EXISTS fk_plan_mapa;
ALTER TABLE sge_mapa ADD CONSTRAINT fk_plan_mapa FOREIGN KEY (id_plan) REFERENCES sge_plan(id_plan) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa DROP CONSTRAINT IF EXISTS fk_tipo_nivel_mapa;
ALTER TABLE sge_mapa ADD CONSTRAINT fk_tipo_nivel_mapa FOREIGN KEY (id_tipo_nivel) REFERENCES sge_tipo_nivel(id_tipo_nivel) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa_detalle DROP CONSTRAINT IF EXISTS fk_eje_mapa_det;
ALTER TABLE sge_mapa_detalle ADD CONSTRAINT fk_eje_mapa_det FOREIGN KEY (id_eje) REFERENCES sge_eje(id_eje) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_detalle DROP CONSTRAINT IF EXISTS fk_mapa_detalle;
ALTER TABLE sge_mapa_detalle ADD CONSTRAINT fk_mapa_detalle FOREIGN KEY (id_mapa) REFERENCES sge_mapa(id_mapa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_detalle DROP CONSTRAINT IF EXISTS fk_prespectiva_mapa_det;
ALTER TABLE sge_mapa_detalle ADD CONSTRAINT fk_prespectiva_mapa_det FOREIGN KEY (id_perspectiva) REFERENCES sge_perspectiva(id_perspectiva) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa_indicador DROP CONSTRAINT IF EXISTS fk_indicador_map_ind;
ALTER TABLE sge_mapa_indicador ADD CONSTRAINT fk_indicador_map_ind FOREIGN KEY (id_indicador) REFERENCES sge_indicador(id_indicador) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_indicador DROP CONSTRAINT IF EXISTS fk_map_obj_map_ind;
ALTER TABLE sge_mapa_indicador ADD CONSTRAINT fk_map_obj_map_ind FOREIGN KEY (id_mapa_objetivo) REFERENCES sge_mapa_objetivo(id_mapa_objetivo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa_iniciativa DROP CONSTRAINT IF EXISTS fk_estado_iniciativa;
ALTER TABLE sge_mapa_iniciativa ADD CONSTRAINT fk_estado_iniciativa FOREIGN KEY (id_estado) REFERENCES sge_estado(id_estado) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_iniciativa DROP CONSTRAINT IF EXISTS fk_iniciativa_mapa;
ALTER TABLE sge_mapa_iniciativa ADD CONSTRAINT fk_iniciativa_mapa FOREIGN KEY (id_iniciativa) REFERENCES sge_iniciativa(id_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_iniciativa DROP CONSTRAINT IF EXISTS fk_mapa_indicador_iniciativa;
ALTER TABLE sge_mapa_iniciativa ADD CONSTRAINT fk_mapa_indicador_iniciativa FOREIGN KEY (id_mapa_indicador) REFERENCES sge_mapa_indicador(id_mapa_indicador) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_iniciativa DROP CONSTRAINT IF EXISTS fk_obj_mapa_iniciatva;
ALTER TABLE sge_mapa_iniciativa ADD CONSTRAINT fk_obj_mapa_iniciatva FOREIGN KEY (id_mapa_objetivo) REFERENCES sge_mapa_objetivo(id_mapa_objetivo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa_iniciativa_detalle DROP CONSTRAINT IF EXISTS fk_iniciativa_detalle;
ALTER TABLE sge_mapa_iniciativa_detalle ADD CONSTRAINT fk_iniciativa_detalle FOREIGN KEY (id_mapa_iniciativa) REFERENCES sge_mapa_iniciativa(id_mapa_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa_iniciativa_indicador DROP CONSTRAINT IF EXISTS fk_indicador_iniciativa;
ALTER TABLE sge_mapa_iniciativa_indicador ADD CONSTRAINT fk_indicador_iniciativa FOREIGN KEY (id_mapa_indicador) REFERENCES sge_mapa_indicador(id_mapa_indicador) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_iniciativa_indicador DROP CONSTRAINT IF EXISTS fk_iniciativa_indicador;
ALTER TABLE sge_mapa_iniciativa_indicador ADD CONSTRAINT fk_iniciativa_indicador FOREIGN KEY (id_mapa_iniciativa) REFERENCES sge_mapa_iniciativa(id_mapa_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_iniciativa_indicador DROP CONSTRAINT IF EXISTS fk_mapa_iniciativa_detalle;
ALTER TABLE sge_mapa_iniciativa_indicador ADD CONSTRAINT fk_mapa_iniciativa_detalle FOREIGN KEY (id_iniciativa_detalle) REFERENCES sge_mapa_iniciativa_detalle(id_iniciativa_detalle) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa_objetivo DROP CONSTRAINT IF EXISTS fk_map_detalle;
ALTER TABLE sge_mapa_objetivo ADD CONSTRAINT fk_map_detalle FOREIGN KEY (id_detalle) REFERENCES sge_mapa_detalle(id_detalle) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_objetivo DROP CONSTRAINT IF EXISTS fk_map_detalle_objetio;
ALTER TABLE sge_mapa_objetivo ADD CONSTRAINT fk_map_detalle_objetio FOREIGN KEY (id_objetivo) REFERENCES sge_objetivo(id_objetivo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_mapa_objetivo_apoyo DROP CONSTRAINT IF EXISTS fk_mapa_obj_apoyo;
ALTER TABLE sge_mapa_objetivo_apoyo ADD CONSTRAINT fk_mapa_obj_apoyo FOREIGN KEY (id_mapa) REFERENCES sge_mapa(id_mapa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_objetivo_apoyo DROP CONSTRAINT IF EXISTS fk_map_obj_a;
ALTER TABLE sge_mapa_objetivo_apoyo ADD CONSTRAINT fk_map_obj_a FOREIGN KEY (id_map_obj_a) REFERENCES sge_mapa_objetivo(id_mapa_objetivo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_mapa_objetivo_apoyo DROP CONSTRAINT IF EXISTS fk_map_obj_de;
ALTER TABLE sge_mapa_objetivo_apoyo ADD CONSTRAINT fk_map_obj_de FOREIGN KEY (id_map_obj_de) REFERENCES sge_mapa_objetivo(id_mapa_objetivo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_meta DROP CONSTRAINT IF EXISTS fk_frec_meta;
ALTER TABLE sge_meta ADD CONSTRAINT fk_frec_meta FOREIGN KEY (id_fdetalle) REFERENCES sge_frecuencia_detalle(id_fdetalle) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_meta DROP CONSTRAINT IF EXISTS fk_mapa_indicador_meta;
ALTER TABLE sge_meta ADD CONSTRAINT fk_mapa_indicador_meta FOREIGN KEY (id_mapa_indicador) REFERENCES sge_mapa_indicador(id_mapa_indicador) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_objetivo DROP CONSTRAINT IF EXISTS fk_objetivo_parent;
ALTER TABLE sge_objetivo ADD CONSTRAINT fk_objetivo_parent FOREIGN KEY (id_parent_objetivo) REFERENCES sge_objetivo(id_objetivo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_objetivo DROP CONSTRAINT IF EXISTS fk_plan_objetivo;
ALTER TABLE sge_objetivo ADD CONSTRAINT fk_plan_objetivo FOREIGN KEY (id_plan) REFERENCES sge_plan(id_plan) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_objetivo DROP CONSTRAINT IF EXISTS fk_tipo_nivel_objetivo;
ALTER TABLE sge_objetivo ADD CONSTRAINT fk_tipo_nivel_objetivo FOREIGN KEY (id_tipo_nivel) REFERENCES sge_tipo_nivel(id_tipo_nivel) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_plan_anho DROP CONSTRAINT IF EXISTS fk_plan_anho;
ALTER TABLE sge_plan_anho ADD CONSTRAINT fk_plan_anho FOREIGN KEY (id_plan) REFERENCES sge_plan(id_plan) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_proceso DROP CONSTRAINT IF EXISTS sge_actividad_proc_fk;
ALTER TABLE sge_proceso ADD CONSTRAINT sge_actividad_proc_fk FOREIGN KEY (id_actividad) REFERENCES sge_actividad(id_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_proceso DROP CONSTRAINT IF EXISTS sge_proceso_actividad_det_fk;
ALTER TABLE sge_proceso ADD CONSTRAINT sge_proceso_actividad_det_fk FOREIGN KEY (id_proceso_actividad) REFERENCES sge_proceso_actividad(id_proceso_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_proceso_actividad DROP CONSTRAINT IF EXISTS fk_tipo_act_proc;
ALTER TABLE sge_proceso_actividad ADD CONSTRAINT fk_tipo_act_proc FOREIGN KEY (id_tipo_actividad) REFERENCES sge_tipo_actividad(id_tipo_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_proceso_actividad DROP CONSTRAINT IF EXISTS sge_tipo_proceso_act_fk;
ALTER TABLE sge_proceso_actividad ADD CONSTRAINT sge_tipo_proceso_act_fk FOREIGN KEY (id_tipo_proceso) REFERENCES sge_tipo_proceso(id_tipo_proceso) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE sge_proceso_iniciativa DROP CONSTRAINT IF EXISTS fk_mapa_iniciativa_proceso;
ALTER TABLE sge_proceso_iniciativa ADD CONSTRAINT fk_mapa_iniciativa_proceso FOREIGN KEY (id_mapa_iniciativa) REFERENCES sge_mapa_iniciativa(id_mapa_iniciativa) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE sge_proceso_iniciativa DROP CONSTRAINT IF EXISTS fk_proceso_iniciativa;
ALTER TABLE sge_proceso_iniciativa ADD CONSTRAINT fk_proceso_iniciativa FOREIGN KEY (id_tipo_proceso) REFERENCES sge_tipo_proceso(id_tipo_proceso) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_actividad_horario DROP CONSTRAINT IF EXISTS fk1_vin_carga_actividad;
ALTER TABLE vin_actividad_horario ADD CONSTRAINT fk1_vin_carga_actividad FOREIGN KEY (id_interv_actividad) REFERENCES vin_interv_actividad(id_interv_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_asistencia_interv DROP CONSTRAINT IF EXISTS vin_asistencia_fk1;
ALTER TABLE vin_asistencia_interv ADD CONSTRAINT vin_asistencia_fk1 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_asistencia_interv DROP CONSTRAINT IF EXISTS vin_asistencia_fk2;
ALTER TABLE vin_asistencia_interv ADD CONSTRAINT vin_asistencia_fk2 FOREIGN KEY (id_interv_actividad) REFERENCES vin_interv_actividad(id_interv_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_asist_interv_det DROP CONSTRAINT IF EXISTS vin_asist_interv_det_fk1;
ALTER TABLE vin_asist_interv_det ADD CONSTRAINT vin_asist_interv_det_fk1 FOREIGN KEY (id_asistencia_interv) REFERENCES vin_asistencia_interv(id_asistencia_interv) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_asist_interv_det DROP CONSTRAINT IF EXISTS vin_asist_interv_det_fk2;
ALTER TABLE vin_asist_interv_det ADD CONSTRAINT vin_asist_interv_det_fk2 FOREIGN KEY (id_persona) REFERENCES moises.persona(id_persona) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_asist_interv_det DROP CONSTRAINT IF EXISTS vin_asist_interv_det_fk4;
ALTER TABLE vin_asist_interv_det ADD CONSTRAINT vin_asist_interv_det_fk4 FOREIGN KEY (id_inscripcion_actividad) REFERENCES vin_inscripcion_actividad(id_inscripcion_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_asist_interv_det DROP CONSTRAINT IF EXISTS vin_asist_interv_det_fk5;
ALTER TABLE vin_asist_interv_det ADD CONSTRAINT vin_asist_interv_det_fk5 FOREIGN KEY (id_interv_beneficiario) REFERENCES vin_interv_beneficiario(id_interv_beneficiario) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_asist_interv_det DROP CONSTRAINT IF EXISTS vin_asist_interv_det_fk6;
ALTER TABLE vin_asist_interv_det ADD CONSTRAINT vin_asist_interv_det_fk6 FOREIGN KEY (id_interv_personal) REFERENCES vin_interv_personal(id_interv_personal) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_curso_art_prog DROP CONSTRAINT IF EXISTS curso_art_prog_fk1;
ALTER TABLE vin_curso_art_prog ADD CONSTRAINT curso_art_prog_fk1 FOREIGN KEY (id_cursos_articulados) REFERENCES vin_cursos_articulados(id_cursos_articulados) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_cur_art_ac_soc DROP CONSTRAINT IF EXISTS cur_art_ac_soc_fk1;
ALTER TABLE vin_cur_art_ac_soc ADD CONSTRAINT cur_art_ac_soc_fk1 FOREIGN KEY (id_cursos_articulados) REFERENCES vin_cursos_articulados(id_cursos_articulados) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_cur_art_ac_soc DROP CONSTRAINT IF EXISTS cur_art_ac_soc_fk2;
ALTER TABLE vin_cur_art_ac_soc ADD CONSTRAINT cur_art_ac_soc_fk2 FOREIGN KEY (id_tipo_accion_social) REFERENCES vin_tipo_accion_social(id_tipo_accion_social) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_cur_art_dim DROP CONSTRAINT IF EXISTS cur_art_dim_fk1;
ALTER TABLE vin_cur_art_dim ADD CONSTRAINT cur_art_dim_fk1 FOREIGN KEY (id_cursos_articulados) REFERENCES vin_cursos_articulados(id_cursos_articulados) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_cur_art_dim DROP CONSTRAINT IF EXISTS cur_art_dim_fk2;
ALTER TABLE vin_cur_art_dim ADD CONSTRAINT cur_art_dim_fk2 FOREIGN KEY (id_tipo_dimension) REFERENCES vin_tipo_dimension(id_tipo_dimension) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_diagnostico_informe DROP CONSTRAINT IF EXISTS diagnostico_informe_fk1;
ALTER TABLE vin_diagnostico_informe ADD CONSTRAINT diagnostico_informe_fk1 FOREIGN KEY (id_diagnostico_institucion) REFERENCES vin_diagnostico_institucion(id_diagnostico_institucion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_diagnostico_institucion DROP CONSTRAINT IF EXISTS diagnostico_institucion_fk1;
ALTER TABLE vin_diagnostico_institucion ADD CONSTRAINT diagnostico_institucion_fk1 FOREIGN KEY (id_ruc) REFERENCES moises.persona_juridica(id_ruc) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_diagnostico_programa DROP CONSTRAINT IF EXISTS diagnostico_programa_fk1;
ALTER TABLE vin_diagnostico_programa ADD CONSTRAINT diagnostico_programa_fk1 FOREIGN KEY (id_diagnostico_institucion) REFERENCES vin_diagnostico_institucion(id_diagnostico_institucion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_ejes_lineas DROP CONSTRAINT IF EXISTS ejes_lineas_fk;
ALTER TABLE vin_ejes_lineas ADD CONSTRAINT ejes_lineas_fk FOREIGN KEY (id_parent) REFERENCES vin_ejes_lineas(id_ejes_lineas) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_grupo_actividad DROP CONSTRAINT IF EXISTS grupo_actividad_fk1;
ALTER TABLE vin_grupo_actividad ADD CONSTRAINT grupo_actividad_fk1 FOREIGN KEY (id_interv_actividad) REFERENCES vin_interv_actividad(id_interv_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_grupo_activ_alum DROP CONSTRAINT IF EXISTS grupo_activ_alum_fk1;
ALTER TABLE vin_grupo_activ_alum ADD CONSTRAINT grupo_activ_alum_fk1 FOREIGN KEY (id_grupo_actividad) REFERENCES vin_grupo_actividad(id_grupo_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_grupo_activ_alum DROP CONSTRAINT IF EXISTS grupo_activ_alum_fk2;
ALTER TABLE vin_grupo_activ_alum ADD CONSTRAINT grupo_activ_alum_fk2 FOREIGN KEY (id_inscripcion_actividad) REFERENCES vin_inscripcion_actividad(id_inscripcion_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_grupo_beneficiario DROP CONSTRAINT IF EXISTS grupo_beneficiario_fk1;
ALTER TABLE vin_grupo_beneficiario ADD CONSTRAINT grupo_beneficiario_fk1 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_inscripcion_actividad DROP CONSTRAINT IF EXISTS inscripcion_actividad_fk2;
ALTER TABLE vin_inscripcion_actividad ADD CONSTRAINT inscripcion_actividad_fk2 FOREIGN KEY (id_interv_rol_participante) REFERENCES vin_interv_rol_participante(id_interv_rol_participante) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_institucion_documento DROP CONSTRAINT IF EXISTS institucion_documento_fk1;
ALTER TABLE vin_institucion_documento ADD CONSTRAINT institucion_documento_fk1 FOREIGN KEY (id_diagnostico_institucion) REFERENCES vin_diagnostico_institucion(id_diagnostico_institucion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_institucion_documento DROP CONSTRAINT IF EXISTS vin_tipo_inst_tipo_inst_fk;
ALTER TABLE vin_institucion_documento ADD CONSTRAINT vin_tipo_inst_tipo_inst_fk FOREIGN KEY (id_tipo_instrumento) REFERENCES vin_tipo_instrumento(id_tipo_instrumento) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_institucion_necesidad DROP CONSTRAINT IF EXISTS institucion_necesidad_fk1;
ALTER TABLE vin_institucion_necesidad ADD CONSTRAINT institucion_necesidad_fk1 FOREIGN KEY (id_diagnostico_institucion) REFERENCES vin_diagnostico_institucion(id_diagnostico_institucion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_institucion_necesidad DROP CONSTRAINT IF EXISTS institucion_necesidad_fk21;
ALTER TABLE vin_institucion_necesidad ADD CONSTRAINT institucion_necesidad_fk21 FOREIGN KEY (id_ejes_lineas) REFERENCES vin_ejes_lineas(id_ejes_lineas) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_institucion_participante DROP CONSTRAINT IF EXISTS institucion_participante_fk1;
ALTER TABLE vin_institucion_participante ADD CONSTRAINT institucion_participante_fk1 FOREIGN KEY (id_diagnostico_institucion) REFERENCES vin_diagnostico_institucion(id_diagnostico_institucion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_institucion_participante DROP CONSTRAINT IF EXISTS institucion_participante_fk2;
ALTER TABLE vin_institucion_participante ADD CONSTRAINT institucion_participante_fk2 FOREIGN KEY (id_persona) REFERENCES moises.persona(id_persona) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_institucion_participante DROP CONSTRAINT IF EXISTS institucion_participante_fk3;
ALTER TABLE vin_institucion_participante ADD CONSTRAINT institucion_participante_fk3 FOREIGN KEY (id_tipo_rol) REFERENCES vin_tipo_rol(id_tipo_rol) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_inst_doc_instrumento DROP CONSTRAINT IF EXISTS inst_doc_instrumento_fk1;
ALTER TABLE vin_inst_doc_instrumento ADD CONSTRAINT inst_doc_instrumento_fk1 FOREIGN KEY (id_institucion_documento) REFERENCES vin_institucion_documento(id_institucion_documento) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_inst_doc_quiz DROP CONSTRAINT IF EXISTS inst_doc_quiz_fk1;
ALTER TABLE vin_inst_doc_quiz ADD CONSTRAINT inst_doc_quiz_fk1 FOREIGN KEY (id_institucion_documento) REFERENCES vin_institucion_documento(id_institucion_documento) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_inst_doc_quiz DROP CONSTRAINT IF EXISTS inst_doc_quiz_fk2;
ALTER TABLE vin_inst_doc_quiz ADD CONSTRAINT inst_doc_quiz_fk2 FOREIGN KEY (id_instrumento) REFERENCES lucas.instrumento_instrumento(id_instrumento) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_intervencion DROP CONSTRAINT IF EXISTS intervencion_fk2;
ALTER TABLE vin_intervencion ADD CONSTRAINT intervencion_fk2 FOREIGN KEY (id_tipo_accion_social) REFERENCES vin_tipo_accion_social(id_tipo_accion_social) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_intervencion DROP CONSTRAINT IF EXISTS intervencion_fk4;
ALTER TABLE vin_intervencion ADD CONSTRAINT intervencion_fk4 FOREIGN KEY (id_proyecto) REFERENCES vin_proyecto(id_proyecto) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_intervencion DROP CONSTRAINT IF EXISTS intervencion_fk5;
ALTER TABLE vin_intervencion ADD CONSTRAINT intervencion_fk5 FOREIGN KEY (id_diagnostico_institucion) REFERENCES vin_diagnostico_institucion(id_diagnostico_institucion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_actividad DROP CONSTRAINT IF EXISTS interv_actividad_fk1;
ALTER TABLE vin_interv_actividad ADD CONSTRAINT interv_actividad_fk1 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_beneficiario DROP CONSTRAINT IF EXISTS interv_beneficiario_fk1;
ALTER TABLE vin_interv_beneficiario ADD CONSTRAINT interv_beneficiario_fk1 FOREIGN KEY (id_persona) REFERENCES moises.persona(id_persona) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_interv_beneficiario DROP CONSTRAINT IF EXISTS interv_beneficiario_fk2;
ALTER TABLE vin_interv_beneficiario ADD CONSTRAINT interv_beneficiario_fk2 FOREIGN KEY (id_grupo_beneficiario) REFERENCES vin_grupo_beneficiario(id_grupo_beneficiario) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_interv_beneficiario DROP CONSTRAINT IF EXISTS interv_beneficiario_fk3;
ALTER TABLE vin_interv_beneficiario ADD CONSTRAINT interv_beneficiario_fk3 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_cur_art DROP CONSTRAINT IF EXISTS interv_cur_art_fk1;
ALTER TABLE vin_interv_cur_art ADD CONSTRAINT interv_cur_art_fk1 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_interv_cur_art DROP CONSTRAINT IF EXISTS interv_cur_art_fk2;
ALTER TABLE vin_interv_cur_art ADD CONSTRAINT interv_cur_art_fk2 FOREIGN KEY (id_cursos_articulados) REFERENCES vin_cursos_articulados(id_cursos_articulados) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_documento DROP CONSTRAINT IF EXISTS interv_documento_fk1;
ALTER TABLE vin_interv_documento ADD CONSTRAINT interv_documento_fk1 FOREIGN KEY (id_interv_actividad) REFERENCES vin_interv_actividad(id_interv_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_necesidad DROP CONSTRAINT IF EXISTS interv_necesidad_fk1;
ALTER TABLE vin_interv_necesidad ADD CONSTRAINT interv_necesidad_fk1 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_interv_necesidad DROP CONSTRAINT IF EXISTS interv_necesidad_fk2;
ALTER TABLE vin_interv_necesidad ADD CONSTRAINT interv_necesidad_fk2 FOREIGN KEY (id_institucion_necesidad) REFERENCES vin_institucion_necesidad(id_institucion_necesidad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_personal DROP CONSTRAINT IF EXISTS interv_personal_fk1;
ALTER TABLE vin_interv_personal ADD CONSTRAINT interv_personal_fk1 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_interv_personal DROP CONSTRAINT IF EXISTS interv_personal_fk2;
ALTER TABLE vin_interv_personal ADD CONSTRAINT interv_personal_fk2 FOREIGN KEY (id_persona) REFERENCES moises.persona(id_persona) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_interv_personal DROP CONSTRAINT IF EXISTS interv_personal_fk3;
ALTER TABLE vin_interv_personal ADD CONSTRAINT interv_personal_fk3 FOREIGN KEY (id_tipo_rol) REFERENCES vin_tipo_rol(id_tipo_rol) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_programa DROP CONSTRAINT IF EXISTS interv_programa_fk1;
ALTER TABLE vin_interv_programa ADD CONSTRAINT interv_programa_fk1 FOREIGN KEY (id_intervencion) REFERENCES vin_intervencion(id_intervencion) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_interv_rol_participante DROP CONSTRAINT IF EXISTS vin_interv_part_acti_fk;
ALTER TABLE vin_interv_rol_participante ADD CONSTRAINT vin_interv_part_acti_fk FOREIGN KEY (id_interv_actividad) REFERENCES vin_interv_actividad(id_interv_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_interv_rol_participante DROP CONSTRAINT IF EXISTS vin_tipo_rol_fk;
ALTER TABLE vin_interv_rol_participante ADD CONSTRAINT vin_tipo_rol_fk FOREIGN KEY (id_tipo_rol) REFERENCES vin_tipo_rol(id_tipo_rol) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_justificacion DROP CONSTRAINT IF EXISTS fk_asist_interv_det;
ALTER TABLE vin_justificacion ADD CONSTRAINT fk_asist_interv_det FOREIGN KEY (id_asist_interv_det) REFERENCES vin_asist_interv_det(id_asist_interv_det) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_plantilla_informe DROP CONSTRAINT IF EXISTS plantilla_informe_fk1;
ALTER TABLE vin_plantilla_informe ADD CONSTRAINT plantilla_informe_fk1 FOREIGN KEY (id_formato_plantilla) REFERENCES vin_formato_plantilla(id_formato_plantilla) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_proyecto DROP CONSTRAINT IF EXISTS proyecto_fk1;
ALTER TABLE vin_proyecto ADD CONSTRAINT proyecto_fk1 FOREIGN KEY (id_ruc) REFERENCES moises.persona_juridica(id_ruc) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_proyectos_lineas DROP CONSTRAINT IF EXISTS proyectos_lineas_fk1;
ALTER TABLE vin_proyectos_lineas ADD CONSTRAINT proyectos_lineas_fk1 FOREIGN KEY (id_tipo_proyectos) REFERENCES vin_tipo_proyectos(id_tipo_proyectos) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_proyectos_lineas DROP CONSTRAINT IF EXISTS proyectos_lineas_fk2;
ALTER TABLE vin_proyectos_lineas ADD CONSTRAINT proyectos_lineas_fk2 FOREIGN KEY (id_ejes_lineas) REFERENCES vin_ejes_lineas(id_ejes_lineas) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_proy_lin_ac_soc DROP CONSTRAINT IF EXISTS proy_lin_ac_soc_fk1;
ALTER TABLE vin_proy_lin_ac_soc ADD CONSTRAINT proy_lin_ac_soc_fk1 FOREIGN KEY (id_proyectos_lineas) REFERENCES vin_proyectos_lineas(id_proyectos_lineas) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_proy_lin_ac_soc DROP CONSTRAINT IF EXISTS proy_lin_ac_soc_fk2;
ALTER TABLE vin_proy_lin_ac_soc ADD CONSTRAINT proy_lin_ac_soc_fk2 FOREIGN KEY (id_tipo_accion_social) REFERENCES vin_tipo_accion_social(id_tipo_accion_social) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_proy_lin_ejes DROP CONSTRAINT IF EXISTS proy_lin_ejes_fk1;
ALTER TABLE vin_proy_lin_ejes ADD CONSTRAINT proy_lin_ejes_fk1 FOREIGN KEY (id_proyectos_lineas) REFERENCES vin_proyectos_lineas(id_proyectos_lineas) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_proy_lin_ejes DROP CONSTRAINT IF EXISTS proy_lin_ejes_fk3;
ALTER TABLE vin_proy_lin_ejes ADD CONSTRAINT proy_lin_ejes_fk3 FOREIGN KEY (id_ejes_lineas) REFERENCES vin_ejes_lineas(id_ejes_lineas) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_proy_lin_prog DROP CONSTRAINT IF EXISTS proy_lin_prog_fk1;
ALTER TABLE vin_proy_lin_prog ADD CONSTRAINT proy_lin_prog_fk1 FOREIGN KEY (id_proyectos_lineas) REFERENCES vin_proyectos_lineas(id_proyectos_lineas) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_relacion_grupos DROP CONSTRAINT IF EXISTS relacion_grupos_fk1;
ALTER TABLE vin_relacion_grupos ADD CONSTRAINT relacion_grupos_fk1 FOREIGN KEY (id_grupo_actividad) REFERENCES vin_grupo_actividad(id_grupo_actividad) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE vin_relacion_grupos DROP CONSTRAINT IF EXISTS relacion_grupos_fk2;
ALTER TABLE vin_relacion_grupos ADD CONSTRAINT relacion_grupos_fk2 FOREIGN KEY (id_grupo_beneficiario) REFERENCES vin_grupo_beneficiario(id_grupo_beneficiario) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_secciones_plantilla DROP CONSTRAINT IF EXISTS secciones_plantilla_fk1;
ALTER TABLE vin_secciones_plantilla ADD CONSTRAINT secciones_plantilla_fk1 FOREIGN KEY (id_plantilla_informe) REFERENCES vin_plantilla_informe(id_plantilla_informe) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vin_tipo_institucion DROP CONSTRAINT IF EXISTS tipo_institucion_fk;
ALTER TABLE vin_tipo_institucion ADD CONSTRAINT tipo_institucion_fk FOREIGN KEY (id_ubigeo) REFERENCES moises.ubigueo(id_ubigeo) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
