-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

FUNCTION        FC_DEPTO_CLIENTE(P_ID_CLIENTE NUMBER) RETURN VARCHAR2 AS
  l_depto VARCHAR2(10);
  l_contar number;
BEGIN
        
  select count(*) into l_contar
  FROM APS_PLANILLA A
  WHERE A.ID_PERSONA = P_ID_CLIENTE  AND
  A.ID_ANHO||lpad(A.id_mes,2,'00') IN (  
     SELECT  max(B.ID_ANHO||lpad(B.id_mes,2,'00'))
     FROM APS_PLANILLA B
     WHERE B.ID_PERSONA = P_ID_CLIENTE
  );
  
  if l_contar> 1 then
    SELECT x.ID_DEPTO into  l_depto
    FROM (
      select A.ID_DEPTO
          FROM APS_PLANILLA A
          WHERE A.ID_PERSONA = P_ID_CLIENTE  AND
          A.ID_ANHO||lpad(A.id_mes,2,'00') IN (  
             SELECT  max(B.ID_ANHO||lpad(B.id_mes,2,'00'))
             FROM APS_PLANILLA B
             WHERE B.ID_PERSONA =P_ID_CLIENTE
          )
        order by A.id_contrato desc
    ) x
    WHERE ROWNUM = 1;
  else
    if l_contar=1 then
    
      select A.ID_DEPTO into  l_depto
      FROM APS_PLANILLA A
      WHERE A.ID_PERSONA = 18940  AND
      A.ID_ANHO||lpad(A.id_mes,2,'00') IN (  
         SELECT  max(B.ID_ANHO||lpad(B.id_mes,2,'00'))
         FROM APS_PLANILLA B
         WHERE B.ID_PERSONA = P_ID_CLIENTE
      );
    end if;
  end if;
  
  return l_depto;
          
END;

