-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

function FC_PSTO_TIPOCONTRATO(P_ID_CARGO_PROCESO NUMBER) RETURN VARCHAR2
IS
l_dato varchar2(3000):='';
l_nombre varchar2(50);
p_conta int;

CURSOR CUR is
SELECT COALESCE(b.NOMBRE_CORTO,b.NOMBRE) 
FROM PSTO_PLLA_CARGO_PROCESO_TIPCON A,TIPO_CONTRATO B
WHERE A.ID_TIPOCONTRATO = B.ID_TIPOCONTRATO
AND A.ID_CARGO_PROCESO=P_ID_CARGO_PROCESO
ORDER BY B.ID_TIPOCONTRATO;


BEGIN
    p_conta:=1;
    open CUR;
        fetch CUR into l_nombre;
        while CUR%found loop
            if p_conta = 1 then
                l_dato := l_nombre;
            else
                l_dato := l_dato||'|'||l_nombre;
            end if;
                    
            fetch CUR into l_nombre;
            p_conta:=p_conta+1;
        end loop;
	close CUR;	
	
	RETURN(l_dato);
END;

