-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

FUNCTION        FC_TIPO_ESTATUS(P_ID INT) RETURN VARCHAR2 AS
L_NOMBRE VARCHAR2(100);
BEGIN

        SELECT NOMBRE INTO L_NOMBRE
        FROM TIPO_ESTATUS 
        WHERE ID_TIPOESTATUS = P_ID;

        RETURN(L_NOMBRE);

END;

