-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_caja,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_caja_sp_eliminar_detraccion_all (P_ID_DETRACCION bigint) AS $body$
DECLARE

        L_ID_VOUCHER integer;
        L_ID_TIPOORIGEN bigint;
        L_ID_ORIGEN bigint;

BEGIN
        SELECT ID_VOUCHER,ID_TIPOORIGEN INTO STRICT L_ID_VOUCHER,L_ID_TIPOORIGEN 
        FROM CAJA_DETRACCION
        WHERE ID_DETRACCION = P_ID_DETRACCION;

        
        DELETE FROM CONTA_ASIENTO
        WHERE ID_TIPOORIGEN = L_ID_TIPOORIGEN
        AND ID_ORIGEN = P_ID_DETRACCION
        AND VOUCHER = L_ID_VOUCHER;

        DELETE FROM CAJA_DETRACCION_COMPRA where ID_DETRACCION = P_ID_DETRACCION;
        DELETE FROM CAJA_DETRACCION_VENTA where ID_DETRACCION = P_ID_DETRACCION;
        DELETE FROM CAJA_DETRACCION where ID_DETRACCION = P_ID_DETRACCION;

    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_caja_sp_eliminar_detraccion_all (P_ID_DETRACCION bigint) FROM PUBLIC;
