-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,utils,public;




CREATE OR REPLACE FUNCTION eliseo.utils_convert_to_char (P_EXPR TSTZ , P_PRECISION bigint DEFAULT NULL, P_SCALE bigint DEFAULT 0, P_STYLE bigint DEFAULT NULL) RETURNS char AS $body$
BEGIN
   RETURN utils_convert_to_char(CAST(P_EXPR AS TS),P_PRECISION,P_SCALE,P_STYLE); --REMOVE TZ
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.utils_convert_to_char (P_EXPR TSTZ , P_PRECISION bigint DEFAULT NULL, P_SCALE bigint DEFAULT 0, P_STYLE bigint DEFAULT NULL) FROM PUBLIC;
