-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_mat_matriculados (id_alumno_contrato, id_persona, id_programa_estudio, id_tipo_contrato, id_semestre_programa, id_planpago_semestre, id_nivel_ensenanza, id_plan_programa, id_matricula_detalle, id_comprobante, estado, total_debito, total_credito, total, matricula, mensual, contado, matricula1cuota, tipo_alumno, id_alumno_contrato_clon, id_alumno_contrato_asociado, id_entidad, id_depto, codigo, nombre, paterno, materno, nombre_facultad, nombre_escuela, cuotas, semestre, id_semestre, id_modo_contrato, id_modalidad_estudio, id_sede, plan_pago, id_resid_tipo_habitacion, dias_residencia, id_facultad, id_escuela, id_sedearea, num_documento, fac_sigla, nombre_corto) AS select a.id_alumno_contrato,
a.id_persona,
d.id_programa_estudio,
a.id_tipo_contrato,
a.id_semestre_programa,
a.id_planpago_semestre,
a.id_nivel_ensenanza,
a.id_plan_programa,
a.id_matricula_detalle,
a.id_comprobante,
a.estado,
a.total_debito,
a.total_credito,
a.total,
a.matricula,
a.mensual,
a.contado,
a.matricula1cuota,
a.tipo_alumno,
a.id_alumno_contrato_clon,
a.id_alumno_contrato_asociado,
sa.id_entidad,
sa.id_depto,
c.codigo,
b.nombre,
b.paterno, 
b.materno,
ps.NOMBRE_FACULTAD,
ps.NOMBRE_ESCUELA,
pp.cuotas,
se.semestre,
d.id_semestre,
md.Id_Modo_Contrato,
ps.id_modalidad_estudio,
sa.id_sede,
pp.nombre as plan_pago,
a.ID_RESID_TIPO_HABITACION,
a.DIAS_RESIDENCIA,
ps.ID_FACULTAD,
ps.ID_ESCUELA,
sa.id_sedearea,
'' as num_documento,
ps.FAC_SIGLA,
ps.NOMBRE_CORTO
FROM DAVID.ACAD_ALUMNO_CONTRATO a, 
moises.persona b,
moises.persona_natural_alumno c,
david.acad_semestre_programa d ,
david.Acad_Matricula_Detalle md,
david.vw_acad_programa_estudio ps,
mat_planpago_semestre pps,
mat_planpago pp,
org_sede_area sa,
david.acad_semestre se
where a.id_persona=b.id_persona
and b.id_persona=c.id_persona
and a.id_semestre_programa=d.id_semestre_programa
and a.Id_Matricula_Detalle=md.Id_Matricula_Detalle
and ps.id_programa_estudio=d.id_programa_estudio
and pps.ID_PLANPAGO_SEMESTRE=a.ID_PLANPAGO_SEMESTRE
and pp.ID_PLANPAGO=pps.ID_PLANPAGO
and sa.id_sedearea=ps.id_sedearea
and d.id_semestre=se.id_semestre;

