-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE eliseo.spc_sehs_dptos ( p_id_entidad integer, p_id_anho integer, OUT CURSOR REFCURSOR ) AS $body$
DECLARE


    l_ingresos decimal(38,2);


BEGIN
    DELETE FROM TT_TABLE_AUX;


    OPEN CURSOR FOR
    SELECT
                    to_char(FEC_ASIENTO,'yyyy/mm/dd') AS FECHA,
                    ID_MES,
                    CODIGO,
                    FC_SEHS_TMP(ID_DEPTO) AS ENTIDAD,
                    ID_DEPTO,
                    COMENTARIO as COMENTARIO,
                    COS_VALOR as VALOR,
                    CASE SIGN(COS_VALOR) WHEN 1 THEN COS_VALOR ELSE 0 END AS DEBE,
                    CASE SIGN(COS_VALOR) WHEN 1 THEN 0 ELSE COS_VALOR END AS HABER,
                    CASE SIGN(COS_VALOR) WHEN 1 THEN 'D' ELSE 'C' END AS DC
                from VW_CONTA_DIARIO
                where ID_ENTIDAD = p_id_entidad
                and ID_ANHO = p_id_anho
                and (
                  id_cuentaaasi in (
                    SELECT id_cuentaaasi from CONTA_CTA_DENOMINACIONAL
                      where id_cuentaaasi like '3%' 
                      --and es_grupo = 0
                      and ES_ACREEDORA = 0
                  )
                  or 
                  id_cuentaaasi in (
                    select id_cuentaaasi from CONTA_CTA_DENOMINACIONAL
                      where id_cuentaaasi like '4%' 
                      and es_grupo = 0
                      and ES_ACREEDORA = 0
                  )
                  or (id_cuentaaasi in (
                    select id_cuentaaasi from CONTA_CTA_DENOMINACIONAL
                      where id_cuentaaasi like '6%' 
                      and es_grupo = 0
                      and ES_ACREEDORA = 0
                  )  
                  and not ID_TIPOASIENTO in ('IN','EA')
                  )
                ) 
;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.spc_sehs_dptos ( p_id_entidad integer, p_id_anho integer, OUT CURSOR REFCURSOR ) FROM PUBLIC;

