-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = genesis,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_persona_documento (id_persona, id_tipodocumento, num_documento, tipodocumento, img_documento, documento_url, es_activo) AS select  pd.id_persona ,
        pd.id_tipodocumento, 
        pd.num_documento, 
        td.siglas tipodocumento, 
        pd.img_documento, 
        pd.documento_url, 
        pd.es_activo
FROM genesis.persona_documento pd 
inner join moises.tipo_documento td on pd.id_tipodocumento = td.id_tipodocumento;

