-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.fc_codigo_articulo_codigo (P_ID_ARTICULO bigint,P_ID_ANHO bigint) RETURNS varchar AS $body$
DECLARE

    L_CODIGO varchar(20);

BEGIN 
    SELECT 
            MAX(CODIGO) INTO STRICT L_CODIGO
    FROM INVENTARIO_ALMACEN_ARTICULO
    WHERE ID_ARTICULO = P_ID_ARTICULO
    AND ID_ANHO = P_ID_ANHO;
    RETURN(L_CODIGO);
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.fc_codigo_articulo_codigo (P_ID_ARTICULO bigint,P_ID_ANHO bigint) FROM PUBLIC;

