-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.fc_gth_validar_ver_boleta (P_ID_GESTION bigint,P_ID_PERSONA bigint,P_ID_CONTRATO bigint) RETURNS bigint AS $body$
DECLARE

l_dato integer:=0;
l_contar integer:=0;
l_id_gestion bigint;
l_id_proceso bigint;

BEGIN

  IF  coalesce(P_ID_GESTION::text, '') = '' THEN
    l_dato:=0;
  ELSE

    SELECT COUNT(*) INTO STRICT l_contar FROM APS_PLANILLA_BOLETA A, APS_PLANILLA_BOLETA_PROCESO B
    WHERE A.ID_GESTION=B.ID_GESTION
    AND A.ID_PERSONA = P_ID_PERSONA
    AND A.ID_CONTRATO  = P_ID_CONTRATO
    AND A.ID_GESTION   = P_ID_GESTION
    AND B.ID_PROCESO = 2;

    /*1	Firma
    2	Aviso Enviado
    3	Revisado
    4	Descargado*/
    
    if l_contar > 0 then
    
      SELECT count(*) INTO STRICT l_contar FROM APS_PLANILLA_BOLETA 
      WHERE ID_PERSONA = P_ID_PERSONA
      AND ID_CONTRATO = P_ID_CONTRATO
      AND ID_GESTION<P_ID_GESTION;

      IF l_contar>0 THEN
  
        SELECT coalesce(max(ID_GESTION),0) INTO STRICT l_id_gestion FROM APS_PLANILLA_BOLETA 
        WHERE ID_PERSONA = P_ID_PERSONA
        AND ID_CONTRATO = P_ID_CONTRATO
        AND ID_GESTION<P_ID_GESTION;

        SELECT COUNT(*) INTO STRICT l_contar FROM APS_PLANILLA_BOLETA_PROCESO   WHERE ID_GESTION =l_id_gestion  AND ID_PROCESO = 3;

        IF l_contar=1 THEN
          l_dato:=1;
        ELSE
          SELECT count(*) INTO STRICT l_contar FROM APS_PLANILLA_BOLETA
          WHERE ID_PERSONA = P_ID_PERSONA
          AND ID_CONTRATO = P_ID_CONTRATO;

          if l_contar=1 then
             l_dato:=1;
          else
            l_dato:=0;
          end if;

        END IF;

      ELSE
        SELECT COUNT(*) INTO STRICT l_contar FROM APS_PLANILLA_BOLETA_PROCESO   WHERE ID_GESTION =P_ID_GESTION  AND ID_PROCESO = 2;

        IF l_contar=1 THEN
          l_dato:=1;
        ELSE
          l_dato:=0;
        END IF;
      END IF;
     end if;
  END IF;

  
	RETURN(l_dato);
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.fc_gth_validar_ver_boleta (P_ID_GESTION bigint,P_ID_PERSONA bigint,P_ID_CONTRATO bigint) FROM PUBLIC;

