-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.fc_ruc_proveedor (P_ID_PROVEEDOR bigint) RETURNS varchar AS $body$
DECLARE

  l_datos varchar(30);
 datos CURSOR FOR
                SELECT
                ID_RUC AS RUC
                FROM MOISES.PERSONA_JURIDICA
                WHERE ID_PERSONA=P_ID_PROVEEDOR;
datos2 CURSOR FOR
                SELECT
                NUM_DOCUMENTO AS RUC
                FROM MOISES.PERSONA_DOCUMENTO
                WHERE ID_PERSONA=P_ID_PROVEEDOR
                 and ID_TIPODOCUMENTO = 6;


BEGIN
       open datos;
       fetch datos into l_datos;
       if not datos%found then
            open datos2;
            fetch datos2 into l_datos;
            if not datos2%found then
                l_datos := ' ';
            end if;
            close datos2;
       end if;
       close datos;
       RETURN( l_datos );
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.fc_ruc_proveedor (P_ID_PROVEEDOR bigint) FROM PUBLIC;

