-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.fc_sigla_cta_bancaria (P_ID_CTABANCARIA bigint) RETURNS varchar AS $body$
DECLARE

        L_SIGLA varchar(255);

BEGIN
            SELECT coalesce(A.SIGLA,'') INTO STRICT L_SIGLA
            FROM CAJA_ENTIDAD_FINANCIERA A JOIN CAJA_CUENTA_BANCARIA B ON A.ID_BANCO = B.ID_BANCO
            WHERE B.ID_CTABANCARIA = P_ID_CTABANCARIA;

            RETURN(L_SIGLA);
    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.fc_sigla_cta_bancaria (P_ID_CTABANCARIA bigint) FROM PUBLIC;

