-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = genesis,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_resp_financiero_id ON responsable_financiero CASCADE;
CREATE OR REPLACE FUNCTION genesis.trigger_fct_tr_resp_financiero_id() RETURNS trigger AS $BODY$
BEGIN
		  select nextval('genesis.sq_resp_financiero_id')
		  into STRICT NEW.id_responsable_financiero
		;
		RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION genesis.trigger_fct_tr_resp_financiero_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_resp_financiero_id ON responsable_financiero;
CREATE TRIGGER tr_resp_financiero_id
	BEFORE INSERT ON responsable_financiero FOR EACH ROW
	EXECUTE PROCEDURE genesis.trigger_fct_tr_resp_financiero_id();

