-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = enoc,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_rol_vacacional (id_periodo_vac_trab, id_periodo_vac, id_trabajador, periodo_ini, periodo_fin, periodo_ini_trab, periodo_fin_trab, total_dias, total_dias_efect, id_estado_vac_trab, comentario, id_user_apru, fecha_apru, dias_anho, id_entidad, nombre, min_dias_periodo1, min_dias_periodo2, id_estado_periodo_vac, anho_inicio, id_rol_vacacion, fecha_ini, fecha_fin, dias, dias_efect, condicion, id_parent, id_estado_rol_vac, fecha_registra, id_user_reg, id_tipo_suspension, confirmacion_salida, fecha_confirmacion_salida, user_confirmacion_salida, confirmacion_retorno, fecha_confirmacion_retorno, user_confirmacion_retorno, motivo_repro, id_tipo_rol_vac, id_sol_vac_adel_det, salida_url) AS select
a.ID_PERIODO_VAC_TRAB,
a.ID_PERIODO_VAC,
a.ID_TRABAJADOR,
a.PERIODO_INI,
a.PERIODO_FIN,
a.PERIODO_INI_TRAB,
a.PERIODO_FIN_TRAB,
a.TOTAL_DIAS,
a.TOTAL_DIAS_EFECT,
a.ID_ESTADO_VAC_TRAB,
a.COMENTARIO,
a.ID_USER_APRU,
a.FECHA_APRU,
a.DIAS_ANHO,
a.ID_ENTIDAD,
a.NOMBRE,
a.MIN_DIAS_PERIODO1,
a.MIN_DIAS_PERIODO2,
a.ID_ESTADO_PERIODO_VAC,
a.ANHO_INICIO,
b.ID_ROL_VACACION,
b.FECHA_INI,
b.FECHA_FIN,
b.DIAS,
b.DIAS_EFECT,
b.CONDICION,
b.ID_PARENT,
b.ID_ESTADO_ROL_VAC,
b.FECHA_REGISTRA,
b.ID_USER_REG,
b.ID_TIPO_SUSPENSION,
b.CONFIRMACION_SALIDA,
b.FECHA_CONFIRMACION_SALIDA,
b.USER_CONFIRMACION_SALIDA,
b.CONFIRMACION_RETORNO,
b.FECHA_CONFIRMACION_RETORNO,
b.USER_CONFIRMACION_RETORNO,
b.MOTIVO_REPRO,
b.ID_TIPO_ROL_VAC,
b.ID_SOL_VAC_ADEL_DET,
b.SALIDA_URL
FROM ENOC.VW_PERIODO_VAC_TRAB a,
ENOC.PLLA_ROL_VACACIONAL b
where a.ID_PERIODO_VAC_TRAB=b.ID_PERIODO_VAC_TRAB;

