-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = enoc,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_adicional_grupo (id_adicional, id_persona, id_trabajador, id_contrato, apellidonombre, num_documento, siglas, area, puesto, id_anho, mes, id_mes, id_depto, ccosto, id_area, id_entidad, id_depto_padre, importe, vigencia, id_condicion_laboral, id_situacion_trabajador, id_tipo_control_personal, id_concepto_planilla, id_estado_adicional, id_depto_t, ccosto_t, concepto_adicional, id_tipo_tiempo_trabajo) AS select
  a.id_adicional,
t.id_persona,
d.id_trabajador,
t.id_contrato,
t.apellidonombre,
t.num_documento,
td.siglas,
saa.nombre as area,
pp.puesto,
a.id_anho,
m.nombre as mes,
a.id_mes,
sa.id_depto,
sa.ccosto,
saa.id_area,
t.id_entidad,
saa.id_depto_padre,
d.importe,
d.vigencia,
t.id_condicion_laboral,
t.id_situacion_trabajador,
t.id_tipo_control_personal,
a.id_concepto_planilla,
a.id_estado_adicional,
saa.id_depto as id_depto_t,
saa.ccosto as ccosto_t,
ca.nombre as concepto_adicional,
t.id_tipo_tiempo_trabajo
FROM enoc.PLLA_ADICIONAL a, 
enoc.PLLA_ADICIONAL_PERSONA d, 
enoc.vw_trabajador t, 
ELISEO.VW_SEDE_AREA sa, 
eliseo.conta_mes m,
moises.tipo_documento td,
enoc.vw_perfil_puesto pp,
ELISEO.VW_SEDE_AREA saa,
enoc.plla_concepto_adicional ca
where a.id_adicional=d.id_adicional
and d.id_trabajador=t.id_trabajador
and d.id_sedearea=sa.id_sedearea
and a.id_mes=m.id_mes
and t.ID_TIPODOCUMENTO= td.ID_TIPODOCUMENTO
and t.id_perfil_puesto=pp.id_perfil_puesto
and t.id_sedearea=saa.id_sedearea
and a.id_concepto_adicional=ca.id_concepto_adicional;

