-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_prof,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_prof_sp_resi_lavanderia (P_ID_PROFORMA bigint,P_ID_CRITERIO_SEMESTRE bigint,P_ERROR OUT bigint,P_MSGERROR out text) AS $body$
DECLARE

    l_items bigint;
    l_contar bigint;
    l_error bigint:=0;
    l_msgerror varchar(200):='';
    l_id_semestre_programa bigint;
    l_id_persona bigint;

    l_id_criterio	bigint;
    l_importe	decimal(10,2);
    l_tipo_proceso	varchar(2);
    l_tipo_valor	varchar(2);
    l_nombre varchar(150);
    l_dc varchar(1);
    l_creditos decimal(10,2);
    l_id_postulante bigint;
    l_id_resis_tipo_habitacion bigint;
    l_desde timestamp(0);
    l_hasta timestamp(0);
    l_dias decimal(10,2):=112;

BEGIN
  
    
    SELECT B.ID_PERSONA, A.ID_SEMESTRE_PROGRAMA,B.ID_POSTULANTE,coalesce(A.ID_RESID_TIPO_HABITACION,0),coalesce(A.DIAS_RESIDENCIA,0)
    INTO STRICT l_id_persona,l_id_semestre_programa,l_id_postulante,l_id_resis_tipo_habitacion,l_dias
    FROM ELISEO.PRO_PROFORMA A, PRO_POSTULANTE B
    WHERE A.ID_POSTULANTE=B.ID_POSTULANTE
    AND A.ID_PROFORMA = P_ID_PROFORMA;

    if l_id_resis_tipo_habitacion>0 then
    
      SELECT 
        ID_CRITERIO,
        IMPORTE,
        TIPO_PROCESO,
        TIPO_VALOR,
        DC,
        NOMBRE
        INTO STRICT
        l_id_criterio,
        l_importe,
        l_tipo_proceso,
        l_tipo_valor,
        l_dc,
        l_nombre
      FROM VW_MAT_CRITERIO_SEMESTRE
      WHERE ID_CRITERIO_SEMESTRE=P_ID_CRITERIO_SEMESTRE;

      SELECT COUNT(*) INTO STRICT l_contar FROM DAVID.RESIDENCIA_CARACTERISTICA A, DAVID.TIPO_CARACTERISTICA_RESIDENCIA B 
      WHERE A.ID_TIPO_CARACT_RESIDENCIA=B.ID_TIPO_CARACT_RESIDENCIA
      AND A.ID_RESID_TIPO_HABITACION=l_id_resis_tipo_habitacion  and a.estado='1'
      AND B.CODIGO='7';

      IF l_contar>0 THEN
      
        SELECT COALESCE(MAX(ITEM),0)+1  INTO STRICT l_items FROM PRO_CONCEPTO_ASIGN_ALUM
        WHERE ID_PROFORMA=P_ID_PROFORMA;

        
        insert into PRO_CONCEPTO_ASIGN_ALUM(
            ID_PROFORMA,
            ID_CRITERIO_SEMESTRE,
            ITEM,
            ID_SEMESTRE_PROGRAMA,
            DESCRIPCION,
            DC,
            CANTIDAD,
            UNITARIO,
            TOTAL,
            TIPO_VALOR
            )VALUES (
            P_ID_PROFORMA,
            P_ID_CRITERIO_SEMESTRE,
            l_items,
            l_id_semestre_programa,
            l_nombre||' ' ||l_dias::text||' dias' ,
            l_dc,
            l_dias,
            l_importe,
            l_importe*l_dias,
            l_tipo_valor
            );
      end if;
    end if;
--     <<salida>>
    P_ERROR:=l_error;
    P_MSGERROR:= l_msgerror;
  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_prof_sp_resi_lavanderia (P_ID_PROFORMA bigint,P_ID_CRITERIO_SEMESTRE bigint,P_ERROR OUT bigint,P_MSGERROR out text) FROM PUBLIC;
