-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.fc_caja_detraccion_fecha (P_ID_COMPRA bigint) RETURNS varchar AS $body$
DECLARE

L_NOMBRE varchar(100);

BEGIN

/*
	SELECT MAX(coalesce(to_char(FECHA,'dd/mm/yyyy'),'')) INTO L_NOMBRE FROM CAJA_DETRACCION a, CAJA_DETRACCION_COMPRA b
WHERE a.ID_DETRACCION = b.ID_DETRACCION
AND b.ID_COMPRA = P_ID_COMPRA;
*/
	SELECT MAX(coalesce(to_char(FECHA_EMISION,'dd/mm/yyyy'),'')) INTO STRICT L_NOMBRE FROM CAJA_DETRACCION a, CAJA_DETRACCION_COMPRA b
WHERE a.ID_DETRACCION = b.ID_DETRACCION
AND b.ID_COMPRA = P_ID_COMPRA;

        
        RETURN(L_NOMBRE);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.fc_caja_detraccion_fecha (P_ID_COMPRA bigint) FROM PUBLIC;

