-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.fc_obtener_email_p (P_ID_PERSONA bigint) RETURNS varchar AS $body$
DECLARE

l_dato varchar(100):='';
l_contar integer:=0;
l_id_virtual bigint;


BEGIN

   select COUNT(*) INTO STRICT l_contar from MOISES.persona_virtual WHERE ID_PERSONA=P_ID_PERSONA and ID_TIPOVIRTUAL=1 and GTH=1;

   IF l_contar>0 THEN
     IF l_contar=1 THEN
      select DIRECCION INTO STRICT l_dato from MOISES.persona_virtual WHERE ID_PERSONA=P_ID_PERSONA and ID_TIPOVIRTUAL=1 and GTH=1;
     ELSE
      select max(id_virtual) into STRICT l_id_virtual from MOISES.persona_virtual WHERE ID_PERSONA=P_ID_PERSONA and ID_TIPOVIRTUAL=1 and GTH=1;
      select DIRECCION INTO STRICT l_dato from MOISES.persona_virtual WHERE ID_PERSONA=P_ID_PERSONA and id_virtual=l_id_virtual and ID_TIPOVIRTUAL=1 and GTH=1;
     END IF;

   ELSE
   	select COUNT(*) INTO STRICT l_contar from MOISES.PERSONA_VIRTUAL WHERE ID_PERSONA=P_ID_PERSONA and ID_TIPOVIRTUAL=1;
  	IF l_contar > 0 THEN
  		select max(id_virtual) into STRICT l_id_virtual from MOISES.persona_virtual WHERE ID_PERSONA=P_ID_PERSONA and ID_TIPOVIRTUAL=1;
  		select DIRECCION INTO STRICT l_dato from MOISES.persona_virtual WHERE ID_PERSONA=P_ID_PERSONA and id_virtual=l_id_virtual and ID_TIPOVIRTUAL=1;	
  	END IF;
   END IF;

	RETURN(l_dato);
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.fc_obtener_email_p (P_ID_PERSONA bigint) FROM PUBLIC;

