-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.fc_saldo_fondo_asignado (P_ENTIDAD integer,P_ANHO integer,P_MES integer, P_FONDO integer) RETURNS bigint AS $body$
DECLARE

S_SALDO decimal(10,2):=0.00;
P_EMPRESA numeric(38):=207;
L_COUNT numeric(38):=0;



BEGIN
	IF (P_ANHO <=2020) THEN
	
		SELECT ID_EMPRESA INTO STRICT P_EMPRESA FROM CONTA_ENTIDAD ce
		WHERE ID_ENTIDAD = P_ENTIDAD;
		IF (P_EMPRESA = 207) THEN
			SELECT -1*coalesce((sum(VCD.COS_VALOR)),0) INTO STRICT S_SALDO
		   	FROM VW_CONTA_DIARIO_ALL VCD
		    INNER JOIN(SELECT ID_DEPTO FROM DEPTO_CHILD
		    WHERE ID_ENTIDAD= P_ENTIDAD AND ID_PARENT ='0D') DC 
			ON VCD.ID_DEPTO =DC.ID_DEPTO
			WHERE ID_ENTIDAD= P_ENTIDAD AND ID_ANHO=P_ANHO
			AND ID_MES <= P_MES
		    AND ID_FONDO = P_FONDO 
		    AND NOT ID_CUENTAAASI IN ('2130605','2136006');
	
		ELSE
			SELECT -1*coalesce((sum(VCD.COS_VALOR)),0) INTO STRICT S_SALDO
		   	FROM VW_CONTA_DIARIO_ALL VCD
		    INNER JOIN(SELECT ID_DEPTO FROM DEPTO_CHILD
		    WHERE ID_ENTIDAD= P_ENTIDAD AND ID_PARENT ='0D') DC 
			ON VCD.ID_DEPTO =DC.ID_DEPTO 
			WHERE ID_ENTIDAD= P_ENTIDAD AND ID_ANHO=P_ANHO
			AND ID_MES <= P_MES
		    AND ID_FONDO = P_FONDO;
		    --AND NOT ID_CUENTAAASI IN ('2130605','2136006');
	
		END IF;
	
	ELSE
		SELECT count(1) INTO STRICT L_COUNT
		FROM VW_CONTA_ENTIDAD_CATEGORIA vcec 
		WHERE vcec.ID_CATEGORIA = 1 AND vcec.ID_ENTIDAD = P_ENTIDAD;
		IF L_COUNT > 0 THEN
			SELECT SUM(FA.SALDO) AS SALDO INTO STRICT S_SALDO FROM (
	
	                SELECT SUM(SALDO) AS SALDO FROM (SELECT vcda.ID_CUENTAAASI, SUM(vcda.COS_VALOR) AS SALDO
	                FROM VW_CONTA_DIARIO_ALL vcda 
	                WHERE vcda.ID_CUENTAAASI = 2317001
	                AND vcda.ID_TIPOASIENTO = 'BB'
	                AND ID_FONDO = P_FONDO
	                AND vcda.ID_MES <= P_MES AND vcda.ID_ANHO = P_ANHO
	                AND vcda.ID_ENTIDAD = P_ENTIDAD
	                GROUP BY vcda.ID_CUENTAAASI) alias3 
	                
	                
UNION ALL

	
	                SELECT sum(SALDO) AS SALDO FROM (
	                SELECT vcda.ID_CUENTAAASI, SUM(vcda.COS_VALOR) AS SALDO
	                FROM VW_CONTA_DIARIO_ALL vcda 
	                WHERE (regexp_match(vcda.ID_CUENTAAASI, '^318|^319','n') IS NOT NULL AND (regexp_match(vcda.ID_CUENTAAASI, '^318|^319','n'))::text <> '')
	                --AND vcda.ID_TIPOASIENTO = 'BB'
	                AND ID_FONDO = P_FONDO
	                AND vcda.ID_DEPTO NOT IN (0002,0001)
	                AND vcda.ID_MES <= P_MES AND vcda.ID_ANHO = P_ANHO
	                AND vcda.ID_ENTIDAD = P_ENTIDAD 
	                GROUP BY vcda.ID_CUENTAAASI) alias11 
	                
	                
UNION ALL

	                
	                SELECT sum(SALDO) AS SALDO FROM (
	                SELECT vcda.ID_CUENTAAASI, SUM(vcda.COS_VALOR) AS SALDO
	                FROM VW_CONTA_DIARIO_ALL vcda 
	                WHERE vcda.ID_CUENTAAASI IN (6400001,6400005, 6100001, 6300001)
	                --AND vcda.ID_TIPOASIENTO = 'BB'
	                AND ID_FONDO = P_FONDO
	                AND vcda.ID_MES <= P_MES AND vcda.ID_ANHO = P_ANHO
	                AND vcda.ID_ENTIDAD = P_ENTIDAD 
	                GROUP BY vcda.ID_CUENTAAASI) alias15 
	                
UNION all

	                SELECT sum(saldo) FROM (
	                SELECT vcda.ID_CUENTAAASI, SUM(vcda.COS_VALOR) AS SALDO
	                FROM VW_CONTA_DIARIO_ALL vcda 
	                WHERE (regexp_match(vcda.ID_CUENTAAASI, '^411|^412|^414|^419','n') IS NOT NULL AND (regexp_match(vcda.ID_CUENTAAASI, '^411|^412|^414|^419','n'))::text <> '')
	                --AND vcda.ID_TIPOASIENTO = 'BB'
	                AND ID_FONDO = P_FONDO
	                AND vcda.ID_MES <= P_MES AND vcda.ID_ANHO = P_ANHO
	                AND vcda.ID_ENTIDAD = P_ENTIDAD 
	                GROUP BY vcda.ID_CUENTAAASI) alias22 
	                
UNION all

	                SELECT sum(saldo) FROM (
	                SELECT vcda.ID_CUENTAAASI, SUM(vcda.COS_VALOR) AS SALDO
	                FROM VW_CONTA_DIARIO_ALL vcda 
	                WHERE vcda.ID_CUENTAAASI LIKE '421%'
	                --AND vcda.ID_TIPOASIENTO = 'BB'
	                AND ID_FONDO = P_FONDO
	                AND vcda.ID_MES <= P_MES AND vcda.ID_ANHO = P_ANHO
	                AND vcda.ID_ENTIDAD = P_ENTIDAD
	                GROUP BY vcda.ID_CUENTAAASI) alias25 
	                
	                ) FA;
	    END IF;
	
	
	END IF;

	RETURN(S_SALDO);


END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.fc_saldo_fondo_asignado (P_ENTIDAD integer,P_ANHO integer,P_MES integer, P_FONDO integer) FROM PUBLIC;

