-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = eliseo,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE FUNCTION eliseo.sexo ( v_id_persona integer) RETURNS varchar AS $body$
DECLARE

	p_sexo	  varchar(800);


BEGIN

    select CASE WHEN sexo=1 THEN  'M' WHEN sexo=2 THEN  'F'  ELSE '-' END   into STRICT p_sexo
    from moises.persona_natural
    where id_persona=v_id_persona;

return p_sexo;

END;



/*
select *
from moises.persona_natural
where id_persona = 14002
;
*/
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION eliseo.sexo ( v_id_persona integer) FROM PUBLIC;

