-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_purchases,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_purchases_sp_compra_detalle (P_ID_PCOMPRA bigint,P_ID_COMPRA bigint) AS $body$
DECLARE

        L_ID_DETALLE bigint;
        L_ID_CTIPOIGV bigint;
        L_ID_ALMACEN bigint;
        L_ID_ARTICULO bigint;
        L_ID_TIPOIGV varchar(5);
        L_DETALLE varchar(255);
        L_CANTIDAD decimal(10,2);
        L_PRECIO decimal(10,2);
        L_BASE decimal(10,2);
        L_IGV decimal(10,2);
        L_IMPORTE decimal(10,2);
        L_ID_ANHO bigint;
        L_ID_PEDIDO bigint;
        L_ORIGEN varchar(10);
        L_ID_COMPROBANTE varchar(2);

        DETA CURSOR FOR		
        SELECT 
                B.ID_ALMACEN,B.ID_ARTICULO,C.ID_TIPOIGV,pkg_inventories_fc_articulo(B.ID_ARTICULO) AS NOMBRE_ARTICULO,B.CANTIDAD,B.PRECIO,B.BASE,B.IGV,B.IMPORTE
        FROM PEDIDO_COMPRA A JOIN PEDIDO_COMPRA_DETALLE B
        ON A.ID_PCOMPRA = B.ID_PCOMPRA
        JOIN INVENTARIO_ALMACEN_ARTICULO C
        ON B.ID_ALMACEN = C.ID_ALMACEN
        AND B.ID_ARTICULO = C.ID_ARTICULO
        AND C.ID_ANHO = L_ID_ANHO
        AND A.ID_PCOMPRA = P_ID_PCOMPRA;

BEGIN
            SELECT 
                    B.ID_PEDIDO,B.ID_ANHO INTO STRICT L_ID_PEDIDO,L_ID_ANHO
            FROM PEDIDO_COMPRA A JOIN PEDIDO_REGISTRO B
            ON A.ID_PEDIDO = B.ID_PEDIDO
            AND A.ID_PCOMPRA = P_ID_PCOMPRA;

            SELECT (SELECT X.ID_DEPTO FROM ORG_SEDE_AREA X WHERE X.ID_ENTIDAD = A.ID_ENTIDAD AND X.ID_SEDEAREA = coalesce(A.ID_AREAGASTO,A.ID_AREAORIGEN) ) ORIGEN
                INTO STRICT L_ORIGEN 
                FROM PEDIDO_REGISTRO A 
                WHERE A.ID_PEDIDO = L_ID_PEDIDO;

            SELECT ID_COMPROBANTE INTO STRICT L_ID_COMPROBANTE FROM COMPRA
            WHERE ID_COMPRA = P_ID_COMPRA;

            OPEN DETA;
                FETCH DETA INTO L_ID_ALMACEN,L_ID_ARTICULO,L_ID_TIPOIGV,L_DETALLE,L_CANTIDAD,L_PRECIO,L_BASE,L_IGV,L_IMPORTE;
                WHILE DETA%FOUND LOOP
                    --SELECT 
                    --        NVL(MAX(ID_DETALLE),0)+1 INTO L_ID_DETALLE
                    --FROM COMPRA_DETALLE;
                    IF L_ORIGEN = '12020102' AND L_ID_COMPROBANTE = '01' THEN  --FACTURA BAZAR
                        IF L_ID_TIPOIGV = '10' THEN 
                            L_ID_CTIPOIGV := 1;
                        ELSIF L_ID_TIPOIGV = '20' THEN
                            L_ID_CTIPOIGV := 4;
                        ELSE
                            L_ID_CTIPOIGV := 4;
                        END IF;
                    --ELSIF L_ORIGEN = '12020102' AND L_ID_COMPROBANTE = '03' THEN --BOLETA BAZAR
                    ELSIF L_ID_COMPROBANTE = '03' THEN  --TODAS LAS BOLETAS SON BASE 4
                        L_ID_CTIPOIGV := 4;
                        L_IGV := 0;
                        L_BASE := L_IMPORTE;
                    ELSIF L_ORIGEN = '11010111' AND L_ID_COMPROBANTE = '01' THEN  --FACTURA LOGSITICA
                        IF L_ID_TIPOIGV = '10' THEN
                            L_ID_CTIPOIGV := 3;
                        ELSIF L_ID_TIPOIGV = '20' THEN
                            L_ID_CTIPOIGV := 4;
                        ELSE
                            L_ID_CTIPOIGV := 4;
                        END IF;
                    ELSIF L_ORIGEN = '11010111' AND L_ID_COMPROBANTE = '03' THEN  --BOLETA LOGISTICA
                        L_ID_CTIPOIGV := 4;
                        L_IGV := 0;
                        L_BASE := L_IMPORTE;
                    ELSIF L_ORIGEN = '12020104' AND L_ID_COMPROBANTE = '01' THEN  --FACTURA COMEDOR
                        IF L_ID_TIPOIGV = '10' THEN
                            L_ID_CTIPOIGV := 3;
                        ELSIF L_ID_TIPOIGV = '20' THEN
                            L_ID_CTIPOIGV := 4;
                        ELSE
                            L_ID_CTIPOIGV := 4;
                        END IF;
                    ELSIF L_ORIGEN = '51010111' AND L_ID_COMPROBANTE = '01' THEN  --FACTURA LOGISTICA FJ
                        IF L_ID_TIPOIGV = '10' THEN
                            L_ID_CTIPOIGV := 3;
                        ELSIF L_ID_TIPOIGV = '20' THEN
                            L_ID_CTIPOIGV := 4;
                        ELSE
                            L_ID_CTIPOIGV := 4;
                        END IF;
                    ELSIF L_ORIGEN = '51010111' AND L_ID_COMPROBANTE = '03' THEN  --BOLETA LOGISTICA FJ
                        L_ID_CTIPOIGV := 4;
                        L_IGV := 0;
                        L_BASE := L_IMPORTE;
                    ELSIF L_ORIGEN = '52020102' AND L_ID_COMPROBANTE = '01' THEN  --FACTURA COMEDOR FJ
                        IF L_ID_TIPOIGV = '10' THEN
                            L_ID_CTIPOIGV := 1;
                        ELSIF L_ID_TIPOIGV = '20' THEN
                            L_ID_CTIPOIGV := 4;
                        ELSE
                            L_ID_CTIPOIGV := 4;
                        END IF;
                    ELSIF L_ORIGEN = '52020102' AND L_ID_COMPROBANTE = '03' THEN  --BOLETA COMEDOR FJ
                        L_ID_CTIPOIGV := 4;
                        L_IGV := 0;
                        L_BASE := L_IMPORTE;
                    ELSE
                        IF L_ID_TIPOIGV = '10' THEN
                            L_ID_CTIPOIGV := 1;
                        ELSIF L_ID_TIPOIGV = '20' THEN
                            L_ID_CTIPOIGV := 4;
                        ELSE
                            L_ID_CTIPOIGV := 4;
                        END IF;
                    END IF;

                    
                    INSERT INTO COMPRA_DETALLE(
                    --ID_DETALLE,
                    ID_COMPRA,ID_CTIPOIGV,ID_ALMACEN,ID_ARTICULO,ID_TIPOIGV,
                    DETALLE,CANTIDAD,PRECIO,BASE,IGV,IMPORTE,ORDEN,ESTADO)
                    VALUES (
                   --L_ID_DETALLE,
                   P_ID_COMPRA,L_ID_CTIPOIGV,L_ID_ALMACEN,L_ID_ARTICULO,L_ID_TIPOIGV,
                  L_DETALLE,L_CANTIDAD,L_PRECIO,L_BASE,L_IGV,L_IMPORTE,'0','1')
                 RETURNING ID_DETALLE INTO L_ID_DETALLE;

                FETCH DETA INTO L_ID_ALMACEN,L_ID_ARTICULO,L_ID_TIPOIGV,L_DETALLE,L_CANTIDAD,L_PRECIO,L_BASE,L_IGV,L_IMPORTE;
                END LOOP;
            CLOSE DETA;
            CALL pkg_purchases_sp_actualizar_total_compra(P_ID_COMPRA);
    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_purchases_sp_compra_detalle (P_ID_PCOMPRA bigint,P_ID_COMPRA bigint) FROM PUBLIC;
