-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

procedure pcd_eliminar_contrato_multiple
 is
  
  cursor contrato is
  select  * FROM AATEMP_ELIMINAR_CONTRATO_PCD aecp
  ;
    
 begin 
 
    for cc in contrato loop
      pcd_anular_contrato_alumno_n(cc.id_alumno_contrato);
    end loop;

 end;
 

