-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

PROCEDURE       PCD_UPDATE_STATE_MAT_PROGRAMA
IS
	CURSOR matricula_programa_list IS SELECT * FROM david.MATRICULA_PROGRAMA WHERE ESTADO = 1;
	fecha DATE;
	fecha_fin_programa_v DATE;
	id_matricula_programa_v NUMBER;
BEGIN
	
	FOR item IN matricula_programa_list LOOP

		SELECT mp.ID_MATRICULA_PROGRAMA, nvl(MP.fecha_fin, AMD.fecha_fin) AS fecha_fin INTO id_matricula_programa_v, fecha_fin_programa_v FROM david.MATRICULA_PROGRAMA mp
		JOIN david.ACAD_MATRICULA_DETALLE amd ON mp.ID_MATRICULA_DETALLE = amd.ID_MATRICULA_DETALLE 
		WHERE mp.ID_MATRICULA_PROGRAMA = item.id_matricula_programa;
	 
		IF TRUNC(fecha_fin_programa_v) < TRUNC(sysdate) THEN
		  -- DBMS_OUTPUT.PUT_LINE(id_matricula_programa_v || ' - ' || fecha_fin_programa_v);
		  UPDATE david.MATRICULA_PROGRAMA SET estado = '0' WHERE ID_MATRICULA_PROGRAMA = id_matricula_programa_v;
      commit;
		END IF;
	
	END LOOP;

END PCD_UPDATE_STATE_MAT_PROGRAMA;

