-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_sire,public;




CREATE OR REPLACE FUNCTION eliseo.pkg_sire_fc_proveedor_ruc (P_RUC_PROVEEDOR text) RETURNS bigint AS $body$
DECLARE

        L_ID_PERSONA bigint;

BEGIN
        SELECT ID_PERSONA INTO STRICT L_ID_PERSONA FROM (
       		SELECT ID_PERSONA
	        FROM MOISES.VW_PERSONA_JURIDICA
	        WHERE ID_RUC = P_RUC_PROVEEDOR
	        
UNION ALL

	        SELECT ID_PERSONA
	        FROM MOISES.VW_PERSONA_NATURAL
	        WHERE ID_TIPODOCUMENTO=6 AND NUM_DOCUMENTO=P_RUC_PROVEEDOR
        ) X LIMIT 1;

        RETURN(L_ID_PERSONA);
   END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION eliseo.pkg_sire_fc_proveedor_ruc (P_RUC_PROVEEDOR text) FROM PUBLIC;
