-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_sales_industry,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_sales_industry_sp_venta_guia_electronica (P_ID_VENTA_GUIA bigint) AS $body$
DECLARE

        L_ID_ENTIDAD bigint;
        L_RUC varchar(11);
        L_ID_COMPROBANTE varchar(2);
        L_SERIE varchar(4);
        L_NUMERO varchar(8);

        L_DET text;
        L_EMISOR_ID bigint:=101; --acesssss EMPRESA CON RUC UPeU
        L_HASH varchar(50);
        	

BEGIN  
        SELECT 
                ID_ENTIDAD,ID_COMPROBANTE,SERIE,NUMERO
                INTO STRICT L_ID_ENTIDAD,L_ID_COMPROBANTE,L_SERIE,L_NUMERO
        FROM VENTA_GUIA
        WHERE ID_VENTA_GUIA = P_ID_VENTA_GUIA;

        SELECT B.ID_RUC INTO STRICT L_RUC
        FROM CONTA_ENTIDAD A, CONTA_EMPRESA B
        WHERE A.ID_EMPRESA = B.ID_EMPRESA
        AND A.ID_ENTIDAD = L_ID_ENTIDAD;

        SELECT (pkg_sales_industry_fc_venta_guia(P_ID_VENTA_GUIA)) INTO STRICT L_DET;
        IF L_ID_ENTIDAD =7124 THEN  -- upeu
			SELECT ID INTO STRICT L_EMISOR_ID FROM VENTA_EMISOR WHERE RUC=L_RUC;
        	INSERT INTO VENTA_ELECTRONICA(EMISORID,ORIGENID,FECHA,TIPO,NROCOMPROBANTE,COMPROBANTE,NOMBREARCHIVO,PROCESADO,ENVIADO)
        	VALUES (L_EMISOR_ID,P_ID_VENTA_GUIA,clock_timestamp(),L_ID_COMPROBANTE,L_SERIE||'-'||L_NUMERO,L_DET,L_RUC||'-'||L_ID_COMPROBANTE||'-'||L_SERIE||'-'||L_NUMERO||'.txt',0,0);
        ELSIF L_ID_ENTIDAD =9415 THEN  --ACES
			SELECT ID INTO STRICT L_EMISOR_ID FROM VENTA_EMISOR_ACES vea WHERE RUC=L_RUC;
        	INSERT INTO VENTA_ELECTRONICA_ACES(EMISORID,ORIGENID,FECHA,TIPO,NROCOMPROBANTE,COMPROBANTE,NOMBREARCHIVO,PROCESADO,ENVIADO)
        	VALUES (L_EMISOR_ID,P_ID_VENTA_GUIA,clock_timestamp(),L_ID_COMPROBANTE,L_SERIE||'-'||L_NUMERO,L_DET,L_RUC||'-'||L_ID_COMPROBANTE||'-'||L_SERIE||'-'||L_NUMERO||'.txt',0,0);
        END IF;

    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_sales_industry_sp_venta_guia_electronica (P_ID_VENTA_GUIA bigint) FROM PUBLIC;
