-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = eliseo,pkg_accounting,public;




CREATE OR REPLACE PROCEDURE eliseo.pkg_accounting_sp_validar_voucher ( p_id_entidad bigint, p_id_depto text, p_id_anho bigint, p_id_tipovoucher bigint, p_id_persona bigint, p_id_voucher OUT bigint, p_numero OUT bigint, p_fecha OUT text, p_error OUT bigint, p_msn OUT text ) AS $body$
DECLARE

        l_cont       bigint;
        l_automatico varchar(4);
        l_msn        varchar(200) := 'VACIO';

BEGIN
        l_cont := 0;
        SELECT
            COUNT(1)
        INTO STRICT l_cont
        FROM
            conta_voucher_config
        WHERE
                id_entidad = p_id_entidad
            AND id_depto = p_id_depto
            AND id_anho = p_id_anho
            AND id_tipovoucher = p_id_tipovoucher;

        IF l_cont = 0 THEN
            p_error := 1;
            p_id_voucher := 0;
            p_numero := 0;
            l_msn := 'Alto! No existe una configuración de vouchers de tipo: ' || p_id_tipovoucher;
            p_fecha := '';
        ELSE
            SELECT
                automatico
            INTO STRICT l_automatico
            FROM
                conta_voucher_config
            WHERE
                    id_entidad = p_id_entidad
                AND id_depto = p_id_depto
                AND id_anho = p_id_anho
                AND id_tipovoucher = p_id_tipovoucher;

            IF l_automatico = 'S' THEN
                SELECT
                    COUNT(1)
                INTO STRICT l_cont
                FROM
                    conta_voucher
                WHERE
                        id_entidad = p_id_entidad
                    AND id_depto = p_id_depto
                    AND id_anho = p_id_anho
                    AND id_tipovoucher = p_id_tipovoucher
                    AND to_char(fecha, 'YYYYDDMM') = to_char(clock_timestamp(), 'YYYYDDMM');

                IF l_cont = 0 THEN
                    p_error := 0;
                    p_id_voucher := 0;
                    p_numero := 0;
                    p_fecha := '';
                    l_msn := 'OK: Aun no se genera el Primer Voucher Automatico';
                ELSE
                    SELECT
                        id_voucher,
                        numero,
                        to_char(fecha, 'DD/MM/YYYY')
                    INTO STRICT
                        p_id_voucher,
                        p_numero,
                        p_fecha
                    FROM
                        conta_voucher
                    WHERE
                            id_entidad = p_id_entidad
                        AND id_depto = p_id_depto
                        AND id_anho = p_id_anho
                        AND id_tipovoucher = p_id_tipovoucher
                        AND to_char(fecha, 'YYYYDDMM') = to_char(clock_timestamp(), 'YYYYDDMM');

                    l_msn := 'OK: Voucher Asigando';
                    p_error := 0;
                END IF;

            ELSE
                SELECT
                    COUNT(1)
                INTO STRICT l_cont
                FROM
                    conta_voucher         a,
                    conta_voucher_persona b
                WHERE
                        a.id_voucher = b.id_voucher
                    AND a.id_entidad = p_id_entidad
                    AND a.id_depto = p_id_depto
                    AND a.id_anho = p_id_anho
                    AND a.id_tipovoucher = p_id_tipovoucher
                    AND a.activo = 'S'
                    AND b.id_persona = p_id_persona
                    AND b.estado = '1';

                IF l_cont = 0 THEN
                    p_error := 1;
                    p_id_voucher := 0;
                    p_numero := 0;
                    p_fecha := '';
                    l_msn := 'Alto! Debe asignarse un voucher activo para provisionar comprobantes. ' || p_id_anho;
                ELSE
                    SELECT
                        a.id_voucher,
                        a.numero,
                        to_char(a.fecha, 'DD/MM/YYYY')
                    INTO STRICT
                        p_id_voucher,
                        p_numero,
                        p_fecha
                    FROM
                        conta_voucher         a,
                        conta_voucher_persona b
                    WHERE
                            a.id_voucher = b.id_voucher
                        AND a.id_entidad = p_id_entidad
                        AND a.id_depto = p_id_depto
                        AND a.id_anho = p_id_anho
                        AND a.id_tipovoucher = p_id_tipovoucher
                        AND a.activo = 'S'
                        AND b.id_persona = p_id_persona
                        AND b.estado = '1';

                    l_msn := 'OK: Voucher asigando';
                    p_error := 0;
                END IF;

            END IF;

        END IF;

        p_msn := l_msn;
    END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE eliseo.pkg_accounting_sp_validar_voucher ( p_id_entidad bigint, p_id_depto text, p_id_anho bigint, p_id_tipovoucher bigint, p_id_persona bigint, p_id_voucher OUT bigint, p_numero OUT bigint, p_fecha OUT text, p_error OUT bigint, p_msn OUT text ) FROM PUBLIC;
