-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = jairo,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_vin_grupo_beneficiario_id ON vin_grupo_beneficiario CASCADE;
CREATE OR REPLACE FUNCTION jairo.trigger_fct_tr_vin_grupo_beneficiario_id() RETURNS trigger AS $BODY$
begin
  select sq_vin_grupo_beneficiario_id.nextval
  into :new.id_grupo_beneficiario
  from dual;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION jairo.trigger_fct_tr_vin_grupo_beneficiario_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_vin_grupo_beneficiario_id ON vin_grupo_beneficiario;
CREATE TRIGGER tr_vin_grupo_beneficiario_id
	BEFORE INSERT ON vin_grupo_beneficiario FOR EACH ROW
	EXECUTE PROCEDURE jairo.trigger_fct_tr_vin_grupo_beneficiario_id();

