-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';
SET search_path = enoc,pkg_planilla,public;




CREATE OR REPLACE PROCEDURE enoc.pkg_planilla_sp_insertar_planilla_trab (P_ID_TRABAJADOR text,P_ID_PLANILLA bigint,P_ID_ANHO bigint,P_ID_MES bigint,P_ID_USER bigint,P_ID_PLANILLA_TRAB OUT text, P_ERROR OUT bigint,P_MSGERROR out text) AS $body$
DECLARE

    l_contar bigint;
    l_error bigint:=0;
    l_msgerror varchar(200):='';
    l_id_planilla_trab varchar(40);
    l_num_dias bigint;
    l_tipo_pago varchar(5);
    l_id_remuneracion bigint;
    l_id_anho bigint;
    l_horas bigint;
    l_num_vacacion bigint:=0;
    l_num_faltas  bigint:=0;
    l_dias bigint:=30;
    l_num_dias_calc bigint;
    l_inicio timestamp(0);
    l_fin timestamp(0);
    l_inicio_proc timestamp(0);
    l_fin_proc timestamp(0);
    l_inicio_mes timestamp(0);
    l_fin_mes timestamp(0);
    l_dias_mes bigint;

BEGIN
  
    l_inicio_mes:= to_date(P_ID_ANHO::text||'-'||P_ID_MES::text||'-01','YYYY-MM-DD');
    select ((date_trunc('month',(l_inicio_mes)::timestamp + interval '1 month'))::timestamp(0) - 1) into STRICT l_fin_mes;

    select fecha_inicio, fecha_fin_previsto 
    into STRICT l_inicio,l_fin
    from moises.trabajador
    where id_trabajador=P_ID_TRABAJADOR;

    if l_inicio>l_fin_mes then
      l_error:=1;
      l_msgerror:='No corresponde';
--       goto salida;
    end if;

    if l_inicio<l_inicio_mes then
      l_inicio_proc:=l_inicio_mes;
    else
      l_inicio_proc:=l_inicio;
    end if;

    if l_inicio_mes>l_fin then
      l_error:=1;
      l_msgerror:='No corresponde';
--       goto salida;
    end if;

    if (l_fin IS NOT NULL AND l_fin::text <> '') then
      if l_fin>l_fin_mes then
        l_fin_proc:=l_fin_mes;
      else
        l_fin_proc:=l_fin;
      end if;
    else
      l_fin_proc:=l_fin_mes;
    end if;

    select (l_fin_proc - l_inicio_proc)+ 1 into STRICT l_dias_mes;

    if (to_char(l_fin_mes,'DD'))::numeric =l_dias_mes then
      l_dias:=30;
    else
      l_dias:=l_dias_mes;
    end if;

    select 
    tipo_pago
    into STRICT
    l_tipo_pago
    from enoc.plla_remuneracion 
    where id_trabajador=P_ID_TRABAJADOR
    and vigencia=1;

    if l_tipo_pago='H' then
    
      select coalesce(sum(dias),0) into STRICT l_num_dias 
      from ENOC.plla_remuneracion_det 
      where id_remuneracion=l_id_remuneracion 
      and id_anho=P_ID_ANHO 
      and id_mes=P_ID_MES;

      l_num_dias_calc:=l_num_dias;

   else
      select
        coalesce(sum(case when ID_MOTIVO_ASIST='V' then NUM_HORAS else 0 end),0) as vacacion,
        coalesce(sum(case when ID_MOTIVO_ASIST in ('PLD') and tipo='SI' then NUM_HORAS else 0 end),0) as faltas
        into STRICT
        l_num_vacacion,
        l_num_faltas
      from enoc.PLLA_CONTROL_ASISTENCIA
      where id_trabajador=P_ID_TRABAJADOR
      and id_anho=P_ID_ANHO 
      and id_mes=P_ID_MES;

      l_num_dias:=l_num_vacacion + l_num_faltas;
      l_num_dias_calc:=l_dias - l_num_dias;
    end if;

    if l_num_dias_calc<0 then
      l_num_dias_calc:=0;
      l_error:=1;
      l_msgerror:='Cero días';
--       goto salida;
    end if;

    l_id_planilla_trab:= P_ID_PLANILLA::text||P_ID_TRABAJADOR::text;

    INSERT INTO ENOC.PLLA_PLANILLA_TRAB(
      ID_PLANILLA_TRAB,
      ID_PLANILLA,
      ID_TRABAJADOR,
      ID_CONTRATO,
      ID_SEDEAREA,
      ID_PERFIL_PUESTO,
      ID_SITUACION_TRABAJADOR,
      ID_CONDICION_LABORAL,
      ID_TIPO_TIEMPO_TRABAJO,
      ID_TIPO_CONTROL_PERSONAL,
      NUM_DIAS,
      NUM_DIAS_VACACION,
      NUM_DIAS_FALTAS,
      ID_PROCESO_BOLETA,
      ID_USER_REG, 
	    FECHA_REG
    )
    SELECT
      l_id_planilla_trab,
      P_ID_PLANILLA,
      ID_TRABAJADOR,
      ID_CONTRATO,
      ID_SEDEAREA,
      ID_PERFIL_PUESTO,
      ID_SITUACION_TRABAJADOR,
      ID_CONDICION_LABORAL,
      ID_TIPO_TIEMPO_TRABAJO,
      ID_TIPO_CONTROL_PERSONAL,
      l_num_dias_calc,
      l_num_vacacion,
      l_num_faltas,
      1,--1	Sin firma,
      P_ID_USER,
      clock_timestamp()
    FROM MOISES.TRABAJADOR
    WHERE ID_TRABAJADOR=P_ID_TRABAJADOR;

--     <<salida>>
    P_ID_PLANILLA_TRAB:=l_id_planilla_trab;
    P_ERROR:=l_error;
    P_MSGERROR:=l_msgerror;
  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE enoc.pkg_planilla_sp_insertar_planilla_trab (P_ID_TRABAJADOR text,P_ID_PLANILLA bigint,P_ID_ANHO bigint,P_ID_MES bigint,P_ID_USER bigint,P_ID_PLANILLA_TRAB OUT text, P_ERROR OUT bigint,P_MSGERROR out text) FROM PUBLIC;
