-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_ac_cur_plan_comp_id ON ac_cur_plan_comp CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_ac_cur_plan_comp_id() RETURNS trigger AS $BODY$
BEGIN
  select nextval('sq_ac_cur_plan_comp_id')
  into STRICT NEW.id_ac_cur_plan_comp
;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_ac_cur_plan_comp_id() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_ac_cur_plan_comp_id ON ac_cur_plan_comp;
CREATE TRIGGER tr_ac_cur_plan_comp_id
	BEFORE INSERT ON ac_cur_plan_comp FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_ac_cur_plan_comp_id();

