-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_adviser_sesion_pk ON adviser_sesion CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_adviser_sesion_pk() RETURNS trigger AS $BODY$
BEGIN
  select nextval('sq_adviser_sesion_id')
  into STRICT NEW.id_adviser_sesion
;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_adviser_sesion_pk() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_adviser_sesion_pk ON adviser_sesion;
CREATE TRIGGER tr_adviser_sesion_pk
	BEFORE INSERT ON adviser_sesion FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_adviser_sesion_pk();

