-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_clasificacion_comp_perf ON clasificacion_comp_perf CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_clasificacion_comp_perf() RETURNS trigger AS $BODY$
BEGIN
  SELECT nextval('david.sq_clasificacion_comp_perf')
  INTO STRICT NEW.id_CLASIFICACION_COMP_PERF
;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_clasificacion_comp_perf() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_clasificacion_comp_perf ON clasificacion_comp_perf;
CREATE TRIGGER tr_clasificacion_comp_perf
	BEFORE INSERT ON clasificacion_comp_perf FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_clasificacion_comp_perf();

