-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS tr_zoom_accounts ON zoom_acounts CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_tr_zoom_accounts() RETURNS trigger AS $BODY$
BEGIN
  SELECT nextval('david.zoom_acounts_seq')
  INTO STRICT   NEW.ID_ZOOM_ACOUNTS
;
 RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_tr_zoom_accounts() FROM PUBLIC;

DROP TRIGGER IF EXISTS tr_zoom_accounts ON zoom_acounts;
CREATE TRIGGER tr_zoom_accounts
	BEFORE INSERT ON zoom_acounts FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_tr_zoom_accounts();

