-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS trig_acad_semestre_beca ON acad_semestre_beca CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_trig_acad_semestre_beca() RETURNS trigger AS $BODY$
BEGIN
IF coalesce(NEW.ID_SEMESTRE_BECA::text, '') = '' THEN
SELECT nextval('david.sq_acad_semestre_beca_id')
INTO STRICT NEW.ID_SEMESTRE_BECA
;
END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_trig_acad_semestre_beca() FROM PUBLIC;

DROP TRIGGER IF EXISTS trig_acad_semestre_beca ON acad_semestre_beca;
CREATE TRIGGER trig_acad_semestre_beca
	BEFORE INSERT ON acad_semestre_beca FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_trig_acad_semestre_beca();

