-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.174.11.5;sid=upeu;port=1521

SET client_encoding TO 'UTF8';

SET search_path = david,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS trig_acad_plan_clase_rec_cod ON acad_plan_clase_recurso CASCADE;
CREATE OR REPLACE FUNCTION david.trigger_fct_trig_acad_plan_clase_rec_cod() RETURNS trigger AS $BODY$
DECLARE
    SEMESTER DAVID.ACAD_SEMESTRE.SEMESTRE%TYPE;
BEGIN
    IF coalesce(NEW.CODIGO::text, '') = '' THEN

        SELECT e.SEMESTRE INTO STRICT SEMESTER
        FROM DAVID.ACAD_PLAN_CLASE_RESULTADO a
                 INNER JOIN DAVID.ACAD_CARGA_TEMA b ON a.ID_CARGA_TEMA = b.ID_CARGA_TEMA
                 INNER JOIN DAVID.ACAD_CARGA_CURSO c ON b.ID_CARGA_CURSO = c.ID_CARGA_CURSO
                 INNER JOIN DAVID.ACAD_SEMESTRE_PROGRAMA d ON c.ID_SEMESTRE_PROGRAMA = d.ID_SEMESTRE_PROGRAMA
                 INNER JOIN DAVID.ACAD_SEMESTRE e ON d.ID_SEMESTRE = e.ID_SEMESTRE
        WHERE A.ID_PLAN_CLASE_RESULTADO = NEW.ID_PLAN_CLASE_RESULTADO;

        SELECT SEMESTER || '-' || NEW.ID_PLAN_CLASE_RESULTADO || '-R' ||
               nextval('david.sq_acad_plan_clase_rec_codigo') INTO STRICT NEW.CODIGO
;
    END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION david.trigger_fct_trig_acad_plan_clase_rec_cod() FROM PUBLIC;

DROP TRIGGER IF EXISTS trig_acad_plan_clase_rec_cod ON acad_plan_clase_recurso;
CREATE TRIGGER trig_acad_plan_clase_rec_cod
	BEFORE INSERT ON acad_plan_clase_recurso FOR EACH ROW
	EXECUTE PROCEDURE david.trigger_fct_trig_acad_plan_clase_rec_cod();

